### ISSUE TITLE
Adding undo handling in createThreadWithUsers

### ISSUE THREAD

**Issue by CalvinTp** [chat-sdk/chat-sdk-ios#10]
Hi Ben, Simon,
The codes has gone through major restructuring and it does add in more robustness on top of the core codes from the previous ChatSDK (which is already good). 

I wanted to feedback on the code related to createThreadWithUsers.

This codes used to be under: _ChatFirebaseAdapter/ChatFirebaseAdapter/Classes/Chatcat/BChatcatNetworkAdapter.m_

The codes in GitHub version is under:
_/FirebaseAdapter/Classes/Handlers/BFirebaseCoreHandler.m_

The feedback is as below:

When a new thread is created the database begin the UndoGroup incase there is an error found.
```
 [[BStorageManager sharedManager].a beginUndoGroup];
.......
 [[BStorageManager sharedManager].a endUndoGroup];

```

However when there is an error, it would be good to undo these database changes if there is an errors by calling the 
`        [[BStorageManager sharedManager].a undo];
`
Probably good to handle it when there is an error
```
    },^id(NSError * error) {
        if (threadCreated != Nil) {
            threadCreated(error, Nil);
        }
        return error;
    });
```

Thanks,
Calvin

**Comment by bensmiley** [comment]
Fix added in 4.2.1
