### ISSUE TITLE
Queries on 2 Factor Auth

### ISSUE THREAD

**Issue by CalvinTp** [chat-sdk/chat-sdk-ios#100]
Hi,
I am logging this as a question to the forum.

I am trying to enable 2 factor auth through Firebase UI Phone Auth and followed the steps provided in the ChatSDK and Firebase website. Although I manage to receive the sms with the codes, I failed to get it verified successfully after I entered the codes. 

Is anyone facing the similar issue?

Thanks,
Calvin

**Comment by CalvinTp** [comment]
Hi Ben/ Simon,
I still could not get the Firebase phone authentication to work on my side. Can you paste your App Delegate.h especially for:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

```

Thanks,
Calvin

**Comment by bensmiley** [comment]
This should be fixed using the [Firebase UI module](https://github.com/chat-sdk/chat-sdk-ios#firebase-ui).
