### ISSUE TITLE
Forgot Password support

### ISSUE THREAD

**Issue by FredrickJn** [chat-sdk/chat-sdk-ios#102]
Hey guys,

Is there a way to set up a Forgot Password feature?

**Comment by simonsmiley64** [comment]
Hi @FredrickJn,

This functionality is not currently added to the Chat SDK but there are tutorials on how to do it online. [Here](https://www.youtube.com/watch?v=gATutTzzbKY) is one using Swift which shouldn't be too hard to replicate with Objective-C. 

Simon

**Comment by bensmiley** [comment]
This has now been added.
