### ISSUE TITLE
exception in trying out the chat sdk demo

### ISSUE THREAD

**Issue by mylyuic** [chat-sdk/chat-sdk-ios#105]
Run into the following exception with the stack trace:

2017-07-26 14:36:38.072931-0700 ChatSDK Demo[24125:20267423] *** Assertion failure in -[UIButton keep_insetForSelector:edgeAttribute:coefficient:name:], /Users/yongmao/test/chat-sdk-ios/ChatSDK/ChatSDKUI/Classes/Libs/KeepLayout/KeepView.m:253
2017-07-26 14:36:38.083860-0700 ChatSDK Demo[24125:20267423] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Keep Layout: Calling keepBottomInset allowed only when superview exists'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010bfd4f6b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010b933121 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010bfd9fd2 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010b3e9c8a -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   ChatSDKUI                           0x000000010af4f68b -[UIView(KeepLayout) keep_insetForSelector:edgeAttribute:coefficient:name:] + 1643
	5   ChatSDKUI                           0x000000010af504a3 -[UIView(KeepLayout) keepBottomInset] + 83
	6   ChatSDKUI                           0x000000010af28cae -[BTextInputView init] + 2222
	7   ChatSDKUI                           0x000000010af358c0 -[ElmChatViewController setupTextInputView] + 64
	8   ChatSDKUI                           0x000000010af37465 -[ElmChatViewController viewDidLoad] + 901
	9   ChatSDKUI                           0x000000010aef3fa9 -[BChatViewController viewDidLoad] + 57
	10  UIKit                               0x000000010cd0a137 -[UIViewController loadViewIfRequired] + 1235
	11  UIKit                               0x000000010cd0a584 -[UIViewController view] + 27
	12  ChatSDKUI                           0x000000010af3555e -[ElmChatViewController initWithDelegate:] + 350
	13  ChatSDKUI                           0x000000010aef3edb -[BChatViewController initWithThread:] + 139
	14  ChatSDKUI                           0x000000010aefc08a -[BDefaultInterfaceAdapter chatViewControllerWithThread:] + 90
	15  ChatSDKUI                           0x000000010af1d9b2 -[BProfileTableViewController pushChatViewControllerWithThread:] + 130
	16  ChatSDKUI                           0x000000010af1d7ab __48-[BProfileTableViewController startChatWithUser]_block_invoke + 107
	17  ChatSDKFirebaseAdapter              0x000000010ac9dd04 __65-[BFirebaseCoreHandler createThreadWithUsers:name:threadCreated:]_block_invoke + 100
	18  RXPromise                           0x000000010b2063da __76-[RXPromise registerWithExecutionContext:onSuccess:onFailure:returnPromise:]_block_invoke_3 + 90
	19  libdispatch.dylib                   0x000000010fce46dd _dispatch_call_block_and_release + 12
	20  libdispatch.dylib                   0x000000010fce56c8 _dispatch_client_callout + 8
	21  libdispatch.dylib                   0x000000010fcf127b _dispatch_main_queue_callback_4CF + 614
	22  CoreFoundation                      0x000000010bf98289 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	23  CoreFoundation                      0x000000010bf5cc32 __CFRunLoopRun + 2162
	24  CoreFoundation                      0x000000010bf5c149 CFRunLoopRunSpecific + 409
	25  GraphicsServices                    0x00000001125459d7 GSEventRunModal + 62
	26  UIKit                               0x000000010cb7691d UIApplicationMain + 159
	27  ChatSDK Demo                        0x000000010a8b332f main + 111
	28  libdyld.dylib                       0x000000010fd69b65 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

Any idea why?

**Comment by simonsmiley64** [comment]
Hi @mylyuic,

Do you receive this error after downloading and running the Chat SDK or after making some modifications?

I would expect it was something to do with this error:

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Keep Layout: Calling keepBottomInset allowed only when superview exists'
```

Have you made any modifications to views that could have caused this?

Simon

**Comment by mylyuic** [comment]
No, i only updated the GoogleService-Info.plist

**Comment by simonsmiley64** [comment]
When downloading the Chat SDK for the first time it is worth running and compiling it would making any changes, this lets you get it working to test out the functionality. 

Depending on the changes you made to the plist will depend on how to fix the issue. 

Have you gone through the step by step guide for getting the Chat SDK set up? You can find detailed tutorials [here](https://github.com/chat-sdk/chat-sdk-ios/wiki).

I would recommend the following:

1. Download a new version, compile it and ensure it is working on your system
2. Follow the steps to configure it on your own custom Firebase account
3. Test it to ensure it has been correctly configured (you can watch in real time the database updating when it is working and you create users or send messages)

It is important to make sure you have followed the steps correctly before making your own modifications as it is very difficult to troubleshoot if you have changed anything.

Hopefully this helps, let me know if you are still having issues after trying this,

Simon
