### ISSUE TITLE
Can't inherit BDefaultInterfaceAdapter in Swift?

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#107]
When I tried to inherit and then override a function it crashes:

       override func defaultTabBarViewControllers() -> [Any] {
        return [self.privateThreadsViewController, self.contactsViewController, self.profileViewController(with: nil)]
    }

I did create an Objective-C version and that worked.

**Comment by bensmiley** [comment]
What kind of crash are you getting?

**Comment by bensmiley** [comment]
See #138.
