### ISSUE TITLE
Use Backendless version 3.0

### ISSUE THREAD

**Issue by CalvinTp** [chat-sdk/chat-sdk-ios#108]
Hi,
I am logging this so that ChatSDK users can benefit from this (also note that this is only applicable for those that use Backendless for push notification).

**Ensure:**
Please ensure that you are using version 3.* of Backendless with ChatSDK so your pod file needs to be something similar to the line below:
`pod 'Backendless’,’~>3.0.0’`

**Reason:**
Backendless has transition to version 4.* so if you leave the version blank such as below and has previously not build with version 3.*, you will face issues because your project will load with version 4.*:
`pod 'Backendless’`

Thanks,
Calvin

**Comment by RyanElliott94** [comment]
@CalvinTp I was hoping this was the reason notifications weren't working for me but I'm still having problems! I don't suppose you know of any solutions? 

I have an issue open [Here](https://github.com/chat-sdk/chat-sdk-ios/issues/106).

Thanks,
Ryan

**Comment by CalvinTp** [comment]
@RyanElliott94 I have no issue with Backendless when I enabled the module in ChatSDK but I am using other push notification for my app due to other reasons. 

Did you check your dashboard in Backendless whether the push notification has been sent? Their dashboard will let you know how many messages has been sent and also the users which has been registered. This will give you a hint on your issue. 

Btw, where did you copy over the BBackendless* module codes? Do ensure that you copied them at the root directory. 

Did you also enable the modules in the AppDelegates?  

Thanks,
Calvin

**Comment by RyanElliott94** [comment]
@CalvinTp Well i know that the iOS devices show up but when i try to send a push notification from the Backendless website, nothing works. 

Now I don't actually think it's suppose to do anything but i also have a feeling it doesn't actually do what i think it does and that's show banners or alerts but only add a badge which only updates when a user go into the app then out again.

So what i really need is to be able to get a notification when a new message comes in but the user has the app in the background.

I mentioned in my post that i saw another post along with others saying that Firebase removes observers automatically when the app is in the background.

Oh and I've got the module in the root directory as it says in the readme and i do have it activated too.

Ryan

**Comment by RyanElliott94** [comment]
Sorry for hijacking the issue! So it looks like i can send a notification from Backendless and now i just need to send a notification when a message is sent and to then show it

**Comment by RyanElliott94** [comment]
I've managed to fix my issue now, it turns out the pushToChannels method wasn't working correctly so notifications weren't actually being sent or received!
