### ISSUE TITLE
Chat SDK questions

### ISSUE THREAD

**Issue by createch-info** [chat-sdk/chat-sdk-ios#109]
Hi,

We're looking to use chat SDK API for an iOS native app we're building, and have the following questions after researching the website for features & pricing.

1) How are daily active users calculated? Is this the number of users (not messages) active on a given day?

2) Is there a limit on how many messages a user can send on a day?

3) Does the free version includes the ability to send messages with pictures/videos and documents?

4) Are there any initial setup or licensing fee if we're looking to start with the free version and upgrade as we scale?

Thank you,
Sri

**Comment by simonsmiley64** [comment]
Hi @createch-info,

Thanks for getting in touch,

1. Daily active users is calculated looking at the average number of messages a given user might send and how long a user will be online. During the life of the Chat SDK so far we have gradually improved the functionality to ensure there is no lag on messages being sent and received. We have apps build around Chat SDK which have 10s of thousands of daily users. As the number of users on Chat SDK has grown in the last few years we have gradually improved to code to ensure excellent performance on projects both large and small.

2. Chat SDK provides no limits on messages being sent. That being said the database does rely on Firebase which has limits depending on which tier you are on. You can check this out [here](https://firebase.google.com/pricing/). We find that the free version is more than enough for a large number of users. The great thing about Firebase is that you can scale up your plan to meet the demand of your user base.

3. The free version includes the ability to send text, image and location messages. If you want to send audio and video messages you will need to purchase the additional module, you can check these out [here](https://chatsdk.co/modules/) with audio or video being $99 per license per platform. We currently don't have document messages but if you send us an email we could chat to you about the specifications.

4. There is no initial setup or license fee. You just download the code and off you go. Checkout our wiki pages and youtube tutorials to help you get going and also post tickets if you have problems. We normally respond within a day and have a number of community developers who have used the Chat SDK enough to often help on issues. The only licensing fees would be, as mentioned above, from any modules you might want to add. 

We always recommend downloading the project and getting started then you can see what compliments your project and think about licensing that if needed. 

We also offer priority support if you need a bit of additional help and have a lot of experience integrating the Chat SDK into projects. If in doubt just raise a ticket we'll do our best to explain how to structure and code your desired outcome. 

Let me know if you have any other questions and I'll do my best to answer them. 

Simon

**Comment by createch-info** [comment]
Thanks for quick response @Simon!
