### ISSUE TITLE
Trying to Run with Backendless get this error

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#110]
Terminating app due to uncaught exception of class 'Fault'
I am using the v3 version as suggested in a different thread.

Have no idea on how to track this down. Backendless says it has something to do with a first time user and catching the fault in code.

**Comment by bensmiley** [comment]
We have now removed Backendless support from the project. I would recommend using the [Firebase Push Notifications](https://github.com/chat-sdk/chat-sdk-ios#push-notifications) and [Firebase File Storage](https://github.com/chat-sdk/chat-sdk-ios#file-storage) modules instead.
