### ISSUE TITLE
Update Documentation! 

### ISSUE THREAD

**Issue by expertalex** [chat-sdk/chat-sdk-ios#111]
In the documentation you are mentioning FUser and it isn't exists. Do you mean PUser ? Can you make a better documentation about your architecture and how to change it? For example what if I will like to change the chat UI. 

Regards
Alex

**Comment by simonsmiley64** [comment]
Hi @expertalex,

If you can link to the documentation you are talking about I can look into it. Is it a single instance of the wrong character being used or is FUser used in the entire documentation? With he improvements we are constantly making to the Chat SDK there will sometimes be times we miss a tutorial while updating - sorry about that. 

We currently recommend posting an issue ticket if you want to change the UI. When we have time, we will post documentation on specific modifications to the UI but always appreciate people letting us know what they want - how to add custom cells, how to modify the chat cells, etc etc.

Looking forward to hearing from you,

Simon
