### ISSUE TITLE
Set the Current User

### ISSUE THREAD

**Issue by lacvapps** [chat-sdk/chat-sdk-ios#113]
Hello I am currently authenticating with a custom token, then I try 'createThreadWithUsers' it fails because the  currentUserModel is null. What am I missing, I do not see anywhere where I can set the currentUserModel

**Comment by bensmiley** [comment]
In the latest version of the code use:

```
[NM.auth authenticate:[BAccountDetails token:@"Your Token"]];
```

In previous versions:

```
[NM.auth authenticateWithDictionary:@{bLoginTypeKey: @(bAccountTypeCustom), bLoginCustomToken: @"Your Token"}];
```
