### ISSUE TITLE
Delete Thread Status

### ISSUE THREAD

**Issue by CalvinTp** [chat-sdk/chat-sdk-ios#114]
Hi Ben, Simon,
There is a small bug in the latest code, for deleteThread:
`-(RXPromise *) deleteThread {`

The code added that only if there are **2 users the delete status will be added**. This will cause an issue later if the user re-install the app. This is because if the chat room has more than 2 participant, when the user left, the code did not log the delete status. The code inside the deleteThread which has issue is the following: 
```
    if (_model.type.intValue & bThreadFilterPrivate && _model.users.allObjects.count == 2) {
        // Rather than delete the thread we just set the status as deleted
        [currentThreadUser setValue:@{bNameKey: currentUser.name, bDeletedKey: [FIRServerValue timestamp]}
```

In the messagesOn for the thread: 
`-(RXPromise *) messagesOn {`

The code will look for the startDate and if deleteDate is available, it will use the deleteDate as priority. 
```
        // If there are messages we only fetch messages since the
        // last message
        if (messages.count) {
            startDate = ((id<PMessage>)messages.firstObject).date;
        }
        else {
            // TODO: Add limit
            startDate = [_model.lastMessageAdded dateByAddingTimeInterval:-bDays * 3650];
        }
        
        // If thread is deleted
        if (deletedDate) {
            startDate = deletedDate;
        }
```

Since the deleteDate is missing when the app is re-install, the user will receive all the previously deleted thread. Therefore the code should always update the delete status for a group chat. 

Thanks,
Calvin

**Comment by bensmiley** [comment]
If the thread is a private group i.e. a private thread with more than 2 members, the user should just be removed from the thread:

```
    else {
        
        // We still want to notify the user to refresh the view
        [[NSNotificationCenter defaultCenter] postNotificationName:bNotificationThreadDeleted object:Nil];
        
        // Otherwise we just remove the user
        return [self removeUser:[CCUserWrapper userWithModel:currentUser]];
    }
```

Is this not working?
