### ISSUE TITLE
Localization of ChatUILocalizable.strings

### ISSUE THREAD

**Issue by ilyanengen** [chat-sdk/chat-sdk-ios#117]
Dear developers and experienced users of chat SDK, 

**What is the proper way to localize strings of chat sdk?**

I have found ChatUILocalizable.strings file, where all strings are stored,  but need help to add another language.

Hope for your support.
 
@jimijon @bensmiley  @simonsmiley64  @kykrueger

**Comment by bensmiley** [comment]
I'd recommend looking at this [tutorial](https://www.raywenderlich.com/64401/internationalization-tutorial-for-ios-2014). Also at the Apple documents on [localization](https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/LocalizingYourApp/LocalizingYourApp.html).

**Comment by simonsmiley64** [comment]
Hi @ilyanengen,

Did you manage to get the localization working?
