### ISSUE TITLE
How to retrieve only my contact list on firebase chat? can you explain or any other documentation? 

### ISSUE THREAD

**Issue by Advick** [chat-sdk/chat-sdk-ios#118]
Contact fetch on only my mobile device, its list on my firebase chat any documentation or explain how to do this?

**Comment by simonsmiley64** [comment]
Hi @Advick,

We have a module available for the Chat SDK which does this, you can check out the details [here](https://chatsdk.co/downloads/contact-book-integration/)

Let me know if you have any further questions,

Simon
