### ISSUE TITLE
Android to iOS Chat issue

### ISSUE THREAD

**Issue by Ghana93** [chat-sdk/chat-sdk-ios#12]
1. iOS device receiving blank message from android Device.

2. Android device receiving Multiple copies of single message from iOS device.

**Comment by simonsmiley64** [comment]
I have just downloaded the iOS and Android versions of the Chat SDK. The Android version was previously on a different Firebase path than the iOS one so I have changed them to be set up on the same one and pushed the changes. This means you should be able to download and immediately run both projects on the same database. 

When testing this the iOS with Android messaging worked fine with both devices receiving the expected messages in the correct format and number. 

Can you confirm whether you are running the base projects or if this has occurred once switching to your own Firebase account?

We can then help find out what is causing this problem to occur.

Simon
