### ISSUE TITLE
Getting error while running on device can anyone help ?

### ISSUE THREAD

**Issue by sunilhs1986** [chat-sdk/chat-sdk-ios#121]
Hi,

Getting the below error while compiling on device.

dyld: Library not loaded: @rpath/Firebase.framework/Firebase
  Referenced from: /private/var/containers/Bundle/Application/2E99ECFB-6B99-4DF1-9525-A699B8803A27/InjuryApp.app/Frameworks/ChatSDKFirebaseAdapter.framework/ChatSDKFirebaseAdapter
  Reason: image not found

Regards
Sunil

**Comment by simonsmiley64** [comment]
Hi @sunilhs1986,

Are you still having this issue? Could you post more details on when it is occurring if you are?

Simon

**Comment by simonsmiley64** [comment]
Hi @sunilhs1986,

If you can post any solutions to how you solved this issue it could potentially help other users facing it in the future.

Simon
