### ISSUE TITLE
How do I change the tabbar icon?

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#122]
What is the proper way to use my own icons for the tab bar?

**Comment by bensmiley** [comment]
You should subclass the ViewControllers that in the tab bar that need custom icons. Next look at the guide on customizing the [user interface](https://github.com/chat-sdk/chat-sdk-ios/wiki/Exploring-the-Chat-SDK-Architecture#customizing-the-user-interface). You can subclass the [BDefaultInterfaceAdapter](https://github.com/chat-sdk/chat-sdk-ios/blob/master/ChatSDK/ChatSDKUI/Classes/Manager/BDefaultInterfaceAdapter.m) then override the `defaultTabBarViewControllers` method returning an array of your subclasses. You should then set your interface adapter in the AppDelegate.

```
[BInterfaceManager sharedManager].a = [[YourInterfaceAdapter alloc] init];
```

Then in the ViewController subclass you can override the `viewDidLoad` method and set the image:

```
self.tabBarItem.image = [UIImage imageNamed:@"your-image.png"];
```
