### ISSUE TITLE
Updated profile image for user

### ISSUE THREAD

**Issue by sunilhs1986** [chat-sdk/chat-sdk-ios#126]
Hi,

i am trying to update the profile image, but its crashing can someone please help.

Getting exc_bad access in the below line of code in BProfileTableViewController.m

    [NM.upload uploadImage:image thumbnail:thumbnail].thenOnMain(^id(NSDictionary * urls) {

Regards
Sunil

**Comment by sunilhs1986** [comment]
@bensmiley  let me know if you can help with this.

Regards
Sunil

**Comment by simonsmiley64** [comment]
Hi @sunilhs1986,

Below is the full code you have added a snippet from:

```
    // Update the user
    id<PUser> user = NM.currentUser;
    [user setImage:UIImagePNGRepresentation(image)];
    [user setThumbnail:UIImagePNGRepresentation(thumbnail)];
    
    // Set the image now
    [NM.upload uploadImage:image thumbnail:thumbnail].thenOnMain(^id(NSDictionary * urls) {
    
        // Set the meta data
        [user setMetaString:urls[bImagePath] forKey:bUserPictureURLKey];
        [user setMetaString:urls[bThumbnailPath] forKey:bUserPictureURLThumbnailKey];
    
        // Update the user
        [NM.core pushUser];
    
        return urls;
    }, Nil);
``` 

Can you confirm exactly what you are trying to do and what is causing you issues?

For example does the code in the Chat SDK work for you without modification? Download a new version from Github and then try modifying the user image.

If this is working then there is going to be a problem with the modifications you have made to the code. Can you add a break point and confirm exactly where the code is getting the error? Do you have a currently registered user? Is your Firebase account correctly linked and authenticated?

Simon

**Comment by sunilhs1986** [comment]
Hi Simon,

I am trying to update the profile picture in profile page of the app and it crashes once i select picture and click done in crop image page.

Attached screenshot for reference.

Regards
Sunil
![screen shot 2017-09-27 at 8 38 25 pm](https://user-images.githubusercontent.com/31177194/30921728-c9550594-a3c4-11e7-9581-89d81837ff45.png)

**Comment by simonsmiley64** [comment]
Have you made any modifications to the code? I tested this on a recent version of the Chat SDK and this functionality works as expected. 

Have you added a breakpoint in the uploadImage function to see what is going wrong?

**Comment by ilyanengen** [comment]
@simonsmiley64 @sunilhs1986 @bensmiley 
Hello Simon, 
I downloaded chat sdk ios about 4 month ago and updated it only few days ago when I needed a iOS 11 crash fix. The fix worked, but the new problem appeared - I faced the same problem as sunilhs1986 has.

I guess that the reason of the crash is connected with File Storage. 
Is now File Storage Module required to activate in AppDelegate to upload an image/thumbnail ?

 #import "BFirebaseFileStorageModule.h"
[[[BFirebaseFileStorageModule alloc] init] activate];
(from https://chatsdk.co/docs/ios-quickstart/)

Best regards,
Ilya

**Comment by bensmiley** [comment]
@ilyanengen, Have you enabled the [File Storage module](https://github.com/chat-sdk/chat-sdk-ios#file-storage)?

**Comment by ilyanengen** [comment]
@bensmiley 
No,  #import "BFirebaseFileStorageModule.h" doesn't work in AppDelegate. "BFirebaseFileStorageModule.h" file not found.

**Comment by bensmiley** [comment]
I think you need to include the files - look at the general instructions [here](https://github.com/chat-sdk/chat-sdk-ios#firebase-modules). 

> Copy the module code into your Xcode source folder and add the files to your project from inside Xcode. If you are using the symlink you can use the symlink script (mentioned above) and then just add a link to the ChatSDKFirebase folder to Xcode.

> Add any necessary dependencies to your Podfile
Import the module's header file (or add it to the bridging header for a Swift project)

> Activate the module in the AppDelegate.m file

You need to either manually add the Firebase File Storage files into Xcode or add the `ChatSDKFirebase` folder via symlink. 

![screen shot 2017-10-18 at 7 45 55 pm](https://user-images.githubusercontent.com/5514010/31733795-fc15a96a-b43c-11e7-9a08-e8956fa0ba6d.png)

**Comment by ilyanengen** [comment]
@bensmiley 
Thank you very much! It works now :)
