### ISSUE TITLE
crashes when setting textInputView

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#129]
setupTextInputView

If I don't initialize that in the ElmChatViewController it doesn't crash. Some auto layout issue it seems:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'NSLayoutConstraint for <UIButton: 0x7fe4f225dd60; frame = (0 0; 0 0); opaque = NO; layer = <CALayer: 0x604000220ec0>>: A multiplier of 0 or a nil second item together with a location for the first attribute creates an illegal constraint of a location equal to a constant. Location attributes must be specified in pairs.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001150d41cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001141f5f41 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000115148b95 +[NSException raise:format:] + 197
	3   Foundation                          0x000000010f08bb63 ResolveConstraintArguments + 891
	4   Foundation                          0x000000010ee81c0d +[NSLayoutConstraint constraintWithItem:attribute:relatedBy:toItem:attribute:multiplier:constant:] + 80
	5   ChatSDKUI                           0x000000010d826b96 -[KeepConstantAttribute createConstraintWithRelation:value:] + 254
	6   ChatSDKUI                           0x000000010d826368 -[KeepSimpleAttribute setEqual:] + 345
	7   ChatSDKUI                           0x000000010d813f31 -[BTextInputView init] + 1334
	8   ChatSDKUI                           0x000000010d81bfd6 -[ElmChatViewController setupTextInputView] + 53
	9   ChatSDKUI                           0x000000010d81d1a3 -[ElmChatViewController viewDidLoad] + 554
	10  ChatSDKUI                           0x000000010d7f205c -[BChatViewController viewDidLoad] + 50
	11  UIKit                               0x0000000111634d51 -[UIViewController loadViewIfRequired] + 1235
	12  UIKit                               0x000000011163519e -[UIViewController view] + 27
	13  ChatSDKUI                           0x000000010d81bdc1 -[ElmChatViewController initWithDelegate:] + 220
	14  ChatSDKUI                           0x000000010d7f1fe0 -[BChatViewController initWithThread:] + 102
	15  ChatSDKUI                           0x000000010d7f766a -[BDefaultInterfaceAdapter chatViewControllerWithThread:] + 69
	16  CryptoTrader                        0x000000010ae719e5 _T012CryptoTrader24TileDetailViewControllerC8openChatyypFypSgAEcfU_ + 741
	17  CryptoTrader                        0x000000010ae71e62 _T012CryptoTrader24TileDetailViewControllerC8openChatyypFypSgAEcfU_TA + 66
	18  CryptoTrader                        0x000000010ae714c5 _T0ypSgAAIxir_yXlSgABIyBya_TR + 229
	19  RXPromise                           0x00000001109363da __76-[RXPromise registerWithExecutionContext:onSuccess:onFailure:returnPromise:]_block_invoke_3 + 90
	20  libdispatch.dylib                   0x00000001167c13f7 _dispatch_call_block_and_release + 12
	21  libdispatch.dylib                   0x00000001167c243c _dispatch_client_callout + 8
	22  libdispatch.dylib                   0x00000001167cd6f0 _dispatch_main_queue_callback_4CF + 628
	23  CoreFoundation                      0x0000000115096ef9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	24  CoreFoundation                      0x000000011505b662 __CFRunLoopRun + 2402
	25  CoreFoundation                      0x000000011505aa89 CFRunLoopRunSpecific + 409
	26  GraphicsServices                    0x00000001190279c6 GSEventRunModal + 62
	27  UIKit                               0x0000000111496d30 UIApplicationMain + 159
	28  CryptoTrader                        0x000000010aead3f7 main + 55
	29  libdyld.dylib                       0x000000011683ed81 start + 1
)
libc++abi.dylib: terminating with uncaught exception of

**Comment by simonsmiley64** [comment]
Hi @jimijon,

Can you explain what modifications you are attempting to make and what changes you added to get this crash?

I can then troubleshoot and work out the best solution to help fix it,

Simon

**Comment by jimijon** [comment]
I’m commented out my subclass to make sure it wasn’t me. Maybe it’s an iOS 11 issue.

Don’t remember it happening before the upgrade

**Comment by simonsmiley64** [comment]
We haven't had any specific tickets relating to iOS 11. Can you load it up on an iOS 10 simulator and see if the problem still occurs? This way we can determine whether this is primarily and iOS issue.

**Comment by jimijon** [comment]
Works on 10 crashes on 11

**Comment by jimijon** [comment]
Sadly I was hoping to submit to Apple today.  :-(

**Comment by jimijon** [comment]
It's definitely in:

    _textInputView = [[BTextInputView alloc] init];

**Comment by simonsmiley64** [comment]
Hi @jimijon,

Have you added a break point to see where this error is occurring? I will look at this next week and try to get a fix pushed to the repository.

Simon

**Comment by jimijon** [comment]
Problem is. It crashes adding the gesture to the field. So some constraint or the order in which it is being done sets it up to crash from how it was initialized. A lot is going on in the init. 

You can’t do it in IB instead of code?

**Comment by jimijon** [comment]
Any of the commented out lines below will crash the app. Commenting them out also then makes the textfield unusable. May I suggest you just create your special view bar with IB and auto layout? 

        // Constrain the elements
//        _optionsButton.keepLeftInset.equal = bMargin;// +keepRequired;

//        _optionsButton.keepBottomInset.equal = 8.0;
        _optionsButton.keepHeight.equal = 24;
        
        // If the user has no chat options available then remove the chat option button width
        _optionsButton.keepWidth.equal = [BInterfaceManager sharedManager].a.chatOptions.count ? 24 : 0;
        
        _optionsButton.translatesAutoresizingMaskIntoConstraints = NO;
        
//        _sendButton.keepRightInset.equal = bMargin;
//        _sendButton.keepBottomInset.equal = 0;
        _sendButton.keepHeight.equal = 40;
        _sendButton.keepWidth.equal = 48;
        _sendButton.translatesAutoresizingMaskIntoConstraints = NO;
        
        _textView.keepLeftOffsetTo(_optionsButton).equal = bMargin;
        _textView.keepRightOffsetTo(_sendButton).equal = bMargin;
//        _textView.keepBottomInset.equal = bMargin;
//        _textView.keepTopInset.equal = bMargin;
        _textView.translatesAutoresizingMaskIntoConstraints = NO;

**Comment by simonsmiley64** [comment]
Hi @jimijon,

I am going to have a look at this today so will hopefully have a fix by the end of the day (AEST). I'll keep you updated with how I go and the progress I make.

Simon

**Comment by simonsmiley64** [comment]
Hi @jimijon,

It looks like the problem is coming from the version of [KeepLayout](https://github.com/Tricertops/KeepLayout) the Chat SDK is using. This is a library which is manually added to the Chat SDK in the ChatUI pod. 

I expect there will be a few changes required to the code when you swap the old one for the new one. One I found so far is 

    [tableView.keepBottomOffsetTo(_textInputView) remove];

with

    [tableView.keepBottomOffsetTo(_textInputView) deactivate]; 

I will continue looking into this and will try to get a build pushed which works. I wanted to get in touch with you here in case you you want to do some testing around this yourself.

Simon

**Comment by simonsmiley64** [comment]
Hi @jimijon,

I am going to move discussion of these issue to [ticket #130](https://github.com/chat-sdk/chat-sdk-ios/issues/130). 

If you view this thread I have developed some code to allow you to continue developing and coding with the Chat SDK. It is not a comprehensive fix but should be better than the app crashing with iOS 11 devices. 

We will try to get this fixed as soon as possible.

Simon
