### ISSUE TITLE
Obj-C to Swift issue

### ISSUE THREAD

**Issue by samdory** [chat-sdk/chat-sdk-ios#13]
Hi!
I'm writing my own code in Swift using this SDK.
But I have lots of problems with Objective-C code on the page of [here](http://chatsdk.co/docs/ios-quickstart/).
I found some code in Swift from Demo example (AppDelegate.swift), but the rest of code, I can't translate.
Could you guide me how to do it?

**Comment by bensmiley** [comment]
Hi,
Unfortnately, if you want to work with the SDK you will need to get used to reading Objective-C. Maybe this [converter](https://objectivec2swift.com) would help you out...
