### ISSUE TITLE
Can the profile picture url be for a local resource on the user's device?

### ISSUE THREAD

**Issue by GreenRollingHills** [chat-sdk/chat-sdk-ios#133]
This is more of a question than an issue.  

I want to have several pre-built images that users can select from for their profile picture.  I was hoping to store these images locally on the user's device.  Then I was hoping to subclass, extend, etc the  chatSDK so that there was a way to reference and display these locally stored images.  I looked at the code and I can't find an easy way to do this.  Is this true?

Thanks,

**Comment by simonsmiley64** [comment]
I would recommend not changing the way it currently occurs - I should be easy to fit this functionality in with the Chat SDK.

The Chat SDK:

- Sets a users profile picture online
- Adds it to their user object 
- Watches other users for whether their picture has changed
- Downloads and stores the users profile picture (this means it is only downloaded once and updated if it changes)

Depending on what your functionality requires I would do the following.

- Set a default profile picture for all users (currently we have one and it shouldn't be too hard to find where this is set)
- Choose where you want the local images to be selected (eg the profile view)
- Subclass this view
- When the user loads up the profile view and clicks the change picture button load a new view showing the pictures - the user then chooses from these
- This picture is then set as the user's profile in the regular way

As you can see this maintains the Chat SDK flow meaning that other users will still update your current users profile pic. Also with the way Chat SDK is designed it isn't like we download/upload each profile picture more than once. 

If you still have reservations about doing it like this then let me know more details on what you are trying to do and I'll see if this affects the best way.

Simon

**Comment by GreenRollingHills** [comment]
Thanks for the response.  

I guess my only reservation would be unnecessary storage costs of these images. Even though I will only have around 50 images there will be at least one image per user stored in firebase.  And what if the user changes the image?  Will the old one get removed from firebase? But firebase offers 50G at 25/month.  So, my storage cost concerns are probably not much to worry about. 

But an alternative solution: How about hosting the images on firebase by manually uploading them (in Storage not realtime database) via the console.  Then get each image’s download url and manually create an array of these urls in my tableViewController that is going to display these images to the user.  Then use SDWebImage framework (which is already part of my project because it is a dependency of chatSDK) to download and cache them.  Then when user selects an image I just get that image's url and call the NM.currentUser().setImageURL(string) method passing in the appropriate url String followed by the usual update commands.  This way I only store 50 images vs 1 per user.

**Comment by simonsmiley64** [comment]
I would personally stick to how it is currently done, by my calculations:

Approx time to develop new way and testing: 10 hours minimum (probably closer to 20)
Cost of your time per hour: $30-$100
Expected cost of functionality: $450 - $1500 worth of your time (based on 15 hours)

If Firebase is only $25 a month (and that is once you reach the max limit which will require a huge amount of users) then you still have between 18 - 60 months cost which you have saved by not developing this. 

Factor in the fact that your users will have no idea this functionality is even there (as it will work just the same) and I wouldn't recommend you spending too much time on this. 

Obviously we are happy to advice you on the best way to do it if you do decide to go ahead with these modifications but in my opinion there are probably more important features to put the time/money behind. 

Let me know what you decide and if we can be of any help,

Simon

**Comment by bensmiley** [comment]
@GreenRollingHills The easiest approach would be to host your images online somewhere. This could be using Firebase file storage or any other image hosting platform. When you allow the user to select an image, you can load these images directly from the web storage using the SDWebImage library. The Chat SDK never stores images on Firebase - it only stores a link to the image. So whatever solution you decide to use, there won't be a big hit in the data transfer cost.
