### ISSUE TITLE
table cell not displaying properly

### ISSUE THREAD

**Issue by chintan217** [chat-sdk/chat-sdk-ios#134]
Hello,
I have integrated chat sdk in my ios project.
I am first login to app and start chat. then I logout to app and login from different ID. In BMessageCache I am getting isMine property is always NO. Please help me to fix this issue

**Comment by simonsmiley64** [comment]
Hi @chintan217,

Can you confirm if this problem occurs when you download the normal Chat SDK project and test it before integrating it into your project? This will help us see if it is a problem with the SDK or an issue which has been introduced through your code modifications,

Simon

**Comment by chintan217** [comment]
Finally found a solution,
When logout, I have written below code.
`[[BMessageCache sharedCache] clear];`

**Comment by bensmiley** [comment]
Ah ok, this is currently called in the `logout` method in the `BProfileTableViewController`. I'll move it to the logout method in the `BFirebaseAuthenticationHandler`.
