### ISSUE TITLE
Thread 1: Signal SIGBRT

### ISSUE THREAD

**Issue by Lavii7** [chat-sdk/chat-sdk-ios#14]
when running the app and doing this after downloading from git this is what i get: first part is step to re-perform and second is the location of the error screen shot also there and then the actual error log. 
Step A:(REPERFORMANCE STEPS) 
1.) Search for contact  and add to contact 
2.) Chat with that contact you added (Note-> for some reason creating a chat thread takes a bit more time) 
3) When you open the app after few hours --> you will see the chat thread of conversation but the contact that was added disappears.
Besides this while testing I noted 2 additional things: when you click on Chat from the added contacts the app crashes and all the contacts disappear( i think it kinda re-sets as new) Note also that I have noticed that when you flag also app crashes.
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 

LOCATION OF CODE CRASH: BCOREDATAMANAGER.M

-(void) beginUndoGroup {
    [self.managedObjectContext.undoManager beginUndoGrouping];
}

-(void) endUndoGroup {
    [self.managedObjectContext.undoManager endUndoGrouping];
}
![screen shot 2017-03-03 at 3 02 38 pm](https://cloud.githubusercontent.com/assets/26152547/23572237/8d48a560-0022-11e7-974e-aca35fb0dbe5.png)

ERROR LOG:
(
    "<NSLayoutConstraint:0x17094850 V:[UITextField:0x17272190(30)]>",
    "<NSLayoutConstraint:0x170ae7e0 V:|-(8)-[UILabel:0x170d2ab0'No new users found for th...']   (Names: '|':UIView:0x17004050 )>",
    "<NSLayoutConstraint:0x170b1e00 V:[UILabel:0x170d2ab0'No new users found for th...']-(375)-|   (Names: '|':UIView:0x17004050 )>",
    "<NSLayoutConstraint:0x15f11e30 V:|-(85)-[UITextField:0x17272190]   (Names: '|':UIView:0x171ea5c0 )>",
    "<NSLayoutConstraint:0x15f05240 V:[UIButton:0x17277480'Button']-(20)-[UIView:0x17004050]>",
    "<NSLayoutConstraint:0x15fdca30 V:[UIView:0x17004050]-(0)-|   (Names: '|':UIView:0x171ea5c0 )>",
    "<NSLayoutConstraint:0x15f03e70 UIButton:0x17277480'Button'.bottom == UITextField:0x17272190.bottom>",
    "<NSLayoutConstraint:0x1716a380 'UIView-Encapsulated-Layout-Height' V:[UIView:0x171ea5c0(480)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x170b1e00 V:[UILabel:0x170d2ab0'No new users found for th...']-(375)-|   (Names: '|':UIView:0x17004050 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2017-03-03 14:46:59.525 ChatSDKSwift[735:377471] Creating: CDUser
2017-03-03 14:46:59.610 ChatSDKSwift[735:377471] Creating: CDUser
2017-03-03 14:47:11.084 ChatSDKSwift[735:377471] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '_endUndoGroupRemovingIfEmpty:: NSUndoManager 0x17032980 is in invalid state, endUndoGrouping called with no matching begin
'
*** First throw call stack:
(0x225f791b 0x21d92e17 0x225f7861 0x22db13f5 0x15a0eb 0x169429 0x37374b 0x1479b7f 0x1479b6b 0x147e655 0x225b9b6d 0x225b8067 0x22507229 0x22507015 0x23af7ac9 0x26bdb189 0xf8270 0x221af873)
libc++abi.dylib: terminating with uncaught exception of type NSException
warning: could not load any Objective-C class information. This will significantly reduce the quality of type information available.
(lldb)

**Comment by simonsmiley64** [comment]
Hi @Lavii7,

I have pushed a fix for the undo grouping. I think we were calling endUndoGrouping twice in a row by mistake. This was causing the crash. This would also correspond to the app crashing when you were trying to load a thread as the thread would be created and then the app would crash.

**Comment by Lavii7** [comment]
yup that was the issue.
