### ISSUE TITLE
"_OBJC_CLASS_$_FIRAnalytics" from Firebase Analytics

### ISSUE THREAD

**Issue by JoseMGavilan** [chat-sdk/chat-sdk-ios#142]
Hello, I'm getting almost the same error that was reported in the issue #119 

`Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FIRAnalytics", referenced from:
      objc-class-ref in FireBaseManager.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
note: symbol(s) not found for architecture arm64` 

I've read that these error was fixed with an update but I still have this other error.

Can anyone help me with this issue please?

**Comment by bensmiley** [comment]
Are you using the latest version of the code and importing the Firebase module to your Xcode project manually rather than using CocoaPods?

**Comment by JoseMGavilan** [comment]
Yes, I'm using the latest version of the code (I'm fact I've downloaded this morning) and yes, I'm  importing the Firebase module to my Xcode project manually because I'm not using CocoaPods.

**Comment by bensmiley** [comment]
Are you using CocoaPods at all? Can you paste in your Podspec file?

**Comment by JoseMGavilan** [comment]
Nope, I'm not using CocaPods

**Comment by bensmiley** [comment]
So how are you adding the Firebase libraries?

**Comment by JoseMGavilan** [comment]
Manually ...  I've followed the instructions in [https://firebase.google.com/docs/ios/setup](url) in _Integrate without CocoaPods_ . I did the same with RemoteConfig and is working.

**Comment by bensmiley** [comment]
The issue looks like it's caused by you not having imported the Firebase libraries correctly.  Actually the error isn't to do with the Chat SDK because the FireBaseManager isn't a Chat SDK class. It's a Firebase class that is referencing another class that's not linked properly. I'd recommend double checking how you added the Firebase libraries and if you still see the issue, contacting Firebase support.

**Comment by JoseMGavilan** [comment]
It is fixed, I don't know why the library wasn't added to the correct target, even when I selected the target when I added the library . Thanks for try to help me.
