### ISSUE TITLE
Crash in CCThreadWrapper

### ISSUE THREAD

**Issue by rfgallagher1** [chat-sdk/chat-sdk-ios#144]
Hey there - just started playing with library or otherwise I'd just issue a pull request or something.

Line 471 in CCThreadWrapper
        `_model.entityID = ref.key;`

Line 474 calls self.serialize
Line 420
`b_CreatorEntityID: _model.creator.entityID}};`

model.creator.entityID is nil, and the app crashes. 

Should line 471 be setting model.creator (and thus 466 checking for model.creator), or should 420 be retrieving the value from model.entityID, or neither of those for a reason I haven't found yet?

**Comment by bensmiley** [comment]
Well line 417 shouldn't be setting the creator `entityID`, because it's actually setting the thread `entityID`. The creator should be set when the thread is created or deserialized. Can you tell me the steps you take in order to reproduce the crash (with the unmodified code from Github)?

**Comment by rfgallagher1** [comment]
I created a new project, integrated ChatSDK step by step according to docs, and try to create a public thread:
`BNetworkManager.shared().a.publicThread().createPublicThread(withName: "test")`

Crashes because `b_CreatorEntityID: _model.creator.entityID}};` isn't set

**Comment by bensmiley** [comment]
Could you put in a breakpoint inside `createPublicThread` at the line:

```
threadModel.creator = currentUserModel;
```

I expect that the current user is Nil. Could you also tell me how you're authenticating?

Thanks,

Ben

**Comment by rfgallagher1** [comment]
Gah! Yeah that's it. I thought if I was going "public" the whole way then I didn't need to authenticate at all. After authenticating anonymously I'm golden. Thanks homie.
