### ISSUE TITLE
Compiler error in NM.m

### ISSUE THREAD

**Issue by ealeksandrov** [chat-sdk/chat-sdk-ios#148]
Opening braces left in 2af45b7b329471d5781f42e7e42d230b123ceb8d

<img width="1435" alt="screen shot 2017-10-26 at 21 40 33" src="https://user-images.githubusercontent.com/3132438/32070931-72190f80-ba96-11e7-8313-dc8415c3cd6a.png">

Not impacting real users since it's not yet released, but adds some pain when trying example projects.

I suggest adding integration like TravisCI even without tests just to check for successful compilation status on commits and pull requests.

**Comment by bensmiley** [comment]
I'll look at adding some integration tests. This should be fixed in the latest commit.
