### ISSUE TITLE
Typing indicator retrieving instruction 

### ISSUE THREAD

**Issue by Lavii7** [chat-sdk/chat-sdk-ios#15]
Hi Guys, have posted the crash here on github as requested. Also please note that i have done all my updated & have been waiting on you guys to send the instructions for where to retrieve the typing indicator (Ben you are my contact through the e-mail commuication) and if you know the solution for this crash on the latest code. 
Thanks,

**Comment by simonsmiley64** [comment]
Hi @Lavii7,

The typing indicator is one of the additional modules available for the Chat SDK. You can check them all out [here](http://chatsdk.co/modules-2/). Once you buy a module we can then send you the additional modules required to get it up and running with your project. 

I have posted a reply and pushed a commit of the project which hopefully should fix the issues you were having. 

Let me know if you need further information and I will do my best to help you as best I can,

Simon

**Comment by Lavii7** [comment]
Hi Simon, thanks for the update on crash will update that on my end. 
As to the "Typing Indicator" I am not asking where i can get it :) from as I have already gotten the typing indicator from you in the past; i am asking for an update on it, as the one I have is the one before completely parse indipendent; please communicate with Ben as it has been 5 days now since i have been waiting on this from your end. 
I will forward you the information I have commuicated with Ben to your e-mail. 

Thanks,

**Comment by simonsmiley64** [comment]
Hi @Lavii7,

You can email me at: simon_smiley@hotmail.com

If you already have the typing indicator we can send you a free download code so you can download it straight from our website. 

I will close this ticket now and we can deal with this over email

Simon
