### ISSUE TITLE
Decrease the framework sizes

### ISSUE THREAD

**Issue by efdalustaoglu** [chat-sdk/chat-sdk-ios#153]
I'm already integrated ChatSDK to my current project and using it without any problem. However after I added ChatSDK for the first time the app size is increased with 30 mb (I checked it with the iOS Testflight app size comparisons). Where I'm specifically using the ChatSDK is that social login (only G+, FB & Twitter logins no custom login page), main chatrooms view & details of the chatroom view. 

I exported my project and take a look at the framework files. For example ChatUI.framework is 7,2mb & Realm 50mb (I might be wrong, realm maybe not using in ChatSDK). I know maybe after it will be sent to iOS App store, it will be downgraded a bit but still it is considerably too much. My question is, is there a way to decrease the app size by removing or decreasing the sizes of frameworks **or** if I choose to use ChatSDK, Realm, Firebase, FB, G+, Twitter login frameworks this app increase will be something I have to ignore?

**Comment by bensmiley** [comment]
By my calculation, the Chat SDK is only 5.2mb (i.e. the compiled framework). However, the app containing the Chat SDK is over 60mb. I think that most of this is probably due to Apple Frameworks. Have you measured the size of the final App Store payload? Apple probably strip a lot out of the binary for distribution.

**Comment by bensmiley** [comment]
When I exported the app the size came down to 22.9 mb. It would probably be less on the device since Apple will further strip unused assets and frameworks. Since I don't think that 5mb is an unreasonable size, I'm closing the issue for the time being.
