### ISSUE TITLE
Tableview lagging issue

### ISSUE THREAD

**Issue by chintan217** [chat-sdk/chat-sdk-ios#155]
In ElmChatViewController screen, Tableview scrolling not smoothly working. tableview lagging when scrolling. I have tested in iphone 5 with 10.3.1 .

**Comment by bensmiley** [comment]
I'll look into doing some optimization but this is likely partly due to the age of the device. The iPhone 5 was released over 5 years ago which is a long time in mobile terms. I have an iPhone 6 and it's starting to get laggy in some mainstream apps like WhatsApp.

**Comment by chintan217** [comment]
Other chat applications like whatsapp working proper in iphone 5. Tableview is too lagging in your chat sdk. I think this is too major issue. I have created video for issue in iphone 5. Check this link for watch video : https://drive.google.com/file/d/1DcuiyeFmVObyXvqPI_Bh0oCDaLcX167_/view?usp=sharing

**Comment by snipe717** [comment]
I am also experiencing some lag, running on iPhone 8, if you scroll the chat or conversations view, it stutters as you scroll. I have been trying to look at what I could do to optimise things.

**Comment by bensmiley** [comment]
This should be addressed in the latest version - 4.5.4. There were several issues:
- Images loading while scrolling
- Location messages causing a big memory leak
- Some retain cycles 
This has now been tested on an iPhone 6 and it's working well on long threads with a lot of images and locations.

**Comment by snipe717** [comment]
Much improved, thanks!!
