### ISSUE TITLE
BChatSDK missing?

### ISSUE THREAD

**Issue by GreenRollingHills** [chat-sdk/chat-sdk-ios#157]
Hello,

I just integrated ChatSDK (4.3.3).  In `CCUserWrapper` in `-(void) updateUserFromAuthUserData: (FIRUser *) user` there are these lines:

```
if (!_model.messageColor || !_model.messageColor.length) {
        _model.messageColor = [BCoreUtilities colorToString:[BCoreUtilities colorWithHexString:[BChatSDK shared].configuration.messageColorMe]];
    }
```

But I can't find BChatSDK in the pods or in the ChatSDKFirebaseAdapter folder.  Did I do something wrong in my integration?

**Comment by bensmiley** [comment]
Try running `pod update` to get the latest version from CocoaPods. As you can [see](https://github.com/chat-sdk/chat-sdk-ios/tree/master/ChatSDKCore/Classes/Session) the file exists.
