### ISSUE TITLE
Push notification implementation

### ISSUE THREAD

**Issue by pankti28** [chat-sdk/chat-sdk-ios#158]
Hi,
I have read in some issue that backendless is removed from chat sdk. so what is the other procedure to work with push notification in chat sdk? 
I have already completed the chat implementation in my app , it's just the push notification that is not working.
Please guide.

Thanks,
pankti

**Comment by bensmiley** [comment]
Are you using version 3.x or version 4.x?

**Comment by pankti28** [comment]
hi,
I didn't get the version. I have cloned the project from Github about 4 months ago.please help me out.


Thanks in advance.pankti 

    On Wednesday, 15 November 2017 6:09 PM, bensmiley <notifications@github.com> wrote:
 

 Are you using version 3.x or version 4.x?—

**Comment by bensmiley** [comment]
I'd recommend updating to the latest version of the library and using the module I mentioned above. If you have modified the source code, you can still merge your branch with the latest version. The library hasn't changed significantly in the last 4 months.

**Comment by pankti28** [comment]
ok. thanks. I got the version in podspec. it is 4.2.5 for chatsdkcore .

**Comment by pankti28** [comment]
Thank you @bensmiley. It was build error. I was trying to import the module which was not build properly , so unable to access the method of that module.
Now, its working fine. thanks for your support . :) :) 👍
