### ISSUE TITLE
Trouble intergrating the SDK 

### ISSUE THREAD

**Issue by reubenlim1994** [chat-sdk/chat-sdk-ios#161]
Hi guys, im a relatively new ios dev and i've been trying to intergrate the project into a test project of mine. My goal is to use this as a base project and build on top of it using firebase. 

i tried following every step of this tutorial made by Ben( https://www.youtube.com/watch?v=3OWF_qyieXQ&list=PL6uMXvdftGbsCl09y_1Ytt5x016JcdsZW&index=9 ) but i've still encountered several errors , i am building this on top of a swift test project 
here's a screenshot of the error messages i'm encountering 

![screen shot 2017-11-29 at 4 39 17 pm](https://user-images.githubusercontent.com/30619980/33365669-eb681136-d523-11e7-863a-72560fcd56d0.png)

i would appreciate any help i can get ! Thanks a bunch guys

**Comment by bensmiley** [comment]
I think the instructions you're using are outdated. Can you try using the instructions contained [here](https://github.com/chat-sdk/chat-sdk-ios#adding-the-chat-sdk-to-your-project)?

**Comment by reubenlim1994** [comment]
Hi Ben, 

Thank you for the quick response, i've tried the new instructions and it worked, 

however im facing a user registration issue as you can see here . 
![screen shot 2017-11-30 at 12 19 37 pm](https://user-images.githubusercontent.com/30619980/33412843-fab7c118-d5c8-11e7-9890-fdd7dce9f79b.png)

as you can see i have enabled the user sign in method on firebase for email/ password. but the app still does not allow me to register. 
<img width="936" alt="screen shot 2017-11-30 at 12 19 59 pm" src="https://user-images.githubusercontent.com/30619980/33412847-039f8496-d5c9-11e7-9522-73dc46056c20.png">

i tried creating users manually on firebase here and i am able to sign in with these email + password

<img width="934" alt="screen shot 2017-11-30 at 12 20 09 pm" src="https://user-images.githubusercontent.com/30619980/33412890-46a9ed94-d5c9-11e7-8060-5e96d15be9a4.png">

once again, thanks Ben !

**Comment by bensmiley** [comment]
Have you updated the project to run off your Firebase account? I expect that you have enabled sign in on a Firebase database that isn't the one the project is using. You need to make sure that the app is registered properly and that the Google-Services.plist file is correct. So:

1. Look at the plist and check that the app identifier is correct
2. Check that the Firebase database path in the plist is the same as the one where sign in is enabled.

**Comment by reubenlim1994** [comment]
Yes, i've updated the project to run on my personal firebase. Both the app identifier and database path is correct, as you can see i am able to push information into the firebase database in the screenshot below however still unable to register through the application.

<img width="893" alt="screen shot 2017-11-30 at 4 48 54 pm" src="https://user-images.githubusercontent.com/30619980/33539246-5f12c772-d900-11e7-81a8-3a343dd7a8d8.png">

After poking around i tried to enable anonymous login and got a different error message upon pressing the register button by filling in the text fields.
<img width="258" alt="screen shot 2017-12-04 at 2 46 49 pm" src="https://user-images.githubusercontent.com/30619980/33539979-d614cca0-d903-11e7-9946-0eda30969296.png">

if i choose to leave the text fields blank it shows this error message instead and creates a annonymous user in the database. 
![screen shot 2017-12-04 at 3 01 24 pm](https://user-images.githubusercontent.com/30619980/33540145-a9464a86-d904-11e7-9dca-77523defdfc7.png)
<img width="937" alt="screen shot 2017-12-04 at 2 47 11 pm" src="https://user-images.githubusercontent.com/30619980/33540154-b5b9697e-d904-11e7-8c9b-1fe44e2bc0f8.png">

**Comment by pankti28** [comment]
I am facing the same issue after updating to new SDK . have you find any solution?

**Comment by bensmiley** [comment]
When I test this I don't get any error which makes me think that this must be a configuration issue. Can you share a link to the project so I can test it myself? Also, add me to the Firebase database so I can see the data using bensmiley45 (at) gmail [dot] com.

**Comment by reubenlim1994** [comment]
Helllo @pankti28  @bensmiley , updating to the latest chatsdk pod has seem to fixed this problem for me. Thank you ben for the support that you've given! @pankti28 , do let me know if i could do anything to help :)

**Comment by bensmiley** [comment]
Thanks @reubenlim1994. @pankti28  to use the latest pod be sure to run `pod update`.
