### ISSUE TITLE
Customizng UI Tutorial / guide

### ISSUE THREAD

**Issue by jupiter0107** [chat-sdk/chat-sdk-ios#162]
Hello,i am a new ios developer currently i am trying customizing the UI from the pod extension itself, i have a few questions. 

1. will this reset if i update the ChatSDK pod? what would happen when i update the chatSDK pod? if so, what are the best practices in editing the user interface? 
2.I have read both [this](https://github.com/chat-sdk/chat-sdk-ios/wiki/Exploring-the-Chat-SDK-Architecture#customizing-the-user-interface) and [this](https://github.com/chat-sdk/docs#customizing-the-user-interface-1) however i am unfamiliar with subclassing the UI elements
is there any other tutorials  in depth written documentations that i could follow for coding in swift?

**Comment by bensmiley** [comment]
Hi @jupiter0107,

I've updated this guide to give [explicit instructions](https://github.com/chat-sdk/docs#modifying-the-ui-directly) on how to update the Chat SDK directly in a safe way. 

I'd recommend having a look at [this](http://www.techotopia.com/index.php/An_Introduction_to_Swift_Subclassing_and_Extensions) it's a general guide to subclassing in Swift. If you tell me specifically what you don't understand, I'd be happy to provide further explanation.
