### ISSUE TITLE
Interacting with firebase ( pushing data in ) 

### ISSUE THREAD

**Issue by jupiter0107** [chat-sdk/chat-sdk-ios#164]
Hello Ben, this is a follow-up question regarding my previous post 

So i've followed your first solution as to put the group chat under section 2 so that the participant section will always be first. this works as a quick fix. however i am trying to find out how to interact with firebase directly to update the group chat name.

i went through some of the other view controllers to see how it threads are created eg:( BPrivateThreadViewController) . but i'm still not quite able to grasp how the SDK is interacting with firebase directly. (with nm.core etc.). Perhaps there's an example which you could show me or even documentations which i can follow.

Here is a screenshot. what i would want to achieve is to be able to update the "name" under details

<img width="586" alt="screen shot 2017-12-12 at 6 44 57 pm" src="https://user-images.githubusercontent.com/34261628/33881265-3c4047ae-df6f-11e7-9920-9f26379f448a.png"> 

Also i would love to contribute to the project once i've completed this. its the least i can do after all the support you've given, and to give back just a little to the chatsdk community! :)

**Comment by bensmiley** [comment]
To update the group name, you should set the name field on the `id<PThread>` object i.e. thread.name = @"Some name". After that, you need the `CCThreadWrapper` object. 

```
RXPromise * promise = [[CCThreadWrapper threadWithModel: thread] push];
```

This will update the thread directly on Firebase. If you are interested in the lower level details of how entities are synchronized with Firebase you should look at the three wrapper objects - thread, message and user.

**Comment by reubenlim1994** [comment]
@bensmiley I am writing this code on the BUsersViewController.m and unable to use the CCThreadWrapper object. the error message reads " Use of undeclared identifier 'CCThreadWrapper'. how do i go about using the wrapper objects if i would to edit the code inside the chatsdk pod itself?

**Comment by jupiter0107** [comment]
@bensmiley  i am writing this code in BUsersViewController.m and i'm unable to access the CCThreadWrapper object, the error message reads . 'Use of undeclared identifier 'CCThreadWrapper'. How do i go about using the wrapper objects when im writing / editing code from the podfile itself?

**Comment by bensmiley** [comment]
You wouldn't be able to use the `CCThreadWrapper` from inside the `ChatUI` or `ChatCore` modules. The correct way to do this is to subclass the `InterfaceAdapter` - see [here](https://github.com/chat-sdk/docs#customizing-the-user-interface-1). If you do that, then from inside your subclass, you will be able to access all the classes from the `ChatFirebaseAdapter`.

**Comment by jupiter0107** [comment]
Once again Thanks @bensmiley for the support. 

This is how i wrote my class in swift. 

    
    class MyAppInterfaceAdapter: BDefaultInterfaceAdapter {

    
    override func usersViewController(with thread: PThread!, parentNavigationController parent: UINavigationController!) -> UIViewController! {
        let usersVC = BUsersViewController(thread: thread)
        usersVC?.parentNavigationController = parent
        if(usersVC?.isBeingDismissed == true) {
        var _: RXPromise? = CCThreadWrapper.thread(withModel: thread).push()
        }
        return usersVC
    }

however this part of the code does not work,  

            if(usersVC?.isBeingDismissed == true) {
        var _: RXPromise? = CCThreadWrapper.thread(withModel: thread).push()
        }

if i would to write the code like this then it would only push the thread into firebase upon viewing the BUsersViewController which is not ideal. 

        override func usersViewController(with thread: PThread!, parentNavigationController parent: UINavigationController!) -> UIViewController! {
        let usersVC = BUsersViewController(thread: thread)
        usersVC?.parentNavigationController = parent
        var _: RXPromise? = CCThreadWrapper.thread(withModel: thread).push()
        return usersVC
    }
    

i am trying to get the data to push into firebase as the back button is pressed.

**Comment by bensmiley** [comment]
I can see that you have overridden the interface adapter. But when you override the `usersViewController`, it looks like you're returning the standard `BUsersViewController` rather than your own subclass. 

The correct approach would be to make a subclass of the users view controller and add your code there.

**Comment by jupiter0107** [comment]
Thanks @bensmiley  this worked! :)
