### ISSUE TITLE
ios group chat load

### ISSUE THREAD

**Issue by janisInn** [chat-sdk/chat-sdk-ios#168]
Hi.
In our app we make group chats in backend side. Problem is that when group chat is made (in firebase) it right away appears on Android, but on iOS it only appears when someone (android user) writes something in it. 
Is it possible to solve that appears instantly also on iOS.

https://imgur.com/T7SX37J

**Comment by bensmiley** [comment]
This will be fixed in the next release. I've added a new property to the configuration object:

```
@property (nonatomic, readwrite) BOOL showEmptyChats;
```

This will have the value `NO` as default but can be set to `YES` during setup to solve the issue you're having.

**Comment by janisInn** [comment]
Thank you! When the next release will be out?
