### ISSUE TITLE
iOS Objective-C Google+ login fails

### ISSUE THREAD

**Issue by wazowski78** [chat-sdk/chat-sdk-ios#17]
Hi,

this is the log I am seeing when I try to log in with Google+ option:

```
2017-03-11 13:38:54.433330 HeyYapp[11061:4063335] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'uiDelegate must either be a |UIViewController| or implement the |signIn:presentViewController:| and |signIn:dismissViewController:| methods from |GIDSignInUIDelegate|.'
*** First throw call stack:
(0x181a351b8 0x18046c55c 0x181a35100 0x100493114 0x10049562c 0x100492288 0x1000aab40 0x10009e6c8 0x1000b2a38 0x1000fba88 0x18791fd30 0x18791fcb0 0x18790a128 0x18791f59c 0x18791f0c4 0x18791a328 0x1878eada0 0x1880d475c 0x1880ce130 0x1819e2b5c 0x1819e24a4 0x1819e00a4 0x18190e2b8 0x1833c2198 0x1879557fc 0x187950534 0x100023fbc 0x1808f15b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

Any hint on this issue?

**Comment by simonsmiley64** [comment]
Hi @wazowski78,

We are currently working on getting the Google login up and running. Currently the Google login isn't configured on the cloned project. This is why you are getting this error.

We will be trying to release a fix for this in the next few weeks. If you want to attempt adding a fix yourself this is what we would recommend, and what we will be implementing:

1. The Google login delegate seems to need a viewController to login successfully. We have tried assigning the UI delegate to a different viewController to the one the regular delegate has been set to and this doesn't work.
2. This means we are going to create a Google helper viewController which will immediately appear once the user clicks the Google login button. This will then trigger the login flow on this viewController.
3. Once the user has been logged in this VC will disappear. We will then show the login screen which will check for a logged in user and also be dismissed. 

We have done quite substantial testing on linking the Google login to our current flow and haven't been able to get it working but this method should be able to link in seamlessly to the user experience. 

I will comment on this issue once we have pushed a working version of the Google login code.

Simon

**Comment by wazowski78** [comment]
Hello,
and thank you very much for your feedback about this issue. I have been working on it, and I found what you have said, it seems Google Sign in must be a ViewController to present the login view of google. 

I have figure out this and at this moment I have a working login, I have to test if all the data is stored properly and finish some cleaning in the code in order to keep the flow of it.

**Comment by simonsmiley64** [comment]
Hi @wazowski78,

If you can post some code snippets, or even better a pull request, then we can look over your Google login code and add it to the main project. 

Simon

**Comment by simonsmiley64** [comment]
Hi @wazowski78,

I have just pushed a beta version of the Google login to the master branch. 

I am now going to close this issue

Simon
