### ISSUE TITLE
Include sound + vibration upon sending / recieving text messages 

### ISSUE THREAD

**Issue by jupiter0107** [chat-sdk/chat-sdk-ios#171]
Hello @bensmiley , i noticed that the chatSDK does not have any sound + vibration, how do i go about implementing this feature for different sounds when sending and receiving text messages and vibration upon receiving text messages ?

**Comment by bensmiley** [comment]
If you want to do this by listening to some app-wide notifications. You can see all the notifications that are available [here](https://github.com/chat-sdk/chat-sdk-ios/blob/master/ChatSDKCore/Classes/BNetworkFacade.h).

You could listen for the `bNotificationMessageAddedKeyMessage` notification and then make the phone vibrate:

```
AudioServicesPlayAlertSound(kSystemSoundID_Vibrate);
```

Or play a sound:

```
let path = Bundle.main.url(forResource: name, withExtension: ext)
var soundId: SystemSoundID = 0;
AudioServicesCreateSystemSoundID(path! as CFURL, &soundId)
AudioServicesPlaySystemSound(soundId)
```

When it's received.

**Comment by jupiter0107** [comment]
works great @bensmiley thanks! 

What about a banner drop down notification (simmilar to whatsapp) , how do i go about implementing that feature into the sdk?

**Comment by ChintanWeapp** [comment]
I added this solution to my chatViewController and when I entered into it than only It'll play the sound. If the application is terminated it will not playing sound. How to resolve this issue? (p.s. I'm doing my code in objective C)

**Comment by bensmiley** [comment]
@ChintanWeapp I don't understand exactly what you mean. Can you tell me exactly which code you're adding to to where? What kind of exception messages are you getting?

**Comment by ChintanWeapp** [comment]
Oh! sorry for inconvenience. I added the code in my ChatViewController as following method: 

-(void) addObservers {
 _messageObserver = [[NSNotificationCenter defaultCenter] addObserverForName:bNotificationMessageAdded object:Nil queue:Nil usingBlock:^(NSNotification * notification) {
        
        id<PMessage> messageModel = notification.userInfo[bNotificationMessageAddedKeyMessage];
        messageModel.delivered = @YES;
        
        // This makes the phone vibrate when we get a new message
        // Only vibrate if a message is received from a private thread
        if (messageModel.thread.type.intValue & bThreadFilterPrivate) {
            if (![messageModel.userModel isEqual:NM.currentUser]) {
                AudioServicesPlaySystemSound(1007);
                AudioServicesPlayAlertSound(kSystemSoundID_Vibrate);
            }
        }
        
        // Move thread to top
        [self reloadData];
    }];
    
 _messageObserver = [[NSNotificationCenter defaultCenter] addObserverForName:bNotificationMessageRemoved object:Nil queue:Nil usingBlock:^(NSNotification * notification) {
        [self reloadData];
    }];
    _userObserver = [[NSNotificationCenter defaultCenter] addObserverForName:bNotificationUserUpdated object:Nil queue:Nil usingBlock:^(NSNotification * notification) {
        [self reloadData];
    }];
    _internetConnectionObserver = [[NSNotificationCenter defaultCenter] addObserverForName:kReachabilityChangedNotification object:nil queue:Nil usingBlock:^(NSNotification * notification) {
        //[self updateButtonStatusForInternetConnection];
    }];
    
    _typingObserver = [[NSNotificationCenter defaultCenter] addObserverForName:bNotificationTypingStateChanged object:nil queue:Nil usingBlock:^(NSNotification * notification) {
        id<PThread> thread = notification.userInfo[bNotificationTypingStateChangedKeyThread];
        _threadTypingMessages[thread.entityID] = notification.userInfo[bNotificationTypingStateChangedKeyMessage];
        [self reloadData];
    }];
    _threadObserver = [[NSNotificationCenter defaultCenter] addObserverForName:bNotificationThreadDeleted object:Nil queue:Nil usingBlock:^(NSNotification * notification) {
        [self reloadData];
    }];
}

and the problems I am getting is:
(1). I am only able to get notification with sound+vibration is when I entered to my ChatViewController for once. Instead, I am only able to get notification without sound+vibration.

--> so for that I tried to add the above code in AppDelegate.m (didLaunching method) and what I got is only when the app is in foreground than only I am receiving the notification with  sound+vibration.

--> But I also need to get notification with sound+vibration when app is not running (ie. not in foreground and background mode).

**Comment by bensmiley** [comment]
I think that there are two separate issues here:

1. Is it the case that you are managing to the sound and vibration when the app is open? You should only get this if another user sends you the message. You would need to also add this code to a class other than the chat view controller (like the app delegate) because if it's in the chat view controller, it will only be executed when that view controller is actually open. 

2. When the app is closed, you will need to use different logic because push notifications are handled separately. They are handled by the system not the app. This isn't strictly to do with the Chat SDK to give detailed help, I would need to you buy some [priority support time](https://chatsdk.co/downloads/priority-support-block/). However, you could look at something like [this](https://stackoverflow.com/questions/37536591/change-push-notification-sound) and then change the push data that's [sent](https://github.com/chat-sdk/chat-sdk-ios/blob/master/ChatSDKFirebase/FirebasePush/BFirebasePushHandler.m).

```
-(void) pushToUsers: (NSArray *) users withMessage: (id<PMessage>) message {

   //...
   
    NSDictionary * dict = @{@"body": text,
                            @"title": message.userModel.name,
                            @"badge": @1,
                            @"chat_sdk_thread_entity_id": message.thread.entityID,
                            @"chat_sdk_user_entity_id": message.userModel.entityID};
// Add extra keys here

    [self pushToUsers:users withData:dict];
}
```
