### ISSUE TITLE
Facebook login issue

### ISSUE THREAD

**Issue by jupiter0107** [chat-sdk/chat-sdk-ios#175]
Hi , 

Here are a few problems i have encountered using facebook signup method

1) App crashes when canceled is pressed 
To recreate the problem :-  

Press facebook button

![screen shot 2017-12-20 at 5 39 07 pm](https://user-images.githubusercontent.com/34261628/34200630-bd436f82-e5ac-11e7-8222-487e22ee0ed0.png)

Alert view shows up, press cancel and the app crashes , or cancel at any point without completing the facebook login sequence.

This is the error message it throws 

2017-12-20 17:41:31.741730+0800 ChatSDKSwift[25797:19198058] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Either IDToken or accessToken must be supplied.'

2)The second problem arises when the user has completed the log in through facebook, firebaseAuth shows a null value under the identifier column, Here's a screenshot
<img width="634" alt="screen shot 2017-12-20 at 5 51 57 pm" src="https://user-images.githubusercontent.com/34261628/34201177-9fffcce8-e5ae-11e7-8e9b-cad1179824c0.png">

**Comment by bensmiley** [comment]
This will be fixed in 2c6ab521f01fe1f9d3b6b1923bc5893b6cf0b15d.

**Comment by jupiter0107** [comment]
Hello @bensmiley , firebase still does not capture the users email information in this case 

Here's a screenshot under the authentication tab 

<img width="940" alt="screen shot 2018-01-03 at 2 35 48 pm" src="https://user-images.githubusercontent.com/34261628/34511220-dba90bf6-f094-11e7-888b-2998105998ca.png">

**Comment by bensmiley** [comment]
That's correct. If the user authenticates via Facebook, their user information isn't captured. If you feel that this is a problem, you would need to follow up with Firebase support.
