### ISSUE TITLE
Upload image in public chat

### ISSUE THREAD

**Issue by chriseman** [chat-sdk/chat-sdk-ios#176]
Hi,

I just played around with the ChatSDKSwift demo today, and when I tried to send an image in a public chat nothing really happened. To figure out what is going on, I set a break point to line 195 in BChatViewController.m `-(RXPromise *) sendImage: (UIImage *) image` to see if the method is being called, and the answer was no.

Could you help me with this issue?

Thanks,
Chris

**Comment by simonsmileyandrews** [comment]
Hi @chriseman,

Can you confirm if regular messages were working at the time (if not then this might be a problem with authentication to the server). 

Simon

**Comment by chriseman** [comment]
Sending a standard text message works fine.

I finally found the issue **bPictureTypeAlbumImage** was missing in the **execute** method 

<img width="820" alt="screen shot 2017-12-22 at 10 13 26" src="https://user-images.githubusercontent.com/14274762/34299455-473744e4-e723-11e7-8be5-e5261be79e97.png">

**Comment by bensmiley** [comment]
Code updated to fix this issue.
