### ISSUE TITLE
overriding privateThreadsViewController

### ISSUE THREAD

**Issue by chriseman** [chat-sdk/chat-sdk-ios#177]
At the moment I am writing a demo using Xcode 9.2 and SWIFT 4. I replaced the **BAppTabBarController** in **AppDelegate** with my own private chat view controller embedded in a UINavigationController.

All my private conversations appear in the table view, I can open the existing chats, I can send messages I received and sent previously from/to other participant. However after implementing my own private chat view controller, my observers are not triggering any single event. I tried to send a message from another device, but nothing just don't receive a notification on my side.

That's the way I implemented the listener for **bNotificationMessageAdded** in my addObservers() method, maybe there is something I missed out on.

```
self.notificationList.add(NotificationCenter.default.addObserver(forName: Notification.Name(bNotificationMessageAdded), object: nil, queue: nil) { notification in
            print("fired")
            DispatchQueue.main.async {
                let messageModel = notification.userInfo?[bNotificationMessageAddedKeyMessage] as? PMessage
                messageModel?.setDelivered(true)
                
                if let type = messageModel?.thread().type()?.uint32Value {
                    let vibratePhone = type & bThreadFilterPrivate.rawValue
                    if vibratePhone > 0 {
                        if !(messageModel!.userModel().isEqual(NM.currentUser())) {
                            AudioServicesPlayAlertSound(kSystemSoundID_Vibrate)
                        }
                    }
                }
                
                self.reloadData()
            }
        })
```

**Comment by bensmiley** [comment]
I've looked at this and I don't think it's a problem with the Chat SDK. More likely a small bug in your code. For example, can you check:

1. That the notification list isn't `nil`
2. That this code is being called
3. That the observer isn't being removed

I think that one of these is the most likely cause.

**Comment by chriseman** [comment]
I forgot to call the method `self.lifecycleHelper.viewDidAppear().thenOnMain`
