### ISSUE TITLE
Did not getting notification in device

### ISSUE THREAD

**Issue by ChintanWeapp** [chat-sdk/chat-sdk-ios#178]
I have register for remote notification as following:

```
if(SYSTEM_VERSION_GRATERTHAN_OR_EQUALTO(@"10.0")) {
            [UNUserNotificationCenter currentNotificationCenter].delegate = self;
            [[UNUserNotificationCenter currentNotificationCenter] requestAuthorizationWithOptions:(UNAuthorizationOptionSound | UNAuthorizationOptionAlert | UNAuthorizationOptionBadge) completionHandler:^(BOOL granted, NSError * _Nullable error){
                if( !error ){
                   [[UIApplication sharedApplication] registerForRemoteNotifications];
                }
            }];
        }
        else {
            [[UIApplication sharedApplication] registerUserNotificationSettings:[UIUserNotificationSettings settingsForTypes:(UIUserNotificationTypeSound | UIUserNotificationTypeAlert | UIUserNotificationTypeBadge) categories:nil]];
            [[UIApplication sharedApplication] registerForRemoteNotifications];
        }
```

And in device with OS (<= iOS 9.x) I get notification but in device with os (>= ios 10) I didn't getting it. There are two delegate methods for UNUserNotificationCenter framework to get notifications in ios10 or greater. They are as: 

```
- (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler{ }

- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void(^)())completionHandler{}
```

So where I should write following to get notification:

```
 [[BNetworkManager sharedManager].a.push application:application didReceiveRemoteNotification:response.notification.request.content.userInfo];
```

Or If I'm doing anything wrong than please guide me
Thanks

**Comment by softcraftgit** [comment]
did you solve this?

**Comment by ChintanWeapp** [comment]
Yes, it's solved.

**Comment by bensmiley** [comment]
@ChintanWeapp How did you solve the issue?

**Comment by softcraftgit** [comment]
Still I am not getting notification on mobile but chat is updated.

**Comment by bensmiley** [comment]
I've tested this and I am getting notifications. Can you check the following:

1. That you are calling this method in the app delegate:

  ```  
  BFirebasePushModule.init().activateForFirebase(with: application, withOptions: launchOptions)
  ```

2. That you have followed the [setup guide](https://github.com/chat-sdk/chat-sdk-ios#push-notifications). Including [Firebase setup](https://github.com/chat-sdk/chat-sdk-ios/wiki/FIrebase-Push-Notification-Setup).  

3. There are a lot of moving parts involved in push notifications. So I'd recommend going through everything again to double check that you haven't made any mistakes or missed something out.

**Comment by softcraftgit** [comment]
showuld we use "Backendless" to receive notification?

**Comment by bensmiley** [comment]
For the latest version, you should use [Firebase Cloud Messaging](https://firebase.google.com/docs/cloud-messaging/).
