### ISSUE TITLE
Can't find Twitter?

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#180]
OK.
I have pulled, cleaned, repulsed, install, update, clean, etc... and it still can't find Twitter in:

```
//
//  BSocialLoginHandler.m
//  Pods
//
//  Created by Benjamin Smiley-andrews on 01/03/2017.
//
//

#import "BFirebaseSocialLoginHandler.h"

#import <ChatSDK/ChatCore.h>

#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import <FBSDKLoginKit/FBSDKLoginKit.h>

#import <GoogleSignIn/GoogleSignIn.h>
#import <TwitterKit/TwitterKit.h>
```

'TwitterKit/TwitterKit.h' file not found

What obvious upgrade path did I miss with the latest changes from master?

I did all the copying of ChatSDKFirebaseAdapter

Thoughts? I need to get this built to push to apple.

**Comment by bensmiley** [comment]
Did you add this to your `Podfile`:

```
pod 'TwitterKit', '2.3'
pod 'GoogleSignIn'
pod 'FBSDKLoginKit'
```

Run `pod update`?

**Comment by jimijon** [comment]
I had those before... put them back, now I get:

Definition of 'BStickerMessageModule' must be imported from module 'ChatSDKModules.BStickerMessageModule' before it is required

Round and Round hence my payment of an hour of support to get you to build my app. Thanks.
