### ISSUE TITLE
Issue getting with private chat

### ISSUE THREAD

**Issue by Vivekmalani** [chat-sdk/chat-sdk-ios#183]
i will create private threads using NM.core().createThread(withUsers: user, threadCreated: { (error, thread) in })

But after that it will not appear in the list.

i will use syntax for getting list of threads is NM.core().threads(with: bThreadType(bThreadFilterPrivateThread.rawValue))

can someone help me why is getting this type of trouble and how can i resolve it.

**Comment by bensmiley** [comment]
Hi @Vivekmalani 

Are you able to create private threads using the standard threads view controller? i.e. **Conversations -> + -> Compose**. Does this show up?

If so, can you do the following:

1. Post the entirety of your code snippet?
2. Check Firebase (using the dashboard) to see if your thread is being created there
3. Add a break point to see if the `createThread` method is completing successfully. If there is an error, can you post it?

**Comment by Vivekmalani** [comment]
Hi Sir,

Is there any way to send message to multiple threads?

Thanks,
Vivek Malani

**Comment by bensmiley** [comment]
To do that, you would need to loop over the threads and add the message to each one using:

```
[NM.core sendMessageWithText:@"" withThreadEntityID:@""];
```

There are similar methods for sending location or image messages.
