### ISSUE TITLE
Camera Not Working 

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#184]
Camera mode doesn't work.  iOS

It asks for permission. good.
Brings up the camera. good.
allows you to take a snapshot, edit. good
Hit Done... poof all goes away. No trace of photo anywhere. BAD
Didn't crash. GOOD!

**Comment by bensmiley** [comment]
This has been fixed in version [4.3.13](https://github.com/chat-sdk/chat-sdk-ios/releases/tag/4.3.13). Run `pod update`.
