### ISSUE TITLE
how to customise BMessageCells

### ISSUE THREAD

**Issue by chriseman** [chat-sdk/chat-sdk-ios#185]
I just dug into the depth of the SDK to figure out how to change the appearance of the BChat cell, and the only thing I found so far is a lot of work.

Is there an easy way of changing the UI of the chat cells without rewriting the entire BChatViewController, ElmChatViewController stack myself?

Thanks,
Chris

**Comment by bensmiley** [comment]
I added a section to the documentation [here](https://github.com/chat-sdk/docs#customizing-message-cells). If you have other questions you can reopen the issue and I'll try to add more details.
