### ISSUE TITLE
Should we use Backendless to get push notification?

### ISSUE THREAD

**Issue by softcraftgit** [chat-sdk/chat-sdk-ios#186]
Should we use Backendless to get push notification?

**Comment by softcraftgit** [comment]
Getting notification while chatting between iOS apps and getting notification in Android while sending message from iOS. But not getting notification on iOS device while sending message from Android.

**Comment by bensmiley** [comment]
You should now use FCM - see [guide](https://github.com/chat-sdk/chat-sdk-ios#push-notifications). There are some known issues with push notifications that we're trying to resolve.
