### ISSUE TITLE
Changing chat cell background color

### ISSUE THREAD

**Issue by chriseman** [chat-sdk/chat-sdk-ios#188]
Hi,

What is the best solution to change the background color of chat cells?

**Comment by bensmiley** [comment]
I would recommend looking at this [guide](https://github.com/chat-sdk/docs#customizing-message-cells). You could subclass the standard message cells and then set the background color.

**Comment by bensmiley** [comment]
If you just want to change the message color, you can use this:

```
let config = BConfiguration.init();
config.messageColorMe = "FF00AA"
BChatSDK.initialize(config);
```

The color should be a HEX value.
