### ISSUE TITLE
getting issues in integrating FCM messaging services for app level push notifications

### ISSUE THREAD

**Issue by agnitiosoftware** [chat-sdk/chat-sdk-ios#190]
Hello Ben, I'm using chat sdk in my app and now I want to integrate FCM for my app level notifications. Framework for MessagUI are already present in the FirebaseChatSDK, so I didn't installed new pods for it.

When I wrote **Messaging.messaging().delegate = self** in my appdelagate, I got the following error while building the project:

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FIRMessaging", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I found this same issue in #119 
Any help will be appreciated.

Thanks and Regards
Agnitio Software

**Comment by agnitiosoftware** [comment]
Hello,

Please reply on this issue since i need to upload app asap. 
are you guys updating sdk for this implementation ? 

Your quickest reply will be appreciated!!
Thanks in advance!!

**Comment by agnitiosoftware** [comment]
further notes:

**Comment by agnitiosoftware** [comment]
hello team,

can you please reply on this serious issue. 
I am waiting for the response on it. 

Please reply and advice on it.

**Comment by bensmiley** [comment]
Can you provide me with a copy of your `podfile`? Have you followed this [guide](https://firebase.google.com/docs/cloud-messaging/ios/client)? If you have included the messaging pod then you should be able to use the messaging API.

**Comment by agnitiosoftware** [comment]
pod 'Firebase/Core'
pod 'Firebase/Messaging'

**Comment by agnitiosoftware** [comment]
Here's the podfile:

platform :ios, '9.3'

target 'Chimer' do
use_frameworks!

# Pods for Chimer
pod 'FacebookCore'
pod 'FacebookLogin'
#pod 'FacebookShare', :git => 'https://github.com/1amageek/facebook-sdk-swift'
pod 'FBSDKCoreKit'
#pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'TwitterKit'
pod 'GoogleSignIn'
pod 'CircularSpinner'
pod 'AFNetworking', '~> 3.0'
pod 'IQKeyboardManagerSwift', '4.0.13'
pod 'ALCameraViewController', '~> 2.0.3'
#pod 'HELargeCenterTabBarController'
#pod 'AANotifier'
pod 'Socket.IO-Client-Swift', '~> 11.0.2' # Or latest version
pod "Branch"
pod 'SinchVerification-Swift'
pod 'Fabric'
pod 'Crashlytics'
pod 'NearbyMessages'
pod 'TTADataPickerView'
pod "Pulsator"
pod 'Siren'
pod 'MGSwipeTableCell'
#  pod 'ImageScrollView'
pod 'Stripe'
#pod 'Firebase/Messaging'

#pods for firebase chat sdk
pod "ChatSDKCore", :path => "../Chimer/ChatSDK/ChatSDKCore"
pod "ChatSDKUI", :path => "../Chimer/ChatSDK/ChatSDKUI"
pod "ChatSDKCoreData", :path => "../Chimer/ChatSDK/ChatSDKCoreData"
pod "ChatSDKFirebaseAdapter", :path => "../Chimer/ChatSDK/ChatSDKFirebaseAdapter"
pod "ChatSDKFirebaseAdapter/AuthBase", :path => "../Chimer/ChatSDK/ChatSDKFirebaseAdapter"
pod "ChatSDKFirebaseAdapter/Phone", :path => "../Chimer/ChatSDK/ChatSDKFirebaseAdapter"
pod "ChatSDKFirebaseAdapter/Database", :path => "../Chimer/ChatSDK/ChatSDKFirebaseAdapter"
pod "ChatSDKFirebaseAdapter/Storage", :path => "../Chimer/ChatSDK/ChatSDKFirebaseAdapter"
pod "ChatSDKFirebase/VideoMessages", :path => "../Chimer/ChatSDKFirebase"
end

post_install do |installer|
copy_pods_resources_path = "Pods/Target Support Files/Pods-Chimer/Pods-Chimer-resources.sh"
string_to_replace = '--compile "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}"'
assets_compile_with_app_icon_arguments = '--compile "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}" --app-icon "${ASSETCATALOG_COMPILER_APPICON_NAME}" --output-partial-info-plist "${BUILD_DIR}/assetcatalog_generated_info.plist"'
text = File.read(copy_pods_resources_path)
new_contents = text.gsub(string_to_replace, assets_compile_with_app_icon_arguments)
File.open(copy_pods_resources_path, "w") {|file| file.puts new_contents }

end



Please replyASAP
Thanks and Regards
Agnitio Software

**Comment by bensmiley** [comment]
I think you may have used some old or outdated instructions. 

```
pod "ChatSDKCore", :path => "../Chimer/ChatSDK/ChatSDKCore"
pod "ChatSDKUI", :path => "../Chimer/ChatSDK/ChatSDKUI"
pod "ChatSDKCoreData", :path => "../Chimer/ChatSDK/ChatSDKCoreData"
pod "ChatSDKFirebaseAdapter", :path => "../Chimer/ChatSDK/ChatSDKFirebaseAdapter"
pod "ChatSDKFirebaseAdapter/AuthBase", :path => "../Chimer/ChatSDK/ChatSDKFirebaseAdapter"
pod "ChatSDKFirebaseAdapter/Phone", :path => "../Chimer/ChatSDK/ChatSDKFirebaseAdapter"
pod "ChatSDKFirebaseAdapter/Database", :path => "../Chimer/ChatSDK/ChatSDKFirebaseAdapter"
pod "ChatSDKFirebaseAdapter/Storage", :path => "../Chimer/ChatSDK/ChatSDKFirebaseAdapter"
pod "ChatSDKFirebase/VideoMessages", :path => "../Chimer/ChatSDKFirebase"
```

Can you try adding the Chat SDK using the [latest instructions](https://github.com/chat-sdk/chat-sdk-ios#adding-the-chat-sdk-to-your-project). I think you'll find that this solves your issues. If it doesn't, you can reopen the issue.

**Comment by agnitiosoftware** [comment]
I downloaded the new chat sdk and now its working well.

Thanks for the help!! @bensmiley
