### ISSUE TITLE
Error on image message

### ISSUE THREAD

**Issue by victorleungtw** [chat-sdk/chat-sdk-ios#194]
After select image from photo library for messaging, I'm getting an error:

 **[discovery] errors encountered while discovering extensions: Error Domain=PlugInKit Code=13 "query cancelled" UserInfo={NSLocalizedDescription=query cancelled}**

I have checked the app is PHAuthorizationStatusAuthorized. Also info.plist has the Privacy - Photo library Usage Description key-value pair set already. How to solve this error? Thanks

**Comment by bensmiley** [comment]
I'm not able to replicate this issue. Do you get it even if you check out the default version of the Chat SDK?

**Comment by victorleungtw** [comment]
Hi @bensmiley, thanks for your reply. After switching the sample code with pod install latest sdk, the issue can no longer reproduce indeed. This issue should be resolve.
