### ISSUE TITLE
How to extend user

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#197]
I need to add some meta information into a user. I have created my own view controller extending BProfileTableViewController. Changed my adaptor to point to my new controller. Now I need to link up my fields, and then save / retrieve.

Is there documentation on how to extend the User Profile?

**Comment by bensmiley** [comment]
Yes, here is information [here](https://github.com/chat-sdk/docs#user-meta-data) on adding meta data.

**Comment by jimijon** [comment]
I knew it existed!…. but I don’t think you can get to it from the wiki.
I stumbled upon it once and could never find it again.
