### ISSUE TITLE
Not receiving Firebase APNs for new messages when app is closed

### ISSUE THREAD

**Issue by chriseman** [chat-sdk/chat-sdk-ios#199]
Hi there,

Receiving new messages when the app is launched and open works well. However I am not receiving any APNs notifications when new messages arrive whilst the app is closed or the iPhone is locked. Sending APNs notifications from the Firebase console works. 

I followed the instructions in the tutorial.

Thanks,
Chris

**Comment by chriseman** [comment]
I followed this guide https://github.com/chat-sdk/chat-sdk-ios#push-notifications and in the demo I found a section called Backendless. However I haven't figured out how Backendless works together with the SDK, is there any documentation about it?

**Comment by chriseman** [comment]
there was obviously a problem with the push token

**Comment by bensmiley** [comment]
Can you post a link to the Backendless section? We have stopped supporting Backendless so if there is a reference to it, it should be removed. Did you manage to resolve the issue you were having?

**Comment by chriseman** [comment]
Hi @bensmiley,

I didn't know that Backendless was removed?  I found the reference to the Backendless Secret and App ID in the info.plist of the ChatSDK Demo.

<img width="879" alt="screen shot 2018-02-13 at 14 33 58" src="https://user-images.githubusercontent.com/14274762/36152340-fea03b92-10ca-11e8-90f8-7969f957acdb.png">

We have now release the app, and APNs stopped working on our production enviroment which is a bit of a pain because we wanted to launch with this new feature for Valentines Day.

How is the entire APN process working? Maybe you could tell me what we are missing?

Cheers,
Chris

**Comment by chriseman** [comment]
We found the problem, we didn't replace the staging _cloud_messaging_server_key_ in the info.plist with production key.
