### ISSUE TITLE
iOS Objective-C How to remove contact?

### ISSUE THREAD

**Issue by wazowski78** [chat-sdk/chat-sdk-ios#20]
Hello, I have found this method:

`-(RXPromise *) deleteContact: (id<PUser>) user`

I wonder if you can give me any hint to use it, or I have to implement on my own.
Thanks.

**Comment by wazowski78** [comment]
Hi again,
I have made a workaround and solve it with this. At **BContactsViewController.m** I have added the followingg code:

```
- (void)deleteUser:(id<PUser>)user {
    [[BNetworkManager sharedManager].a.contact deleteContact:user];
    [self reloadData];
}

// *** Edited
- (BOOL)tableView:(UITableView *)tableView canEditRowAtIndexPath:(NSIndexPath *)indexPath {
    return YES;
}

- (void)tableView:(UITableView *)tableView commitEditingStyle:(UITableViewCellEditingStyle)editingStyle forRowAtIndexPath:(NSIndexPath *)indexPath {
    if (editingStyle == UITableViewCellEditingStyleDelete) {
        id<PUserConnection> connection = _contacts[indexPath.row];
        [_contacts removeObjectAtIndex:indexPath.row];
        [self deleteUser:connection.user];
    }
}
```

Of course, this is my workaround and it is possible I have missed something, but by the moment, I am not getting any bug.

Thanks.

**Comment by simonsmiley64** [comment]
Hi @wazowski78,

Looking at your code this seems to be correct. I would recommend looking at the addition code and then recreating it with opposite functions. Let us know if you are finding any issues with the add and remove functions and I can help you if you need it.

Simon
