### ISSUE TITLE
Help with blocking module

### ISSUE THREAD

**Issue by reubenlim1994** [chat-sdk/chat-sdk-ios#201]
@bensmiley  i just purchased and implemented the blocking module, how do i go about checking whether the user is blocked in other viewcontrollers? for instance i would like to check at the Chat View controller to see if the current user im chatting with is blocked, and if it is i would want to disable both the send and + button. 

Currently after blocking the user i am unable to receive messages from the user however i am still able to send messages through to the other user, how do i go about implementing a feature disabling two way conversations?

**Comment by bensmiley** [comment]
@reubenlim1994 If you want to found out if a user is blocked you can use his code:

```
NM.blocking().isBlocked("userEntityID")
```

However, this will only work on the user who blocked the other user. If you wanted to find out if you had been blocked, you would need to write some code to query the other user's blocking list. You could use code like this:

```
    FIRDatabaseReference * ref = [[FIRDatabaseReference userRef:@"otherUserEntityID"] child:bBlockedPath];
    [ref observeEventType:FIRDataEventTypeChildAdded withBlock:^(FIRDataSnapshot * snapshot) {
        if(![_blockedUsers containsObject:snapshot.key]) {
            [_blockedUsers addObject:snapshot.key];
        }
    }];
    [ref observeEventType:FIRDataEventTypeChildRemoved withBlock:^(FIRDataSnapshot * snapshot) {
        if([_blockedUsers containsObject:snapshot.key]) {
            [_blockedUsers removeObject:snapshot.key];
        }
    }];
```

You would have to update the security rules to allow another user to query on this path.
