### ISSUE TITLE
How to monitor video messages?

### ISSUE THREAD

**Issue by jasonsherman** [chat-sdk/chat-sdk-ios#202]
Basically I am curious as to how we can monitor our users' video messages for inappropriate content since they are hosted on your server? Where can we view the video messages to moderate content and protect our users?

**Comment by simonsmileyandrews** [comment]
Hi @jasonsherman,

You can access the videos (and images) users send in the Firebase database. When a video message is sent we upload the video to Firebase storage and then store the URL in the message. For a video we also send an image to display. It will look something like this in the database:

```
"b0470f58-f7fd-45b5-86ab-ea421aed1709" : {
            ".priority" : 1511900186889,
            "JSON" : "{\"image-width\":288,\"image-height\":512,\"thumbnail-url\":\"https:\\/\\/firebasestorage.googleapis.com\\/v0\\/b\\/chat-sdk-v4.appspot.com\\/o\\/files%12F7c5n9bhsotrhls6fih3d4mhr5a_image.jpg?alt=media&token=f5e67108-b286-4168-917a-42fde904d87e\",\"text\":\"https:\\/\\/firebasestorage.googleapis.com\\/v0\\/b\\/chat-sdk-v4.appspot.com\\/o\\/files%2Frq48jush2f4e6un7j0onr1krm7_video.mp4?alt=media&token=c43a56e6-32a2-4c05-81fd-7d7095d5c7b9,https:\\/\\/firebasestorage.googleapis.com\\/v0\\/b\\/chat-sdk-v4.appspot.com\\/o\\/files%2F7c5n9bhsotrhls6fih3d4mhr5a_image.jpg?alt=media&token=f5e67108-b286-4168-917a-42fde904d87e,W288&H512\",\"video-url\":\"https:\\/\\/firebasestorage.googleapis.com\\/v0\\/b\\/chat-sdk-v4.appspot.com\\/o\\/files%2Frq48jush2f4e6un7j0onr1krm7_video.mp4?alt=media&token=c43a56e6-32a2-4c05-81fd-7d7095d5c7b9\"}",
            "date" : 1511900186889,
            "payload" : "https://firebasestorage.googleapis.com/v0/b/chat-sdk-v4.appspot.com/o/files%12Frq48jush2f4e6un7j0onr1krm7_video.mp4?alt=media&token=c43a56e6-32a2-4c05-81fd-7d7095d5c7b9,https://firebasestorage.googleapis.com/v0/b/chat-sdk-v4.appspot.com/o/files%2F7c5n9bhsotrhls6fih3d4mhr5a_image.jpg?alt=media&token=f5e67108-b286-4168-917a-42fde904d87e,W288&H512",
            "read" : {
              "59Jt1A9tIZafbLUDVeGoesVyWz92" : {
                "date" : 1511900187157,
                "status" : 2
              }
            },
            "type" : 4,
            "user-firebase-id" : "aJOoZ4VHrTbAUD8KvWGkinw2VIL2"
          },
```

**Note:** I have changed the URLs in this example so they don't connect to the data shown as I got it randomly from one of our test databases. 

As you can see we save the URL in the payload and the JSON areas:

`"payload" : "https://firebasestorage.googleapis.com/v0/b/chat-sdk-v4.appspot.com/o/files%12Frq48jush2f4e6un7j0onr1krm7_video.mp4?alt=media&token=c43a56e6-32a2-4c05-81fd-7d7095d5c7b9,https://firebasestorage.googleapis.com/v0/b/chat-sdk-v4.appspot.com/o/files%2F7c5n9bhsotrhls6fih3d4mhr5a_image.jpg?alt=media&token=f5e67108-b286-4168-917a-42fde904d87e,W288&H512",
`

This opens out to:

// The image URL
https://firebasestorage.googleapis.com/v0/b/chat-sdk-v4.appspot.com/o/files%12Frq48jush2f4e6un7j0onr1krm7_video.mp4?alt=media&token=c43a56e6-32a2-4c05-81fd-7d7095d5c7b9

// The thumbnail URL
https://firebasestorage.googleapis.com/v0/b/chat-sdk-v4.appspot.com/o/files%2F7c5n9bhsotrhls6fih3d4mhr5a_image.jpg?alt=media&token=f5e67108-b286-4168-917a-42fde904d87e

// The width and height (this allows us to format the message cell correctly)
W288&H512"

This means you could just open the database, copy the URL into a browser and it will download the user video (or image). 

**Reality of doing it**
This method is fine when you have only a few users but if you have thousands of users then searching through Firebase is not realistic. User's might send one video message every 100 messages meaning even downloading the database and searching would be a pain. 

I would therefore recommend instead looking into modifying the database to provide you the video URL in a separate place to check. 

There is a good example of code that does a similar job to this in the ChatSDK. The flagging functionality creates a new "flagged" area in the database and adds the flagged message, the messageID and the threadID to allow you to quickly see if the message is inappropriate. You could do something similar to this by adding each video to an area of the database for checking. 

**Use the flagging functionality**
It is also worth noting that the ChatSDK does have the flagging functionality already built in. Lots of users might not realise this - lots of developers who download the chat probably don't as well. Just swipe left on a message and it should enable the flag view - this then adds the message to the flagged area and you can check this. 

I would personally add something letting user's know about the flagging functionality and encouraging them to use it for offensive videos and messages. Then the offensive videos will be added to the flagged areas for checking. 

This will save you a lot of time both checking people's videos and writing more code. All that is required is clearly alerting users to the flagging functionality and encouraging them to use it. 

Hopefully this answers your question, let us know if you have any follow up queries.

Simon

**Comment by jasonsherman** [comment]
Wow thank you for the detailed answers. It sounds like you guys have put a lot of work and effort into this part of the SDK :+1:
