### ISSUE TITLE
Firebase to Firestore?

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#203]
I was wondering if you were going to move the backend to Firestore. Seems more appropriate now, especially for chat. And it is the Direction of Google/Firebase

**Comment by bensmiley** [comment]
This is something we're considering see [Android issue 148 - Add support for Firestore - vote here!](https://github.com/chat-sdk/chat-sdk-android/issues/148). 

But it's more of a semi-long term project. There are some advantages:

- Better querying
- Better scalability
- Easier to write security rules

But also some disadvantages:

- A lot of code would need to be rewritten and re-tested
- Firestore is less flexible
- There is no presence functionality built in. It's necessary to use a hack involving Google Cloud Code and the real-time database - [article here](https://firebase.google.com/docs/firestore/solutions/presence).
- Project is still in beta

Once the current version of the chat is completely stable we'll start looking to also support Firestore.
