### ISSUE TITLE
Customize BTextInputView

### ISSUE THREAD

**Issue by baymaxdev** [chat-sdk/chat-sdk-ios#204]
Hello,

I am going to customize some UI in BTextInputView like "Send" button.
How can I implement customization?

Thank you.

**Comment by bensmiley** [comment]
You can customize it by creating a new interface adapter - follow this [guide](https://github.com/chat-sdk/docs#customizing-the-user-interface). Then subclassing the `BTextInputView` and returning it from your new interface adapter subclass:

```
    override func sendBarView() -> UIView! {
        return MyTextInputView.init(frame: CGRect.zero)
    }
```

**Comment by szoszig** [comment]
Could you achieve this? I can only change the disabled state, and nothing else on send button, the way you mentioned.
