### ISSUE TITLE
BFirebaseCoreHandler threadsWithUsers always returns empty

### ISSUE THREAD

**Issue by mrdavidrees** [chat-sdk/chat-sdk-ios#205]
within this method:
`-(NSArray *) threadsWithUsers: (NSArray *) users type: (bThreadType) type`

In my case I am using 1To1 chats, trying to get a thread that matches two users- the sender and recipient.
Whenever It fetches the users off the thread, the set of users is always empty, I'm assuming it's not downloading this or storing it in CoreData.
This means that this function, amongst others, never returns properly.

Other functions like:
`-(RXPromise *) createThreadWithUsers: (NSArray *) users name: (NSString *) name threadCreated: (void(^)(NSError * error, id<PThread> thread)) threadCreated `

also suffer because this will never be executed:
```
       // Check to see if a thread already exists with these
        // two users
        for (id<PThread> thread in [NM.core threadsWithType:bThreadType1to1 includeDeleted:YES includeEmpty:YES]) {
            if (thread.users.count == 2 && [thread.users containsObject:currentUser] && [thread.users containsObject:otherUser]) {
                jointThread = thread;
                break;
            }
        }
```

This is leading to a new thread being created every time a user goes to message.

Any help would be really appreciated.

**Comment by mrdavidrees** [comment]
I was storing the chatSDK data at

```
chat/dev
chat/test
chat/prod
```

Which was stuffing up the rules.json
changing it to:

```
chat_dev
chat_test
chat_prod
```

Fixed the issues with it not being able to read users.

**Comment by bensmiley** [comment]
That's the easiest solution, otherwise you would have to modify the rules for the extra path.
