### ISSUE TITLE
swift demo can't chat with Android

### ISSUE THREAD

**Issue by acemeow** [chat-sdk/chat-sdk-ios#206]
I am trying out both iOS swift demo and the [pre-built APK](https://www.dropbox.com/s/0yk4hqfz962xyiy/chat-sdk-all-features.apk?dl=0), but they are not able to find and chat with each other.

Is it possible to modify iOS swift demo so it may connect to the same demo server as android?

**Comment by bensmiley** [comment]
I will aim to do this for the next release.
