### ISSUE TITLE
How to remove Location from the options menu in BChatViewController

### ISSUE THREAD

**Issue by chriseman** [chat-sdk/chat-sdk-ios#207]
Hi there,

I was wondering how to remove the **Location** from the options menu in the BChatViewController.

<img width="371" alt="screen shot 2018-02-19 at 15 37 39" src="https://user-images.githubusercontent.com/14274762/36383140-8a187878-158b-11e8-9339-505ddab7a987.png">

Thanks,
Chris

**Comment by bensmiley** [comment]
You can do it with this setting:

```
config.locationMessagesEnabled = NO;
```

Make sure to update to the latest version of the Chat SDK for this to work using `pod update`.
