### ISSUE TITLE
CCMessageWrapper push methods: core data multi-threading violation

### ISSUE THREAD

**Issue by mtrip** [chat-sdk/chat-sdk-ios#208]
In CCMessageWrapper.m

`-(RXPromise *) push {
    
    RXPromise * promise = [RXPromise new];

    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), ^{

        // Add the message to Firebase
        FIRDatabaseReference * ref = [self ref];
        _model.entityID = ref.key;

        [ref setValue:[self serialize] andPriority:[FIRServerValue timestamp] withCompletionBlock:^(NSError * error, FIRDatabaseReference * ref) {
            if (!error) {
                [promise resolveWithResult:self];
            }
            else {
                _model.entityID = Nil;
                [promise rejectWithReason:error];
            }
        }];
        
    });
        
    return promise;
}`

_model should only be accessed from the main thread as its context is of type NSMainQueueConcurrencyType. Removing the dispatch_async block solve the issue.

**Comment by bensmiley** [comment]
Will be fixed in latest release.
