### ISSUE TITLE
Bug in day label

### ISSUE THREAD

**Issue by snipe717** [chat-sdk/chat-sdk-ios#213]
The labels showing the days of the week, in longer threads, are not displaying the correct days.

**Comment by bensmiley** [comment]
Could you provide a screenshot of this behavior or provide steps to reproduce it?

**Comment by snipe717** [comment]
Not sure how I could suggest you reproduce it, but for instance, all messages in the private conversation with my wife this week, are under a 'Mon' label, since monday, but there have been messages sent most days of the week. It seems to be forgetting to add the label break for each new day.

**Comment by bensmiley** [comment]
Can you post a screenshot?

**Comment by snipe717** [comment]
![img_0896](https://user-images.githubusercontent.com/36953608/37534698-70294e0e-293d-11e8-880b-f0061d98b6ad.png)

**Comment by snipe717** [comment]
Where I have indicated, above the line was yesterday (thursday) and below is today (friday) but the last visible marker was monday. Hope this helps.
