### ISSUE TITLE
Two firebase instances

### ISSUE THREAD

**Issue by gneil90** [chat-sdk/chat-sdk-ios#214]
I want to integrate the ChatSDK into the existing application and want to have two Firebase app instances like described here https://firebase.google.com/docs/configure/ Is it available to provide the options not from plist just directly assign them to Chat configuration? What is the way to achieve it?

**Comment by bensmiley** [comment]
This is fixed in the latest release. You can use the `firebaseGoogleServicesPlistName` option when configuring the Chat SDK.
