### ISSUE TITLE
Regards to the audio message module

### ISSUE THREAD

**Issue by jupiter0107** [chat-sdk/chat-sdk-ios#215]
Hi @bensmiley  , in regards to the audio message module i would like to understand how it works more, it is stated that the module replaces the send button, does that means normal chat messages are not able to be sent anymore? or is it simmilar to whatsapp whereby when the user starts typing the microphone button changes to a send button instead?

**Comment by bensmiley** [comment]
@jupiter0107 The app works like WhatsApp. By default the send button is replaced by a microphone icon but if the user types something, it is converted back to the send button so it is still possible to send text messages.
