### ISSUE TITLE
Bug - unread message counter not reset

### ISSUE THREAD

**Issue by yadidl** [chat-sdk/chat-sdk-ios#216]
The unread message counter on the privateThreadsViewController cell not really reset.Its reset just on UI.
**How to reproduce**
So once you get in to chat some chat with unread messages and go back you will see that counter reset but if you close and reopen the app the counter will be there againa.

**Comment by bensmiley** [comment]
Fixed in 4.0.10. To reproduce I received a message, open the thread. Click back and verify that the message is marked as read. Close then kill app. Reopen app. The thread is still marked as read.

**Comment by AJITHAS-842** [comment]
What does this 4.0.10 indicates ?
Is that any version ? and please help me that how these issue is resolved.

**Comment by bensmiley** [comment]
That is the version number.

**Comment by AJITHAS-842** [comment]
I tried to add this version within the pod , but there is error is showing

**Comment by bensmiley** [comment]
The current version 5.1.3 is higher so use that version...
