### ISSUE TITLE
Crash for share location 

### ISSUE THREAD

**Issue by madhusudhanraoch** [chat-sdk/chat-sdk-ios#218]
When i am trying to share loaction through chat then am getiing app crash and found these message from log and my code in objective-c not in swift.

Could not inset legal attribution from corner 4
 Could not inset compass from edges 9
Could not inset scale from edge 9

Please help me how to resolve this issue.
<img width="1276" alt="screen shot 2018-03-16 at 12 23 19 pm" src="https://user-images.githubusercontent.com/4906306/37503712-eb25c372-2914-11e8-9a9e-79757c7b80de.png">

**Comment by bensmiley** [comment]
Closing because same issue as: https://github.com/chat-sdk/chat-sdk-ios/issues/219
