### ISSUE TITLE
Text locations

### ISSUE THREAD

**Issue by Jonnellinen** [chat-sdk/chat-sdk-ios#220]
I have been looking and looking, but where I could locate texts that I can translate the app?

![nayttokuva 2018-3-20 kello 10 50 27](https://user-images.githubusercontent.com/37575295/37644503-bc358a14-2c2c-11e8-9d05-72cf09327ff6.png)
![nayttokuva 2018-3-20 kello 10 50 42](https://user-images.githubusercontent.com/37575295/37644508-c0702094-2c2c-11e8-99b8-7332a0e24e9c.png)

ps. awesome app!

**Comment by bensmiley** [comment]
Text is located in Core/Resources folder
