### ISSUE TITLE
Regarding single , multi and enterprise license 

### ISSUE THREAD

**Issue by reubenlim1994** [chat-sdk/chat-sdk-ios#222]
Hi @bensmiley 

I notice in your website, when we purchase a module there is 3 different types of licenses, may i know whats the differences between them? 

and also do we get the source code given if we would to purchase a single or multi app license?

**Comment by bensmiley** [comment]
@reubenlim1994 The main difference between the licenses is how many apps they support. If you buy a single app license, you can only use the module in one app. However, if you buy a multi-app license you could use the module in up to 5 apps. Another difference is in the amount of support you get - higher licenses come with more support. 

All the modules come with the complete source code so in that sense, it doesn't matter which module you purchase.
