### ISSUE TITLE
Disappearing messages

### ISSUE THREAD

**Issue by snipe717** [chat-sdk/chat-sdk-ios#228]
Most recent messages are lost from the thread when the thread becomes too long, possibly reaches limit for number which can be displayed.

This issue came about following an update to the SDK, it installed as a new app and the problem began when it tried to pull in all the old threads, some of which were quite long and those were where the problems occurred.

Messages reappear gradually as you submit new ones, but didsapear the next time you open the thread.

Deleting the thread and beginning a new one fixed the problem

**Comment by abhishekthanvi8** [comment]
have you fixed this @snipe717

**Comment by bensmiley** [comment]
@snipe717 Can you tell me which version of the SDK you are using and if you have made any modifications to the project? Also, how many messages causes this problem?

**Comment by abhishekthanvi8** [comment]
Hi @bensmiley  I am using it in both 4.9.7 and 4.10 same issue is coming new messages only shows up when I un install and reinstall the app. I think it is saving data in local db and not updating after that ?
Please help

**Comment by bensmiley** [comment]
@abhishekthanvi8 have you made any modifications to the library? Also, what value did you choose for the root path? I remember this issue can happen if you use special characters in the root path.

**Comment by bensmiley** [comment]
If you can send me a link to access your project, I would be happy to have a look myself.

**Comment by abhishekthanvi8** [comment]
NO, I haven't made any modifications in lib also my root path is just "test". Whenever I log in and come to the chat page no messages load after I do pull to refresh this error comes. 

Sure I will send you a link can you give me you email?

**Comment by bensmiley** [comment]
@abhishekthanvi8 did you update the security rules? My email is ben [at] sdk.chat.

**Comment by sguagni** [comment]
Hi guys, I'm having the same issue..
will you please let me know if a solution (or any other problem) is found ?
thanks in advance,
stefano

**Comment by bensmiley** [comment]
@sguagni I can't reproduce this issue myself. Can you provide me with exact steps to reproduce it? If there is any error message could you post that too?

**Comment by sguagni** [comment]
The steps for reproducing are:

uninstall app from devices (say dev1 and dev2) to clean up

- run the app on both devices

- login user1 and user2

- start a tread with user1 and user2

- keep replying to each other and, after a few messages (about 10/15) one of the two devices (i.e. dev1) stops receiving the messages
I can see the messages on dev2 and firebase console but not on the dev1
messages sent from dev1 are received on dev2 but not the opposite..
the only way to recover is uninstall and reinstall the app on dev1


Pasted below the more significant code you may need to make a check, I've probably missed something..
Let me know if you need more details

thank you for helping,
Stefano




Here the pods from Podfile 


		#chat
		pod 'ChatSDK'
		pod 'ChatSDK/FirebaseAdapter'
		pod 'ChatSDK/FirebaseFileStorage'
		pod 'ChatSDK/FirebasePush'
		pod 'ChatSDK/FirebaseSocialLogin'		
		
		# Firebase
		pod 'Firebase/Auth'
		pod 'Firebase/Database'
		pod 'Firebase/Messaging'
		pod 'Firebase/Storage'
		pod 'FirebaseUI/Facebook'
		pod 'Firebase/Core'
		pod 'Firebase/DynamicLinks'

		#Facebook
		pod 'FBSDKLoginKit'
		
	
	
	
and here the initialization code in app delegate

		
		BConfiguration * config = [BConfiguration configuration];
		config.rootPath = @"test";
		config.allowUsersToCreatePublicChats = NO;
		config.googleMapsApiKey = GOOGLEMAP_APIKEY;
		config.firebaseCloudMessagingServerKey = CHAT_SERVERKEY;
		config.clearDataWhenRootPathChanges = YES;
		config.messageColorMe = @"3ACBEE";
		config.messageColorReply = @"E6E5EA";
		config.messageTextColorMe = @"FFFFFF";
		config.messageTextColorReply = @"000000";
		config.messageNameFont = [UIFont fontWithName:FONT_BOLD size:14.];
		config.messageTextFont = [UIFont fontWithName:FONT_MEDIUM size:13.];
		config.messageTimeFont = [UIFont fontWithName:FONT_MEDIUM size:11.];
		config.threadTitleFont = [UIFont fontWithName:FONT_BOLD size:14.];
		config.threadSubtitleFont = [UIFont fontWithName:FONT_MEDIUM size:13.];
		config.threadTimeFont = [UIFont fontWithName:FONT_REGULAR size:11.];		
		config.locationMessagesEnabled = NO;
		config.twitterLoginEnabled = NO;
		config.googleLoginEnabled = NO;
		config.showEmptyChats = NO;
		config.appBadgeEnabled = YES;
		config.shouldOpenChatWhenPushNotificationClicked = YES;
		config.clientPushEnabled = YES;
		config.userChatInfoEnabled = YES;
		config.showUserAvatarsOn1to1Threads = YES;
		config.showLocalNotifications = YES;
		
		//NB:  if empty app will crash even if twitterLoginEnabled=NO
		config.twitterApiKey = @"x";
		config.twitterSecret=@"y";
				
		CustomInterfaceAdapter *cia = [[CustomInterfaceAdapter alloc] init];
		[BChatSDK initialize:config app:application options:launchOptions interfaceAdapter:cia];
		[UNUserNotificationCenter currentNotificationCenter].delegate = self;
		
		
	
here the CustomInterfaceAdapter definition


		@implementation CustomInterfaceAdapter

		-(UIViewController *) privateThreadsViewController {
			if (!_privateThreadsViewController) {
				_privateThreadsViewController = [[PrivateThreadsViewController alloc] init];
			}
			return _privateThreadsViewController;
		}

		-(ChatViewController *) chatViewControllerWithThread: (id<PThread>) thread {
			return [[ChatViewController alloc] initWithThread:thread];
		}

		@end



and here  the PrivateThreadsViewController definition


		@implementation PrivateThreadsViewController


		- (void)viewWillAppear:(BOOL)animated {
			[super viewWillAppear:animated];
			self.navigationItem.leftBarButtonItem = nil;
			self.navigationItem.rightBarButtonItem = nil;    
			object_setClass(self.navigationController.navigationBar, [NavigationBar class]);
			self.navigationController.toolbar.translucent = YES;    
			UIBarButtonItem *hamburgerMenu = [[UIBarButtonItem alloc] initWithImage:[UIImage imageNamed:@"HamburgerMenu"]
																			  style:UIBarButtonItemStylePlain
																			 target:self
																			 action:@selector(openLeftMenu:)];
			[hamburgerMenu setTintColor:[UIColor whiteColor]];
			[self.navigationItem setRightBarButtonItem:hamburgerMenu];    
			[self.navigationItem setHidesBackButton:YES];
		}

		- (void)viewDidLoad {
			[super viewDidLoad];
			NSArray *threads = [BChatSDK.core threadsWithType:bThreadFilterPrivateThread includeDeleted:NO];
			if (threads.count == 0) {
				[[MainAlert sharedInstance] presentAlert:AlertTypeNoChat onViewController:nil then:nil];
			}
		}

		- (void) viewWillLayoutSubviews {
			[super viewWillLayoutSubviews];
		}

		- (UITableViewCell *)tableView:(UITableView *)tableView_ cellForRowAtIndexPath:(NSIndexPath *)indexPath {
			BThreadCell *cell = (BThreadCell*)[super tableView:tableView_ cellForRowAtIndexPath:indexPath];    
			id<PThread> thread = _threads[indexPath.row];
			if([BChatSDK isMe:thread.creator])
				cell.titleLabel.text = thread.otherUser.name == nil || [thread.otherUser.name isEqualToString:@""] ? thread.otherUser.email : thread.otherUser.name;
			else
				cell.titleLabel.text = thread.creator.name == nil || [thread.creator.name isEqualToString:@""] ? thread.creator.email : thread.creator.name;
			return cell;
		}

		- (void) openLeftMenu:(id)sender {
			[self showLeftViewAnimated:self.sideMenuController.leftViewController];
		}

		@end

**Comment by paoloandrea** [comment]
I have the same problem.
When you can we fix it?
