### ISSUE TITLE
User Block/Unblock Issue

### ISSUE THREAD

**Issue by sachinrot** [chat-sdk/chat-sdk-ios#23]
Hello Ben, Simon
Hope you guys are doing good.
I am trying to Block/Unblock user in private 1-on-1 chat thread. 
In BThreadsViewController.m table cell I have added Edit actions for Block Unblock like bellow 
//Block Action
    UITableViewRowAction *blockAction = [UITableViewRowAction rowActionWithStyle:UITableViewRowActionStyleNormal title:@"Block" handler:^(UITableViewRowAction *action, NSIndexPath *indexPath)
                                         {
                                             id<PThread> thread = _threads[indexPath.row];
                                             [[BNetworkManager sharedManager].a.blocking blockUser:thread.otherUser].thenOnMain(^id(id result) {
                                                 NSLog(@"user Blocked Success");
                                                 return Nil;
                                             }, ^id(NSError * error) {
                                                 NSLog(@"user Blocked Error");
                                                 return Nil;
                                             });
                                         }];

Unfortunately this returns Crash of application without any messages except Regular EXCEC_BAD_Exception with no error stack 
The crash is on this line 
 [[BNetworkManager sharedManager].a.blocking blockUser:thread.otherUser].thenOnMain(^id(id result) { }

On the other hand , If i execute this without "thenOnMain" Block then it works without any exception but it seems to have no effect on user states and user is not blocked , like this 
[[BNetworkManager sharedManager].a.blocking blockUser:thread.otherUser];

Can you please help me finding out what i am doing wrong.
Thanks
Sachin

**Comment by sachinrot** [comment]
Also on further digging i found that inside  BFirebaseBlockingHandler these implementations are empty , is this normal?

-(RXPromise *) blockUser: (id<PUser>) user {
    
}

-(RXPromise *) unblockUser: (id<PUser>) user {
    
}

**Comment by bensmiley** [comment]
That's because we haven't implemented the blocking with Firebase yet. The blocking handler is used for the [XMPP project](http://chatsdk.co/downloads/xmpp-chat-sdk-for-ios/). 

There are two options. You could implement blocking yourself. I would recommend storing the list of blocked user IDs in the following path `user/[user id]/blocked/[blocked user id]`. Then you could either just consult this list when a message comes in - and if the user is blocked, the message isn't saved. Or you could add a security rule to prevent the messages being added to the thread. 

If you wanted us to do the work, I'd be happy to give you a quote. You should email [team@chatsdk.co](mailto:team@chatsdk.co).

**Comment by sachinrot** [comment]
Hello Ben,
As a programmer i would be more than happy to contribute to such a nice work that you guys are doing. let me get started and reach out to you in case i need help.
Should i reach out to you on Git or is there any other way you would prefer ?
Thanks 
Sachin

**Comment by bensmiley** [comment]
Hi Sachin,

That would be great. It would be best if you could develop the feature on a new branch and then submit a pull request. We implemented this feature in a past version and it looked like this:

```
-(RXPromise *) blockUser: (id<PUser>) user {
    RXPromise * promise = [RXPromise new];
    
    Firebase * blockedRef = [Firebase userBlockedRef:self.entityID withBlockedID:user.entityID];
    [blockedRef setValue:@{b_UID: user.entityID} withCompletionBlock:^(NSError * error, Firebase * ref) {
        if (!error) {
            [promise resolveWithResult:Nil];
        }
        else {
            [promise rejectWithReason:error];
        }
    }];
    
    return promise;
}

-(RXPromise *) unblockUser: (id<PUser>) user {
    RXPromise * promise = [RXPromise new];
    
    Firebase * blockedRef = [Firebase userBlockedRef:self.entityID withBlockedID:user.entityID];
    [blockedRef removeValueWithCompletionBlock:^(NSError * error, Firebase * ref) {
        if (!error) {
            [promise resolveWithResult:Nil];
        }
        else {
            [promise rejectWithReason:error];
        }
    }];
    
    return promise;
}
```
Then in Firebase+Paths.m
```
#define bBlockedPath @"blocked"

+(Firebase *) userBlockedRef: (NSString *) firebaseID {
    return [[self userRef:firebaseID] child:bBlockedPath];
}

+(Firebase *) userBlockedRef: (NSString *) firebaseID withBlockedID: (NSString *) uid {
    return [[[self userRef:firebaseID] child:bBlockedPath] child:uid];
}
```
When a user is successfully blocked. We make a new user connection with the blocked type. This code is creating a new user if necessary, then 
```
// Block user connection
id<PUser> connection = [[BCoreDataManager sharedManager] fetchOrCreateEntityWithID:<<blocked user id>> withType:bUserEntity];

[user connectUser:connection withType:bUserConnectionTypeBlocked];

// Unblock user connection
id<PUser> connection = [[BCoreDataManager sharedManager] fetchOrCreateEntityWithID:<<blocked user id>> withType:bUserEntity];
[user disconnectUser:connection withType:bUserConnectionTypeBlocked];
```
Then we used a method like this to see if the user is blocked:
```
-(BOOL) isBlocked {
    for (id<PUser> user in [[BNetworkManager sharedManager].adapter.currentUserModel connectionsWithType:bUserConnectionTypeBlocked]) {
        if ([user.entityID isEqualToString:self.entityID]) {
            return YES;
        }
    }
    return NO;
}
```
This is taken from a different version of the code so the method names may have changed a bit. You will just need to look at the relevant class and find the new names. But the logic should all be valid. 

If you need any help or advice just post on this thread.

**Comment by sachinrot** [comment]
Hello Ben, 
Thanks for the directions and code, i am going to pick this up next week as i am occupied in other work this week. I will definitely reach out to you in case i need any help going further.
Thanks
Sachin
