### ISSUE TITLE
Location thumbnail not shown on ChatViewController

### ISSUE THREAD

**Issue by jamesbcho** [chat-sdk/chat-sdk-ios#235]
Hi.

When sending location message, the thumbnail is not shown on ChatViewController.
However it presents map viewController when I touch the space of location thumbnail.

![img_1446](https://user-images.githubusercontent.com/548014/38798762-70b99f36-419d-11e8-8c6b-5c5613bba953.jpg)

**Comment by leoyfj** [comment]
in appdelegate , be sure to set gmsapikey.

```
BConfiguration * config = [BConfiguration configuration];
config.googleMapsApiKey = GMSAPIKEY;
```
and most importantly, enable  googleapis staticmap api via 
[https://console.developers.google.com/apis/api/static_maps_backend?project=_](url)

**Comment by jamesbcho** [comment]
It works! Thank you!! :)
