### ISSUE TITLE
#import <Hakawai/Hakawai-umbrella.h> file not found

### ISSUE THREAD

**Issue by furry-coding** [chat-sdk/chat-sdk-ios#237]
When adding schat-sdk-ios to my Xcode project via Cocoapods I get the error: #import <Hakawai/Hakawai-umbrella.h> file not found.

The Hakawai pod is installed correctly, but it seems like the umbrella header is called: #import <Hakawai/Hakawai-framework-umbrella.h>

![screen shot 2018-04-17 at 15 44 24](https://user-images.githubusercontent.com/12938041/38873542-4c4ecf68-4256-11e8-8a58-2c0559568679.png)

**Comment by muhammadsr** [comment]
Same issue here

**Comment by mansuuu** [comment]
does anyone know how to fix this issue?
