### ISSUE TITLE
Pod install issue

### ISSUE THREAD

**Issue by Ranjith08** [chat-sdk/chat-sdk-ios#24]
Trying to get the ChatSDK working but keep getting error when using `pod install` and i get this `[!] No podspec found for ChatSDKFirebase in ../../ChatSDK/ChatSDKFirebase`
 any help on this please. Tried using the framework beta branch but no luck there aswell.

**Comment by simonsmiley64** [comment]
Hi @Ranjith08,

You need to make sure your pod file is pointing to the podspecs correctly. If you look in the project you can see each of the required podspecs in a folder.

<img width="438" alt="screen shot 2017-04-06 at 11 22 25" src="https://cloud.githubusercontent.com/assets/8721425/24733485/6e010d56-1abb-11e7-94ba-d48090e4c5dd.png">

When you set up your podfile you need to ensure that the address shows exactly where these podspecs are. 

For example: 

../                    means go up one folder
ChatSDK/       means go into the ChatSDK folder

<img width="320" alt="screen shot 2017-04-06 at 11 27 17" src="https://cloud.githubusercontent.com/assets/8721425/24733604/0a87098c-1abc-11e7-8da8-64eca40d70f2.png">

If you look in the image above hopefully this shows you what I mean. We can see the podfile in the Xcode folder. We know from the first image where the podspecs are stored. This means we need to go out of the Xcode folder then into ChatSDK folder and then into the appropriate folder again. Hence:

../ChatSDK/ChatSDKUI 

This is the path to the UIPodspec from the podfile. 

If you have a different area for your podfile in your project you will need to ensure that this links correctly to be able to update from pods.

Let me know if you need further help,

Simon

**Comment by Ranjith08** [comment]
Hi @simonsmiley64 Thanks for the quick response and detailed view, I have the pods installed now and the SDK is working perfectly. Thank you so much and great effort.
