### ISSUE TITLE
I already have Chat in My app, but I haven't figured out how to block users in my app.

### ISSUE THREAD

**Issue by edisonjoao** [chat-sdk/chat-sdk-ios#242]
Would you guys be able to help?
I saw somewhere that you guys use Firebase as the backend, and I already do that, but for the life of me, I can't figure out blocking users.

I'm ready to test my app, but apple is requiring me to do this.

 A method for filtering objectionable content - A mechanism for users to flag objectionable content - A mechanism for users to block abusive users - The developer must act on objectionable content reports within 24 hours by removing the content and ejecting the user who provided the offending content

**Comment by bensmiley** [comment]
You should mention that the app includes message flagging. You can flag a message by swiping on it. Flagged messages can be moderated and deleted by enabling the admin mode - for yourself you should make an admin version of the app by passing in config parameter `   config.enableMessageModerationTab = YES;`. If you want blocking, you would either need to purchase the [blocking module](https://chatsdk.co/user-blocking/). Or implement blocking yourself. You can do that by implementing the `PBlockingHandler`. You would need to implement each of the methods:

```
-(RXPromise *) blockUser: (id<PUser>) user {
    return Nil;
}

-(RXPromise *) unblockUser: (id<PUser>) user {
    return Nil;
}

-(BOOL) isBlocked: (id<PUser>) user {
    return Nil;
}
``` 

And then set your blocking handler:

```
    [BNetworkManager sharedManager].a.blocking = [[YourBlockingHandler alloc] init];
```
