### ISSUE TITLE
Date stamps within the thread appear to be off

### ISSUE THREAD

**Issue by snipe717** [chat-sdk/chat-sdk-ios#243]
This is certainly happening with pulling in old threads from prior versions, but it’s too early to see if this applies to new users and fresh chats, will hopefully know tomorrow. Times are fine, it’s the dates that are off.

**Comment by snipe717** [comment]
Just an update to the above, a fresh chat I began yesterday with the latest version, has date stamped today in the thread correctly, but the upper ‘floating’ date continues to say ‘today’ throughout the thread.

**Comment by bensmiley** [comment]
Would it be possible for you to post a screenshot?
