### ISSUE TITLE
BFirebaseAuthenticationHandler Error

### ISSUE THREAD

**Issue by cesariel** [chat-sdk/chat-sdk-ios#248]
Everything worked perfectly when I called:

`BFirebaseAuthenticationHandler().login(withFirebaseUser: Auth.auth().currentUser)`

But now is giving me the error:

`[FIRUser parseIDToken:error:] unexpectedResponseWithDeserializedResponse`

How can I resolve this issue?

Thanks
CR

**Comment by ChintanWeapp** [comment]
Same issue faced. Any luck on this?

**Comment by bensmiley** [comment]
@cesariel @ChintanWeapp Could you provide a full stack trace of this error?

**Comment by ChintanWeapp** [comment]
Actually I'm doing sign-in with social media and for that I'm doing login with firebase if user is not registered than in error block need to register. The below code snippet is for that:
----------------------

let isUserAlreadyRegisterd = NM.auth().authenticate(with: [bLoginTypeKey: bAccountTypeUsername.rawValue, bLoginEmailKey: strEmailID, bLoginPasswordKey: strEmailID] ).thenOnMain
        
        
        if ((isUserAlreadyRegisterd) != nil) {
            _ = isUserAlreadyRegisterd!({(result: Any?) -> Any? in
                self.updateFirebaseChatUserData(dictParam: dictParam, imageData: imageData)
                return result
            }, {(error: Error?) -> Any? in
                
                
                let isAuthenticated = NM.auth().authenticate(with: [bLoginTypeKey: bAccountTypeRegister.rawValue, bLoginEmailKey: strEmailID, bLoginPasswordKey: strEmailID] ).thenOnMain
                
                if ((isAuthenticated) != nil) {
                    _ = isAuthenticated!({(result: Any?) -> Any? in
                        self.updateFirebaseChatUserData(dictParam: dictParam, imageData: imageData)
                        return result
                    }, {(error: Error?) -> Any? in
                        SVProgressHUD.showError(withStatus: error?.localizedDescription)
                        return error
                    })
                }
                
                return error
            })
        }

**Comment by ChintanWeapp** [comment]
And at that time, I'm getting the error in 
-(RXPromise *) loginWithFirebaseUser: (FIRUser *) firebaseUser accountDetails: (BAccountDetails *) details {} method 
at

 [firebaseUser getIDTokenWithCompletion:^(NSString * token, NSError * error) {
        if (!error) {
            [tokenPromise resolveWithResult:token];
        }
        else {
            [tokenPromise rejectWithReason:error];
        }
    }];

**Comment by cesariel** [comment]
@ChintanWeapp @bensmiley 

I solved the issue first by Updating my Pods and all the Chat SDK Framework (I had the old ChatSDK Core, UI ... etc) now I have only ChatSDK.

After updating the error was still present, but I change it to:

`BIntegrationHelper.authenticate(withToken: Auth.auth().currentUser?.refreshToken)`

And worked perfectly!

**Comment by ChintanWeapp** [comment]
Where I've to write this? If you have any demo than please share, It will be more useful.
Thank you.

**Comment by cesariel** [comment]
@ChintanWeapp Hi!

I just change the line:

`BFirebaseAuthenticationHandler().login(withFirebaseUser: Auth.auth().currentUser)`

for

`BIntegrationHelper.authenticate(withToken: Auth.auth().currentUser?.refreshToken)`

where you want to authenticate. In my case, in my Sign In Controller.

Hope it helps!
