### ISSUE TITLE
Possibility: ChatSDK API + JSQMessagesViewController

### ISSUE THREAD

**Issue by YuryRadchenko** [chat-sdk/chat-sdk-ios#25]
May I use ChatSDK API with JSQMessagesViewController? How do you think?
Project on Swift.

I have runed test project with ChatSDK API.
Project is using BPublicThreadsViewController and BChatViewController2 with my other view controllers now.
I assume I can use JSQMessagesViewController. 
But maybe I don't know something?

**Comment by bensmiley** [comment]
It would be possible to modify the Chat SDK to use the JSQMessageViewController. You would need to replace the `BChatViewController2` file. You would just need to create a class to bridge between the Chat SDK way of doing things to the JSQMessageView way of doing things. i.e. handle different message types correctly, link up send message and receive message functions etc...

**Comment by expertalex** [comment]
@bensmiley i completely agree with @YuryRadchenko about integrating JSQMessagesViewController!

It is a great project! 
Well maintained. 
Well Tested! 
Easy to customize and with more than 10k stars in GitHub.
Why did not use it?

Regards 
Alex
