### ISSUE TITLE
xcode 9.3 chat-sdk -ios  error (BFirebaseAuthenticationHandler.m)

### ISSUE THREAD

**Issue by break200** [chat-sdk/chat-sdk-ios#252]
case bAccountTypeUsername:
        {
            [[FIRAuth auth] signInWithEmail:details.username password:details.password completion:handleResult];
        }
            break;
        case bAccountTypeCustom:
            [[FIRAuth auth] signInWithCustomToken:details.token completion:handleResult];
            break;
        case bAccountTypeRegister:
        {
            [[FIRAuth auth] createUserWithEmail:details.username password:details.password completion:handleResult];
        }
            break;
        case bAccountTypeAnonymous: {
            [[FIRAuth auth] signInAnonymouslyWithCompletion:handleResult];
        }
***************************************************
handleResult  ==> Incompatible block pointer types sending 'void (^__strong)(FIRUser *

**Comment by yadidl** [comment]
https://github.com/chat-sdk/chat-sdk-ios/pull/253
