### ISSUE TITLE
Warnings when Building Project

### ISSUE THREAD

**Issue by cesariel** [chat-sdk/chat-sdk-ios#254]
Hi!

Is there a way to fix this Warnings while building the Project?

<img width="338" alt="screen shot 2018-05-09 at 11 44 34 am" src="https://user-images.githubusercontent.com/13699157/39824982-ae7f2c58-537e-11e8-8e57-26c7a2408d12.png">

Thanks!
CR

**Comment by bensmiley** [comment]
@cesariel The first thing is that warnings will have no impact on the project. Xcode warns about a lot of stuff. For example, unused variables, implicit conversions etc... In most cases you don't need to worry about them. The second thing is that while we can control the warnings associated with the Chat SDK, we cannot remove warnings from third party libraries like AFNetworking or RXPromise. Over the next few releases a lot of warnings will be fixed.
