### ISSUE TITLE
XcodeXMPP not found in Chat SDK zip

### ISSUE THREAD

**Issue by aamir-nazir** [chat-sdk/chat-sdk-ios#256]

**Comment by bensmiley** [comment]
You can find the [XMPP Chat SDK project here](https://chatsdk.co/xmpp-2/).

**Comment by CineXMike** [comment]
Download after purchase doesnt contain that folder.

**Comment by bensmiley** [comment]
@CineXMike could you forward your purchase receipt to team [at] chatsdk [.] co and I'll invite you to the private XMPP for iOS Github Repository.
