### ISSUE TITLE
Can't add Backendless notifications

### ISSUE THREAD

**Issue by YuryRadchenko** [chat-sdk/chat-sdk-ios#26]
Project on Swift.

1. Added the folder Backendless to ChatSDK/ChatSDKModules

2. My podfile:

```
source 'https://github.com/CocoaPods/Specs.git'

target 'chattest' do
  
  pod "ChatSDK", :path => "../"
  pod "ChatSDKModules/Backendless", :path => "../ChatSDKModules"
  
end
```

3. Run pod install
4. Reopen Xcode

But in *-Bridging-Header.h :
```
#import <ChatSDK/ChatCore.h>
#import <ChatSDK/ChatUI.h>
#import <ChatSDK/ChatCoreData.h>
#import <ChatSDK/ChatFirebaseAdapter.h>
#import "BTwitterHelper.h"
#import <ChatSDKModules/BBackendlessPushHandler.h> //<------ 'ChatSDKModules/BBackendlessPushHandler.h' file not found
```

What do I wrong?

**Comment by bensmiley** [comment]
It's possible that this issue is caused by the move to the use_frameworks flag. According to the [latest instructions](https://github.com/chat-sdk/chat-sdk-ios/blob/master/Docs/Modules/Backendless.md), you should add the Backendless module by dragging it into your Xcode project.
