### ISSUE TITLE
layout bMessageTypeCustom

### ISSUE THREAD

**Issue by VVarusha** [chat-sdk/chat-sdk-ios#260]
What is the right way to make correct layout for bMessageTypeCustom?

All the message types have their own layout methods after recognising type of message, what about Custom massage type?

Im trying to make push controller method by clicking on message, its should be ok, if I got my cell leyouted right! But I can't figurate what steps should I do for it, after registering cell for bMessageTypeCustom I got layout empty message in the top-mid, image that is sited in 

- (UIView *)cellContentView {
    return self.containerView;
} 
in customCell class is displayed in left side.. what is right way to setup layout?
![img_0709](https://user-images.githubusercontent.com/27369842/40138237-f66358ce-5954-11e8-9f12-7727cffc73a4.png)

This is 3 messages sended to another user by current, user that should get message can't see any custom messages even empty, but if print tread it have some

**Comment by tranc4mer** [comment]
Please give some notes about layout..

**Comment by tranc4mer** [comment]
please look this issue
