### ISSUE TITLE
Firebase Login

### ISSUE THREAD

**Issue by 7er0** [chat-sdk/chat-sdk-ios#268]
Can I use Chat SDK in combination with a coexisting firebase authentication logic? My whole data model revolves around Firebase, It would be handy to integrate the SDK within my already existing Database, Push Notifications, etc.

**Comment by furry-coding** [comment]
Same here. We're using Firebase Phone Auth. How can I authenticate ChatSDK using the Firebase idToken or FIRUser or something similar related to the regular Firebase registration?

**Comment by bensmiley** [comment]
To do that you just need to call:

```
BChatSDK.auth().authenticateWithCachedToken()
```

Once your Firebase login logic has completed.
