### ISSUE TITLE
Outdated Documentation?

### ISSUE THREAD

**Issue by 7er0** [chat-sdk/chat-sdk-ios#269]
I am trying to set up the SDK as documented, however, already in the beginning:
```
[BChatSDK initialize:config app:application options:launchOptions];

    // Set the root view controller
    [self.window setRootViewController:[BInterfaceManager sharedManager].a.appTabBarViewController];
```

Those lines cause error messages in my xcode: "No known class method.. " "not found on object.." respectively.

**Comment by bensmiley** [comment]
This code is correct. It must be a different issue with your project. If you are still having this issue please reopen the issue.
