### ISSUE TITLE
integration with Microsoft Azure Backend

### ISSUE THREAD

**Issue by ramneekkashyapwhw** [chat-sdk/chat-sdk-ios#271]
I am designing an app for both android and iOS in which I will be requiring a chat service also.
For that I have clear clarification that Android FCM can be integrated with Microsoft Azure.
But I will like to confirm that whether this module of chat-sdk_iOS will be able to integrate with Microsoft Azure or not? I am preferring backend of Microsoft Azure and want to integrate the iOS FCM with that.

Please assist

**Comment by dicarlomagnus** [comment]
FCM and APN can be integrated with most of languages for backend, are you referring to use Azure as a service for send notifications? On AWS there is a service named Mobile Push Notifications‎ for send iOS/ Android notifications you just need the push notification certificate and make some of programming stuff in your backend app. iOS do not use FCM, just Android, iOS use APN from apple. But iOS / Android can use Firebase for most of all task on a chat but you will need an extra module out of Firebase to send notifications to iOS devices, on my app I am using One Signal, this service is very simple and free just 10 lines of code o less on your backend. But if you don't want it you will need build a sender notification module on your backend or use a service like AWS nevertheless you will need some code to make work it.
