### ISSUE TITLE
'NSManagedObject+Status.h' file not found

### ISSUE THREAD

**Issue by muhammadsr** [chat-sdk/chat-sdk-ios#275]
<img width="868" alt="screen shot 2018-07-13 at 2 11 15 pm" src="https://user-images.githubusercontent.com/1937488/42714092-c09d2f42-86a6-11e8-9f41-7bc3fd3a7c8d.png">

In the ChatSDK Demo, I ran `Pod install`. Then, I opened `ChatSDK Demo.xcworkspace`. Then, I built. 

Having this issue now.....Any ideas?

**Comment by bensmiley** [comment]
This has been fixed in the latest version. You can run `pod update` to access it.
