### ISSUE TITLE
How to do change password?

### ISSUE THREAD

**Issue by chintanTBI** [chat-sdk/chat-sdk-ios#277]
I've implemented Chat-SDK in to my project and set login/registration authentication as Email-password. But I'm curious about how to do change password for changing the password for particular user in firebase database. 

Please look into this and help me out!

**Comment by bensmiley** [comment]
@chintanTBI To change the user's password you would use the Firebase call:

```
[[[FIRAuth auth] currentUser] updatePassword:@"New Pass" completion:Nil];
```

Any time when the user is logged in this will work.

**Comment by chintanTBI** [comment]
Thanks for reply. 
I have implemented chat SDK in my existing project which is in swift. So how your solution is useful to me?

**Comment by bensmiley** [comment]
Because the syntax for Swift is almost the same:

```
Auth.auth().currentUser?.updatePassword(to: "Password", completion: Nil)
```
