### ISSUE TITLE
Chat Search:  Search entry hidden yet active. 

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#281]
I am running a test with our UI using iOS's big headers. Somehow the chat search entry area is not showing  itself,  or is too high and user the header:

![img_1164](https://user-images.githubusercontent.com/971445/43720253-9f20e6e4-9955-11e8-8535-9fecc7b3dc38.png)

**Comment by bensmiley** [comment]
We've added big header support in 4.6.10. Also updated the search so it should also work with big headers.
