### ISSUE TITLE
when i run pod install 

### ISSUE THREAD

**Issue by cui30366423** [chat-sdk/chat-sdk-ios#282]
pod install
Analyzing dependencies
Fetching podspec for `ChatSDK` from `../`
[!] Unable to find a specification for `ChatSDKKeepLayout` depended upon by `ChatSDK/UI`

**Comment by frankSol** [comment]
upgrade pod version 1.6.0
trying to 

> sudo gem install cocoapods --pre

and then re-try

**Comment by muh-bilal** [comment]
Try updating your pods by following command and then retry again:
`pod repo update`
