### ISSUE TITLE
Fatal Error When sending Images or Selecting User Avatar 

### ISSUE THREAD

**Issue by expertalex** [chat-sdk/chat-sdk-ios#29]
```
2017-04-14 22:52:00.889 ChatSDK Demo[13311:1128306] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'URL must be in the form of http[s]://firebasestorage.googleapis.com/v0/b/<bucket>/o/<path/to/object>[?token=signed_url_params]'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000103a81b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010700a141 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000103aea625 +[NSException raise:format:] + 197
	3   ChatSDK Demo                        0x0000000101beaf25 +[FIRStoragePath pathFromHTTPURL:] + 475
	4   ChatSDK Demo                        0x0000000101beab89 +[FIRStoragePath pathFromString:] + 137
	5   ChatSDK Demo                        0x0000000101be645f -[FIRStorage referenceForURL:] + 41
	6   ChatSDK Demo                        0x0000000101759a84 -[BFirebaseUploadHandler uploadFile:withName:mimeType:] + 244
	7   ChatSDK Demo                        0x0000000101727960 -[BAbstractUploadHandler uploadImage:thumbnail:] + 176
	8   ChatSDK Demo                        0x000000010172c333 -[BBaseImageMessageHandler sendMessageWithImage:withThreadEntityID:] + 2227
	9   ChatSDK Demo                        0x000000010173de19 -[BChatViewController2 sendImage:] + 345
	10  ChatSDK Demo                        0x00000001017abe3f -[ElmChatViewController sendImageMessage:] + 111
	11  ChatSDK Demo                        0x000000010176a7b2 -[BMediaChatOption cropViewController:didCropToImage:withRect:angle:] + 178
	12  ChatSDK Demo                        0x0000000101a17f02 __40-[TOCropViewController doneButtonTapped]_block_invoke.484 + 146
	13  libdispatch.dylib                   0x000000010927505c _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x0000000109251c6e _dispatch_continuation_pop + 1020
	15  libdispatch.dylib                   0x00000001092669fc _dispatch_source_latch_and_call + 230
	16  libdispatch.dylib                   0x000000010925f4f1 _dispatch_source_invoke + 1167
	17  libdispatch.dylib                   0x000000010925669a _dispatch_main_queue_callback_4CF + 1066
	18  CoreFoundation                      0x0000000103a46909 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	19  CoreFoundation                      0x0000000103a0cae4 __CFRunLoopRun + 2164
	20  CoreFoundation                      0x0000000103a0c016 CFRunLoopRunSpecific + 406
	21  GraphicsServices                    0x000000010a02aa24 GSEventRunModal + 62
	22  UIKit                               0x00000001075bf0d4 UIApplicationMain + 159
	23  ChatSDK Demo                        0x00000001016d647f main + 111
	24  libdyld.dylib                       0x00000001092c165d start + 1
	25  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by bensmiley** [comment]
Do you have the Firebase storage path set correctly?

![screen shot 2017-04-17 at 19 14 15](https://cloud.githubusercontent.com/assets/5514010/25087511/1b4230e6-23a2-11e7-82fb-38cef87a5f7f.png)

**Comment by simonsmiley64** [comment]
Hi @expertalex,

There is a complete tutorial on setting up Firebase [here](https://github.com/chat-sdk/chat-sdk-ios/wiki/Chat-SDK-iOS:-Firebase-Configuration). This includes step by step documentation and a video tutorial.

Let us know if you to continue to have issues,

Simon

**Comment by itgraule** [comment]
I have the same issue! 
the **root_path** and **storage_path** are set correctly in chat_sdk > firebase.

Thanks

**Comment by bensmiley** [comment]
Does this happen in the default version of the Chat SDK when you clone it? Or only when you configure it to use your Firebase account?

**Comment by expertalex** [comment]
When i configure my firebase!

Also i can't take a photo:

2017-04-19 16:36:06.930 ChatSDK Demo[2083:209564] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Source type 1 not available'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000106dc1b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010bbd1141 objc_exception_throw + 48
	2   UIKit                               0x000000010a241ce6 -[UIImagePickerController sourceType] + 0
	3   ChatSDK Demo                        0x0000000104aa9d6f -[BMediaChatOption execute] + 1007
	4   ChatSDK Demo                        0x0000000104a70b90 -[BChatOptionsActionSheet actionSheet:clickedButtonAtIndex:] + 160
	5   UIKit                               0x000000010a5ffbab -[UIActionSheet _prepareToDismissForTappedIndex:] + 134
	6   UIKit                               0x000000010a5ffaeb __37-[UIActionSheet _prepareAlertActions]_block_invoke.101 + 53
	7   UIKit                               0x000000010a1ce404 -[UIAlertController _dismissAnimated:triggeringAction:triggeredByPopoverDimmingView:] + 1080
	8   UIKit                               0x000000010a958eca -[_UIAlertControllerView interfaceAction:invokeActionHandler:completion:] + 337
	9   UIKit                               0x000000010aa2b398 -[UIInterfaceActionGroupView interfaceAction:invokeActionHandler:completion:] + 105
	10  UIKit                               0x000000010a746a23 -[UIInterfaceAction _invokeHandlerWithCompletionBlock:] + 163
	11  UIKit                               0x000000010a512d4f -[UIInterfaceActionSelectionTrackingController _handleActionSelectionGestureRecognizer:] + 784
	12  UIKit                               0x000000010a399c09 -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:] + 57
	13  UIKit                               0x000000010a3a1a07 _UIGestureRecognizerSendTargetActions + 109
	14  UIKit                               0x000000010a39f3bb _UIGestureRecognizerSendActions + 225
	15  UIKit                               0x000000010a39e67e -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 981
	16  UIKit                               0x000000010a38ae02 _UIGestureEnvironmentUpdate + 1219
	17  UIKit                               0x000000010a38a8f3 -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:] + 484
	18  UIKit                               0x000000010a389aba -[UIGestureEnvironment _updateGesturesForEvent:window:] + 274
	19  UIKit                               0x0000000109ed5b9a -[UIWindow sendEvent:] + 4092
	20  UIKit                               0x0000000109e827b0 -[UIApplication sendEvent:] + 352
	21  UIKit                               0x000000010a665adc __dispatchPreprocessedEventFromEventQueue + 2926
	22  UIKit                               0x000000010a65da3a __handleEventQueue + 1122
	23  UIKit                               0x000000010a65ed08 __handleEventQueue + 5936
	24  CoreFoundation                      0x0000000106d67c01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	25  CoreFoundation                      0x0000000106d4d0cf __CFRunLoopDoSources0 + 527
	26  CoreFoundation                      0x0000000106d4c5ff __CFRunLoopRun + 911
	27  CoreFoundation                      0x0000000106d4c016 CFRunLoopRunSpecific + 406
	28  GraphicsServices                    0x000000010d2dfa24 GSEventRunModal + 62
	29  UIKit                               0x0000000109e650d4 UIApplicationMain + 159
	30  ChatSDK Demo                        0x0000000104a1647f main + 111
	31  libdyld.dylib                       0x000000010c56e65d start + 1
	32  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by bensmiley** [comment]
For the Firebase issue, it looks like you have some mistake in your paths. Have you copied the `GoogleServices-Info.plist` file into your project? Can you double check that the Google Services plist has been added correctly and that the paths in the `chat_sdk` section of the `info.plist` match it?

Are you trying to take a photo on the simulator or a real device? This error usually happens when you try to use the camera on the simulator.
