### ISSUE TITLE
Unable to add premium module to Swift Project

### ISSUE THREAD

**Issue by tkocik92** [chat-sdk/chat-sdk-ios#290]
Hello

I am currently using the Free ChatSDK in my Swift 4.2 project. I decided to add the "Block User" feature. I already paid for and received the Blocking Module. According to the ReadMe on this repo, I simply need to add the module to the project and update my pod file to include:

`pod "ChatSDKModules/[ModuleName]", :path => "[Path to ChatSDKModules folder]""`

For me, this translates to:

Pod File:`pod "ChatSDKModules/Blocking", :path => "../ChatSDKFirebase"`
`pod install` result: `[!] No podspec found for 'ChatSDKModules' in '../ChatSDKFirebase'`

I figured the project was renamed since the instructions were written. I modified my pod declaration to say:

Pod file: `pod "ChatSDKFirebase/Blocking", :path => "../ChatSDKFirebase"`
`pod install` result: `[!] Unable to find a specification for 'ChatSDKCore' depended upon by 'ChatSDKFirebase/Blocking'`

I looked in the ChatSDKFirebase folder's .podspec file and modified it from (1) to (2)

1. ```
    s.subspec 'Blocking' do |blo|
        blo.source_files = ['Blocking/Classes/**/*']
        blo.resource_bundles = {
          'ChatBlocking' => ['Blocking/Assets/**/*', 'Blocking/Interface/**/*']
        }

        blo.dependency 'ChatSDKCore'
        blo.dependency 'ChatSDKFirebaseAdapter'
   end

2. ```
    s.subspec 'Blocking' do |blo|
        blo.source_files = ['Blocking/Classes/**/*']
        blo.resource_bundles = {
          'ChatBlocking' => ['Blocking/Assets/**/*', 'Blocking/Interface/**/*']
        }

        blo.dependency 'ChatSDK/Core'
        blo.dependency 'ChatSDK/FirebaseAdapter'
   end

But that only results in: `The 'Pods-[ProjectName]' target has transitive dependencies that include static frameworks: (ChatSDK, FirebaseAuth, FirebaseDatabase, FirebaseCore, FirebaseStorage, and FirebaseMessaging)`

What do I need to do to add this module to my project?

**Comment by bensmiley** [comment]
[ChatSDKModules.podspec.zip](https://github.com/chat-sdk/chat-sdk-ios/files/2406840/ChatSDKModules.podspec.zip)

For this to work, I would recommend having a folder at the same level as your Podfile called `ChatSDKModules`. Make sure it contains the modules podspec (attached) as well as the module source code. Then use the code @jimijon has posted making sure that the path has been updated. If your project looks like this:

```
Project.xcodeproj
Podfile
Project/
ChatSDKModules/
```

Then you would use an import like this:

```
  pod "ChatSDKModules/FirebaseBlocking", :path => "ChatSDKModules"
```
