### ISSUE TITLE
Chat messages no longer being received after manually closing app

### ISSUE THREAD

**Issue by hamachikama88** [chat-sdk/chat-sdk-ios#296]
Hi Chat SDK team, when we manually close our app that utilizes your SDK, messages can no longer be received from other devices. This happens on both public and private chat rooms. Could you please assist? We have updated the Chat SDK to the latest version as of today.

Steps to reproduce:
1. On iPhone 1 and iPhone 2, enter the public chat room or create a private 1:1 chat.
2. Type messages on each iPhone. They will go through just fine.
3. Manually close the app on iPhone 1 (double clicking the home button and swiping away) and relaunch.
4. Type a message in either of the chat rooms from iPhone 1 and iPhone 2 will receive it.
5. On iPhone 2, enter in a message in either chat room. iPhone 1 will not receive any messages anymore. Waiting and going to different views also won't show any messages.

We're seeing the messages in our Firebase database so not sure what's going on.

Thanks a lot in advance for the help.

**Comment by CineXMike** [comment]
Same here but with xmpp
