### ISSUE TITLE
Crash in the last version 4.9.3 + xmpp adpater

### ISSUE THREAD

**Issue by angelopino** [chat-sdk/chat-sdk-ios#301]
Hi,
new release app crash systematically after these logs:
```
<item subscription="both" jid="1919486@localhost"><group></group></item>


<item ask="subscribe" jid="1921460@localhost"></item>

libc++abi.dylib: terminating with uncaught exception of type NSException

```

<img width="1667" alt="screen shot 2018-10-27 at 01 35 14" src="https://user-images.githubusercontent.com/14337673/47596768-f1c80f80-d988-11e8-90bb-e0ccc301f8ba.png">

Could you check please?

**Comment by angelopino** [comment]
Resolved: Remove and install again app.

**Comment by bensmiley** [comment]
I also tested with ejabberd and delete contact is working as expected including the promise callback.
