### ISSUE TITLE
App crashes on sending empty message

### ISSUE THREAD

**Issue by JyotiNS** [chat-sdk/chat-sdk-ios#302]
1. Is the bug present in the demo Chat SDK project? - yes

2. **What modifications have you made to the Chat SDK?**- None

3. **iOS Version? Device or simulator?** iOS 12, on simulator and device both is has issues

4. **Steps taken to reproduce the problem:** - go to any chat room and send an empty message

5. **Expected result:** - It should not crash and should not accept empty message also.

**Comment by bensmiley** [comment]
This has been fixed and it will go live when `4.9.4` is released.
