### ISSUE TITLE
How to open existing chat room for user on login

### ISSUE THREAD

**Issue by JyotiNS** [chat-sdk/chat-sdk-ios#303]
How can I open chat room matching specific String / Group name I have - please reply wether it is possible. provide sample code to open existing thread.

**Comment by bensmiley** [comment]
If you want to open a specific public thread you can use the method:

```
[BChatSDK.publicThread createPublicThreadWithName:@"Name" entityID:@"id" isHidden:NO].thenOnMain(^id(id<PThread> thread) {
        
    return Nil;
}, Nil);
```

You could also check if that thread exists first using:

```
[BChatSDK.db fetchOrCreateEntityWithID:@"id" withType:bThreadEntity];
```

So you can do this:

1. Define some standard public threads and choose some IDs for them like `sports`, `random` etc...
2. Check if that thread exists
3. If it exists, open it in the `BChatViewController`
4. Otherwise create it and join

**Comment by JyotiNS** [comment]
Can I use same chatroom for multiple apps? entity ID which I get from another app is starts with "-" I have tried it with and without "-" but still can't get the existing chat room. I have same Firebase project for both apps.

**Comment by bensmiley** [comment]
I think you would need to post a code snippet for me to give you an answer. There is no reason why you shouldn't be able to access the same thread on multiple devices.

**Comment by lloisp** [comment]
@bensmiley  I am able to get a specific Thread with `[BChatSDK.db fetchOrCreateEntityWithID:@"id" withType:bThreadEntity];`. 

But the `BChatViewController` I lift with that Thread *does not* show new messages as they arrive. Only the ones already on the device.


Should I declare "synchronization with firebase" separately?

**Comment by nooralam6** [comment]
> @bensmiley I am able to get a specific Thread with `[BChatSDK.db fetchOrCreateEntityWithID:@"id" withType:bThreadEntity];`.
> 
> But the `BChatViewController` I lift with that Thread _does not_ show new messages as they arrive. Only the ones already on the device.
> 
> Should I declare "synchronization with firebase" separately?

i am having the same issue, new message does not comes

**Comment by lloisp** [comment]
@nooralam6 I was able to get it to work by authing first.

`[BChatSDK.auth authenticate]`

**Comment by nooralam6** [comment]
> @nooralam6 I was able to get it to work by authing first.
> 
> `[BChatSDK.auth authenticate]`

how can i login with email and password and then check if thread exists, if not then create new thread?, i have already tried the above flow but once public thread is created i am not able to get all threads,

```
override func viewDidLoad() {
        super.viewDidLoad()
        #if targetEnvironment(simulator)
            UserDefaults.standard.set("simulator@genextstudents.com", forKey: "email")
        #else
            UserDefaults.standard.set("device@genextstudents.com", forKey: "email")
        #endif
        UserDefaults.standard.set("test thread", forKey: "threadName")

        if let email = UserDefaults.standard.string(forKey: "email") {
            let emailLogin = BAccountDetails.username(email, password: "1234567")
            let promise = BChatSDK.auth()?.authenticate(emailLogin)?.thenOnMain
            _ = promise!({ (result) -> Any? in
                print(result as Any)
                print(BChatSDK.currentUser() as Any)
                self.goToThread()
                return nil
            }, { (error) -> Any? in
                print(error as Any)
                self.registerUser(email: email)
                return nil
            })
        }
        
    }
    
    func registerUser(email: String) {
        let accountDetails = BAccountDetails.signUp(email, password: "1234567")
        let promise = BChatSDK.auth()?.authenticate(accountDetails!)?.thenOnMain
        _ = promise!({ result in
            print(result as Any)
            print(BChatSDK.currentUser() as Any)
            self.goToThread()
            return result
        }, { error in
            print(error as Any)
            return error
        })
    }
    
    func goToThread() {
  
        let promise = BChatSDK.publicThread()?.createPublicThread(withName: "Noor")?.thenOnMain
        _ = promise!({ (response) -> Any? in
            if let thread = response as? PThread {
                print(thread)
                thread.add(BChatSDK.currentUser())
                BChatSDK.db()?.save()
                self.checkThread()
            }
            return nil
        }, { (errpr) -> Any? in
            print(errpr)
            return nil
        })
    }

    func checkThread() {
        if let threads = BChatSDK.core()?.threads(with: bThreadTypePrivateGroup) as? [PThread] {
            print(threads)//return []
        }
    }
```

**Comment by nooralam6** [comment]
> @nooralam6 I was able to get it to work by authing first.
> 
> `[BChatSDK.auth authenticate]`

i tried authing but still i am not getting previous messages
