### ISSUE TITLE
message list not updating

### ISSUE THREAD

**Issue by sguagni** [chat-sdk/chat-sdk-ios#304]
1. **Is the bug present in the demo Chat SDK project?**
don't know

2. **What modifications have you made to the Chat SDK?**
none

3. **iOS Version? Device or simulator?**
ipad -> ios 10
simulator iphone 8 plus -> ios 11

4. **Steps taken to reproduce the problem:**
fresh install on both devices
login as user A on the simulator
login as user B on the ipad
open a chat from A to B 
write some message from both devices
everything ok (messages are displayed on both devices)
close the app (i.e) on the ipad (user B)
reopen the app on ipad
user B is already logged in (NM.currentUser is not nil)
navigate to chat screen
exchange some message from user A and B
user B does not receives any message on screen
on the firebase DB I can see all the new messages in the thread

5. **Expected result:**
new messages should be displayed on the chat screen for user B

6. **Actual result:**
only the old messages are loaded on the screen

7. **Comments:**
I double checked the startup code against the samples and I've not seen anything missing ..
maybe I lost some action to do after app restarts ?
NB: i can see the notification on the ipad, but the messages are not listed on the thread..
The same behaviour swapping the procedure between the 2 devices..

thank you,
Stefano

**Comment by abhishekthanvi8** [comment]
did it resolved for you?

**Comment by sguagni** [comment]
nobody answered...
still having the same problem
sorry

**Comment by bensmiley** [comment]
Closing and following up here: https://github.com/chat-sdk/chat-sdk-ios/issues/228
