### ISSUE TITLE
Profile photo not scaled property in the Chat View

### ISSUE THREAD

**Issue by muhammadsr** [chat-sdk/chat-sdk-ios#306]
1. **Is the bug present in the demo Chat SDK project?**
Yes.
2. **What modifications have you made to the Chat SDK?**
Nothing

3. **iOS Version? Device or simulator?**
Both

4. **Steps taken to reproduce the problem:**
Launch a chat view with few messages to see the profile photos for users

5. **Expected result:**
Check screenshot
<img width="297" alt="screen shot 2018-11-07 at 5 04 17 pm" src="https://user-images.githubusercontent.com/1937488/48171242-ebeafc00-e2af-11e8-9248-32d9ec029827.png">

6. **Actual result:**
Check screenshot
<img width="296" alt="screen shot 2018-11-07 at 5 06 56 pm" src="https://user-images.githubusercontent.com/1937488/48171233-e42b5780-e2af-11e8-97dd-46d6b2cde876.png">

7. **Comments:**
I am making a PR for this fix.

**Comment by muhammadsr** [comment]
Created a PR https://github.com/chat-sdk/chat-sdk-ios/pull/307

**Comment by bensmiley** [comment]
The pull request has been merged and this fix will be available in the next version of the project `4.9.5`.
