### ISSUE TITLE
Problem with Push Notifications permission dialog

### ISSUE THREAD

**Issue by developer2311** [chat-sdk/chat-sdk-ios#309]
1. **Is the bug present in the demo Chat SDK project?**
True

2. **What modifications have you made to the Chat SDK?**
There are the list of modified files:

- modified: BChatSDK.m;

- modified: BConfiguration.h;

- modified: BConfiguration.m.

I added one Bool property, which help me to resolve my problem.
(I need that Chat SDK doesn't ask permission for push notifications, for the first launch. I want to show permission dialog later).

3. **iOS Version? Device or simulator?**
iOS 12.1, device (iPhone 5s)

4. **Steps taken to reproduce the problem:**
Install application and launch it. (Only for the first launch)

5. **Expected result:**
Chat SDK doesn't ask permission for push notifications, for the first launch. 

6. **Actual result:**
Chat SDK asks permission for push notifications, for the first launch. 

7. **Comments:**
I like to use your SDK, but I need to resolve this problem. It's very important for me. 
I will do pull request with my changes and my changes will not affect to other users, if you'll approve it.

**Comment by bensmiley** [comment]
Hi @developer2311 if you could submit the pull request, then we will be happy to review and merge it.

**Comment by developer2311** [comment]
@bensmiley Hi! Thank you! It will be great! I'll submit the pull request about through 1-2 hours.

**Comment by developer2311** [comment]
Thank @bensmiley for the quick help. I resolved my problem and made pull request, and @bensmiley approved and merged it.
