### ISSUE TITLE
Problem after updating ChatSDK version.

### ISSUE THREAD

**Issue by developer2311** [chat-sdk/chat-sdk-ios#311]
1. **Is the bug present in the demo Chat SDK project?**
It is not bug

2. **What modifications have you made to the Chat SDK?**
Update Chat SDK version.

3. **iOS Version? Device or simulator?**
iOS 12.1, iPhone5s

4. **Steps taken to reproduce the problem:**
Update ChatSDK version

5. **Expected result:**
Project is building

6. **Actual result:**
Project is not building

7. **Comments:**
I did update Chat SDK pod and I can't call some classes from SDK. 
And I can't create the user model.
In the past installed version I could create user model, using below code:

`guard let user = CCUserWrapper.user(withEntityID: userID).model() as? PUser else {return}`

I've just read the guide, but could not found this.
How I can create user model by entity id at the moment?

**Comment by developer2311** [comment]
I did extend from protocol PUserWrapper at my class and then made next:

`let userWrapper = PUserWrapper.model(self)
        guard let user = userWrapper() as? PUser else {return}
        user.setEntityID(userID)`

It's a right way?

**Comment by developer2311** [comment]
@bensmiley could you help me?

**Comment by khurramtnc** [comment]
Have same issue can't get user object  by using CCUserWrapper.user it shows me Error "Use of undeclared type 'CCUserWrapper'". Can you please help me out?
Thanks
