### ISSUE TITLE
add chat without tabbar controller. 

### ISSUE THREAD

**Issue by stevenzielke** [chat-sdk/chat-sdk-ios#313]
Hi.
I am trying to add the chat to an existing app. It works fine when I add BAppTabBarController to the rootviewController like this:
[self.window setRootViewController:BChatSDK.ui.appTabBarViewController]; 

But when I add the privateThreadsViewController like this without the tabbar:

[self.window setRootViewController:BChatSDK.ui.privateThreadsViewController]; 

it shows the Viewcontroller but I cannot click on the chats.

I think it has to do with the missing tabbar. Is it possible to simply open the Views? I dont want a tabbar navigation since my app does not have it.

Thanks, Steven

**Comment by abhishekthanvi8** [comment]
have you done this @stevenzielke

**Comment by bensmiley** [comment]
@abhishekthanvi8 this is quite an old issue. There isn't any reason why you shouldn't be able to add individual views to the app. Could you try and see if this issue persists?
