### ISSUE TITLE
App crashes when attempt calculate unread messages.

### ISSUE THREAD

**Issue by developer2311** [chat-sdk/chat-sdk-ios#314]
1. **Is the bug present in the demo Chat SDK project?**
The bug is not present in the demo project.

2. **What modifications have you made to the Chat SDK?**
I've created custom method to calculate unread messages count.

3. **iOS Version? Device or simulator?**
iOS 10.3.2, iPhone 5c. 

4. **Steps taken to reproduce the problem:**

I'm getting all private threads and in for-in loop I'm getting thread.allMessages for each thread.
Problem was founded in **two cases**: 

**- attempt to get all private threads;**

**- attempt to get all messages for some thread.**

App crashes in both conditions.

5. **Expected result:**
Methods are working correct.

6. **Actual result:**
App crashes in this methods.

7. **Comments:**
I run it at background queue. Maybe problem with multithreading ?

Additional info attached below.

![1](https://user-images.githubusercontent.com/24232961/49282930-08d2b380-f499-11e8-830c-0d9399f2c32c.png)
<img width="759" alt="2018-11-30 11 47 20" src="https://user-images.githubusercontent.com/24232961/49282932-08d2b380-f499-11e8-8951-786448c9f2a0.png">
![screen shot 2018-11-30 at 11 41 10 am](https://user-images.githubusercontent.com/24232961/49282933-08d2b380-f499-11e8-896e-cd7da21652e1.png)

**Comment by bensmiley** [comment]
I think the problem could be that you are accessing the data on a background thread. You should only access Core Data on the main thread.
