### ISSUE TITLE
Push notifications issue. (from iOS to Android message)

### ISSUE THREAD

**Issue by developer2311** [chat-sdk/chat-sdk-ios#320]
1. **Is the bug present in the demo Chat SDK project?**
---
2. **What modifications have you made to the Chat SDK?**
---
3. **iOS Version? Device or simulator?**
12.2, iPhone 5s
4. **Steps taken to reproduce the problem:**
send text message from one to another device
5. **Expected result:**
Device should receive push notification. 
6. **Actual result:**
Device doesn't receive push notification.
7. **Comments:**

Maybe, you have any idea about this? Maybe removing property "firebaseCloudMessagingServerKey" of BConfiguration it's a reason?

**Comment by developer2311** [comment]
Maybe removing property "firebaseCloudMessagingServerKey" of BConfiguration it's a reason?

**Comment by developer2311** [comment]
After running "[FIRFunctions functions] HTTPSCallableWithName:@"pushToChannels"] ..." code , I receive the error with domain "NSCocoaErrorDomain" and code: 3840.

**Comment by developer2311** [comment]
How to use your index.js file, which works with Firebase Functions (sends push notifications) ?

**Comment by developer2311** [comment]
@bensmiley

**Comment by developer2311** [comment]
Yes, sure. Push notifications did work fine till the update to 4.9.5/4.9.7 version of ChatSDK. 
I think that your new approach (with Firebase Cloud Functions) is a reason of non-working push module in my app. 
Must I implement additional functional on firebase? Help me to resolve it, please.

**Comment by developer2311** [comment]
"[[[FIRFunctions functions] HTTPSCallableWithName:@"pushToChannels"] callWithObject ..." in this block of code, I have not any errors, and in this condition your next code is "NSLog(@"Success")". I understand it as "It's OK. Push notification's already sent". But notification have not received yet again.

**Comment by bensmiley** [comment]
The APNs certificate should be sufficient. Could you check the error logs? Go to the Firebase dashboard then click the "Functions" button and look at health, logs and usage to see if there are any error messages.

**Comment by developer2311** [comment]
@bensmiley Error: data must only contain string values

**Comment by developer2311** [comment]
Error: Firebase Cloud Messaging API has not been used in project 1047155545751 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/fcm.googleapis.com/ ...

**Comment by developer2311** [comment]
I'm sorry. I've just checked this link, and this API really was disabled. (I didn't know that). I'm new at Firebase Cloud Functions ) thank you for hint about error logs.

**Comment by developer2311** [comment]
@bensmiley I've already enabled FCM API for my project, and I have next result: 

<img width="1102" alt="screenshot 2019-01-03 at 12 31 23" src="https://user-images.githubusercontent.com/24232961/50633295-7e77e680-0f53-11e9-98bd-5c407abe36d5.png">

**Comment by developer2311** [comment]
Have you any ideas about this error?

**Comment by developer2311** [comment]
When you did test your code (about new Push Notifications approach), have you ever had the same error?

**Comment by developer2311** [comment]
@bensmiley ???
I'm waiting for your answer, Ben.

**Comment by richardleggett** [comment]
@bensmiley The push notification JS script looks for `messageValue["payload"]` however it looks like the latest iOS SDK does not add this into the Messages created in Firestore? You get a null pointer exception in Firebase Cloud Functions. This is not a problem on the Android SDK after updating to the latest. After upgrading iOS we started seeing this NPE.

Related, is there any migration strategy for iOS? Updating the SDK crashes existing installations that read existing messages from Firestore.

**Comment by Bino90** [comment]
@bensmiley same problem as @developer2311 any ideas?

**Comment by developer2311** [comment]
@Bino90 yes, I have a good idea! you should Fork this repo and fix it yourself.

**Comment by developer2311** [comment]
@Bino90 about push notifications, you should to change index.js file's code, and BFirebasePushHandler.m.

**Comment by Bino90** [comment]
Yes, I've done now anyway, but it has been enough for me to swap [„payload“] to [json_v2][text] in the index.js file. What did you do in BFirebasePushHandler.m?

**Comment by developer2311** [comment]
@Bino90 I did pass fcm token and put it instead of "topic".

"token": <userTokenHERE>, and I did change format of message to universal format for iOS and Android.

**Comment by failynsedik** [comment]
Hi @developer2311 @Bino90. Do you know how to debug errors on firebase functions? I am getting the following error, but I have no idea on what went wrong.

`    {
            code: 'messaging/invalid-payload',
            message: 'data must be a non-null object'
      },
codePrefix: 'messaging'
}`

**Comment by failynsedik** [comment]
Hi. So, I just redeployed firebase functions and it fortunately worked. 😁
