### ISSUE TITLE
Hiding email id 

### ISSUE THREAD

**Issue by sanjaytalreja** [chat-sdk/chat-sdk-ios#323]
Email id should not be kept public  as per user privacy.however we need to make Email/password sign in method available to user.Any solution for making emails of other user unaccessible?

**Comment by lum3ll** [comment]
For now I've solved this using first part of user email as user id (but I can achieve this because I use always the same mail domain, ex. mmm.com). So in login I have:

try (adding @mmm.com)
password

**Comment by bensmiley** [comment]
You can remove the user's email using the following code:

```
[BChatSDK.hook addHook:[BHook hook:^(NSDictionary * dict) {
    id<PUser> user = dict[bHook_PUser];
    if (user) {
        [user setMetaValue:"" forKey:bUserEmailKey];
    }
    [BChatSDK.core pushUser];
}] withName:bHookDidAuthenticate];
```

This intercepts the user after login and sets their email address to blank then pushes this change to the server.
