### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by bensmiley** [chat-sdk/chat-sdk-ios#325]
1. **Is the bug present in the demo Chat SDK project?**

Yes. 

2. **What modifications have you made to the Chat SDK?**

None. 

3. **iOS Version? Device or simulator?**

N/A

4. **Steps taken to reproduce the problem:**

Run `pod install` with the latest version of Cocoapods (1.6.0). 

5. **Expected result:**

The project should compile.

6. **Actual result:**

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_NSManagedObjectContext", referenced from:
      l_OBJC_$_CATEGORY_NSManagedObjectContext_$_RXPromise in RXPromise.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

7. **Comments:**

**Comment by bensmiley** [comment]
I managed to fix this by downgrading to Cocoapods 1.5.3.

**Comment by jimijon** [comment]
I fix this manually each time I upgrade. I add the CoreData framework to the target of RXPromise in Pods.

**Comment by dweep119** [comment]
I am having same issue and I also downgrade Cocoapods version but still I get error.

**Comment by jimijon** [comment]
well, with the latest cocoa pods I  don't see this issue. Read the error closely to figure out the missing library  and then add it into that libraries pod target build

**Comment by bensmiley** [comment]
@dweep119 which version of Cocoapods are you using? And what is the exact error you get?

**Comment by dweep119** [comment]
@bensmiley version of Cocoapods is 1.6.0 and here is the exact error is,


> Ld /Users/apple/Library/Developer/Xcode/DerivedData/ChatSDKSwift-avfljmsgtfwiyqcwieqzwqujavbt/Build/Products/Debug-iphonesimulator/RXPromise/RXPromise.framework/RXPromise normal x86_64 (in target: RXPromise)
   cd /Users/apple/Desktop/App\ Development/chat-sdk-ios/XcodeSwift/Pods
   export IPHONEOS_DEPLOYMENT_TARGET=8.0
   /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk -L/Users/apple/Library/Developer/Xcode/DerivedData/ChatSDKSwift-avfljmsgtfwiyqcwieqzwqujavbt/Build/Products/Debug-iphonesimulator/RXPromise -F/Users/apple/Library/Developer/Xcode/DerivedData/ChatSDKSwift-avfljmsgtfwiyqcwieqzwqujavbt/Build/Products/Debug-iphonesimulator/RXPromise -filelist /Users/apple/Library/Developer/Xcode/DerivedData/ChatSDKSwift-avfljmsgtfwiyqcwieqzwqujavbt/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RXPromise.build/Objects-normal/x86_64/RXPromise.LinkFileList -install_name @rpath/RXPromise.framework/RXPromise -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -mios-simulator-version-min=8.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/apple/Library/Developer/Xcode/DerivedData/ChatSDKSwift-avfljmsgtfwiyqcwieqzwqujavbt/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RXPromise.build/Objects-normal/x86_64/RXPromise_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -ObjC -lc++ -framework Foundation -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/apple/Library/Developer/Xcode/DerivedData/ChatSDKSwift-avfljmsgtfwiyqcwieqzwqujavbt/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RXPromise.build/Objects-normal/x86_64/RXPromise_dependency_info.dat -o /Users/apple/Library/Developer/Xcode/DerivedData/ChatSDKSwift-avfljmsgtfwiyqcwieqzwqujavbt/Build/Products/Debug-iphonesimulator/RXPromise/RXPromise.framework/RXPromise

> Undefined symbols for architecture x86_64:
 "_OBJC_CLASS_$_NSManagedObjectContext", referenced from:
     l_OBJC_$_CATEGORY_NSManagedObjectContext_$_RXPromise in RXPromise.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by bensmiley** [comment]
I think you either need to downgrade to 1.5.3 or upgrade to 1.7.0-beta. Either of these versions works but 1.6.0 doesn't work.
