### ISSUE TITLE
crash on below ios 11 devices

### ISSUE THREAD

**Issue by MajidBashir** [chat-sdk/chat-sdk-ios#327]
1. **Is the bug present in the demo Chat SDK project?**
    Yes
2. **What modifications have you made to the Chat SDK?**
     No Modifications made so far
3. **iOS Version? Device or simulator?**
     Testing on real device
4. **Steps taken to reproduce the problem:**
      Simply run on below iOS 11 devices
5. **Expected result:**
      Application should continue
6. **Actual result:**
     Application is crashing
7. **Comments:**
    I have added the ios 11 check which is for `prefersLargeTitles`, but property seems not working as it should work.

**Comment by bensmiley** [comment]
Can you post a stack trace?
