### ISSUE TITLE
duplicate files when Pod install / update

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#328]
When running:

    pod 'ChatSDK'
    pod 'ChatSDK/UI'
    pod 'ChatSDKFirebase/Adapter'
    pod 'ChatSDKFirebase/FileStorage'
    pod 'ChatSDKFirebase/Push'
    pod 'ChatSDKFirebase/SocialLogin'

This creates two FirebaseNetworkAdaptor directories. One under ChatSDK/ChatSDKFirebase and the other under ChatSDKFirebase/

**Comment by bensmiley** [comment]
I think this has to be a caching issue because if you look at the ChatSDK.podspec file. The `ChatSDKFirebaseAdapter` has been commented out. Can you try the standard steps to update Cocoapods:

1. `pod deintegrate`
2. Delete the following: *.xcworkspace, Podfile.lock, Pods directory, Build directory
3. `pod update`

**Comment by jimijon** [comment]
Tried all that about six different times I still get the two directories. I see what you are saying about commenting out.

./ChatSDKModules/ChatSDKModules.podspec :
    nu.dependency 'ChatSDK/FirebaseAdapter'

./ChatSDKModules/FirebaseBlocking-4/ChatSDKModules.podspec :
    nu.dependency 'ChatSDKFirebase/Adapter'

I think this is where the problem is happening

**Comment by bensmiley** [comment]
Ok, I see. I think maybe you need to update the ChatSDKModules.podspec. 
[ChatSDKModules.podspec.zip](https://github.com/chat-sdk/chat-sdk-ios/files/2858708/ChatSDKModules.podspec.zip)
Could you try that and let me know if it works?

**Comment by jimijon** [comment]
new error:  ld: framework not found ChatSDKModules

**Comment by bensmiley** [comment]
Could you post a screenshot of where that error is happening? Also, which version of Cocoapods are you using?

**Comment by jimijon** [comment]
<img width="1150" alt="screen shot 2019-02-13 at 8 51 45 am" src="https://user-images.githubusercontent.com/971445/52720098-a0aa4e80-2f6c-11e9-8137-cd2d2778fca7.png">

**Comment by jimijon** [comment]
1.6.0

**Comment by bensmiley** [comment]
Ok, you need to downgrade to 1.5.3 see this issue. https://github.com/CocoaPods/CocoaPods/issues/8502#event-2135701241

**Comment by jimijon** [comment]
went to 1.5.3 same issue

**Comment by jimijon** [comment]
any other thoughts?

**Comment by jimijon** [comment]
as a sanity check, have you upgraded your modules from a totally clean pre pod environment?
It still feels like CocoaPods to me. Would like the sanity check.

**Comment by bensmiley** [comment]
@jimijon This is definitely an issue with your Cocoapods setup. If you can give me access to the project I can fix it for you. That may be the quickest way.

**Comment by jimijon** [comment]
https://github.com/jimijon/INDX420

you  are still a collaborator on the project.
Make sure you use the Development branch

thanks
James

**Comment by bensmiley** [comment]
I fixed the issue with the pod setup but then there is a separated unrelated issue to do with KingFisher. I've pushed my fixes to `bens_fixes`. If you have more issues with the modules let me know.

**Comment by jimijon** [comment]
Whatever you did along with some minor tweaks by me worked and with cocoa pods 1.6  I just manually add the CoreData framework to RXPromise “link binary with Libraries” and it is all good!

What exactly was wrong with my pods? Curious.

James

PS: Thanks again. Hope to have this upgrade for early next week.

**Comment by bensmiley** [comment]
Actually not much was wrong. I just made sure the podspec was up to date and made sure the module folders were in the same folder as the module podspec. I’m glad you got it all working 👌🏼
