### ISSUE TITLE
Is there a way to register custom module classes?

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#329]
Since they are development pods I can edit the files directly, though, it would be preferable to be able to register my sub class of BNearbyContactsViewController.   Currently it changes the nav color to black. Though I don't even think you need that to be set there.

**Comment by bensmiley** [comment]
Yes, if you look at the nearby module setup code you can see what needs to be done:

```
-(void) activate {
    [BNetworkManager sharedManager].a.nearbyUsers = [[BGeoFireManager alloc] init];
    [BChatSDK.ui addTabBarViewController: [[BNearbyContactsViewController alloc] init] atIndex: 2];
}
```

Since you want to register your own subclass, you would need to deregister the default class:

```
[BChatSDK.ui removeTabBarViewControllerAtIndex:2];
[BChatSDK.ui addTabBarViewController:[Your Subclass] atIndex:2];
```
