### ISSUE TITLE
Cannot build titre sample example of Swift

### ISSUE THREAD

**Issue by akanksharma** [chat-sdk/chat-sdk-ios#334]
I am getting following errors : 
Error 1 : Could not build Objective-C module 'ChatSDK'
Error 2 :   'RXPromise/RXPromise.h' file not found

**Comment by jimijon** [comment]
Update cocoa pods to 1.7.1

**Comment by akanksharma** [comment]
I updated to 1.6.1  which is the latest available I think. Anyway, the issue is resolved.
Thanks a lot.
