### ISSUE TITLE
I receive a message notification but I don't see it in the thread

### ISSUE THREAD

**Issue by muhammadsr** [chat-sdk/chat-sdk-ios#335]
I am not sure if anyone has experienced this issue before but I have seen it a couple of times. When receiving a notification for a new message, I open the app to see the message in the thread but it is not there. I try to reload the threads by killing and opening the app but it's not there. Any ideas?

**Comment by bensmiley** [comment]
Is this happening for the Firebase or the XMPP backend?

**Comment by muhammadsr** [comment]
Firebase @bensmiley

**Comment by muhammadsr** [comment]
I am still investigating the issue. I am still not sure if the message is present in the Firebase Database as I do not have easy access to the `ThreadId`. 

However, I do believe that the message has not been stored in the Database which is weirder. How can I receive a notification for a message that might not be stored in the Firebase Database? Is this possible?

**Comment by bensmiley** [comment]
Hi @muhammadsr,

It would be helpful if you could give me some details about your setup. Firstly, have you made any modifications to the core library? If so, could you summarise them and give me an idea of how your  app is using the Chat SDK. 

Which version of the Chat SDK are you using?

For push notifications, are you using client push or have you uploaded the Firebase Cloud Functions script to handle push notifications? 

There are several ways to find the thread ID depending on your setup. If you are working on a test database that doesn't have many users, you could open the Firebase Console and inspect the user data. When you find your user, you could see the list of threads associated with it. 

Another way would be to add a break point in Xcode when you open the conversation. i.e. in the `BChatViewController` `initWithThread` method. Then inspect the thread object using the Xcode console and `pod thread`. Then you can see the ID. 

In the current version it is possible for a push notification to be sent before the message is added to Firebase (I've fixed that now) but only if client push is being used. If the FCF script is being used that it wouldn't be possible.

**Comment by muhammadsr** [comment]
@bensmiley 
1. **Is the bug present in the demo Chat SDK project?**
Not really sure

2. **What modifications have you made to the Chat SDK?**
I integrated the chat sdk with my current app. I take my users to the same exact Private Threads View that that chatsdk has. Did do any modifications to the ChatSDK itself.

3. **iOS Version? Device or simulator?**
Device (iPhone X)

4. **Steps taken to reproduce the problem:**
I have seen the problem a couple of times but I cannot reproduce it yet. 

5. **Expected result:**
Once I receive the notification, I expect to see the message in the thread.

6. **Actual result:**
The message does not show in the thread but I already received a notification for it.

7. **Comments:**

8. Which version of the Chat SDK are you using?
4.9.9

10. For push notifications, are you using client push or have you uploaded the Firebase Cloud Functions script to handle push notifications?
Firebase cloud function script to handle push notifications. However, I am also setting `config.clientPushEnabled = YES`. I remember that I had to enable this in order for the client to use the Firebase Function. 
 

11. Thanks for (`BChatViewController` `initWithThread`) tip. I did find the threadId and I checked the database. It seems the message has not made it to the database which explains why I was not able to see in my thread. However, I did receive a notification from that message. 


You mentioned that you have fixed that now. Has the fix made it to a released version or not yet?

**Comment by bensmiley** [comment]
@muhammadsr if you are having to set the client push enabled flag to yes, it suggests that something is wrong with your push setup. Because this should be handled by the push script. I would recommend double checking the cloud code and cloud messaging sections of your Firebase console to see if there are any error messages. 

If the messages aren't appearing in your database it suggests an issue with the Firebase rules. This issue is probably what is causing the cloud code script not to work. 

The first step would be to disable client push. Then try to debug the cloud code script. Finally, I would double check the rules and briefly check the entire configuration section to see if you've missed out any steps that could cause the message not to be written to the database.

**Comment by muhammadsr** [comment]
@bensmiley the "push script" you are referring to is the firstbase function `pushToChannels`?

I am using the firebase function to send push notifications and I need to enable client push to trigger the firebase function. 

This is from `BFirebasePushHandler`

```
-(void) pushForMessage: (id<PMessage>) message {
    
    if (!message.textString || !message.textString.length || !BChatSDK.config.clientPushEnabled) {
        return;
    }
   ....
   ....
   ....
}
```

**Comment by bensmiley** [comment]
@muhammadsr the Firebase Cloud Functions script adds a listener to the Firebase Database so it will automatically trigger a push notification when a message is received. The push for message is only needed when Firebase isn't being used as the backend - for XMPP for example. 

I think that there are two configuration issues that you have:
1. The message is sometimes failing to be written to the thread
2. The Firebase Cloud Functions script isn't working correctly - if it were and you had client push enabled, you would expect to receive two pushes.

**Comment by muhammadsr** [comment]
@bensmiley I was not aware the Firebase function was listening to events when adding messages to the database. I assume, in the Firebase function, you do this from: 

```
exports.pushListener = functions.database.ref('{rootPath}/threads/{threadId}/messages/{messageId}').onCreate((messageSnapshot, context) => {

    let messageValue = messageSnapshot.val();
    let senderId = messageValue["user-firebase-id"];
....
....
....
```

If that is the case, where is `{rootPath}`coming from? How does the function know which rootPath I am using in my database?

**Comment by bensmiley** [comment]
@muhammadsr yes, you're right that this script listens to thread path. The root path is a wildcard parameter - that's why it's in brackets. That means the script will listen to all root paths.
