### ISSUE TITLE
Crash when deleting messae

### ISSUE THREAD

**Issue by iBinh** [chat-sdk/chat-sdk-ios#339]
1. **Is the bug present in the demo Chat SDK project?**
YES
2. **What modifications have you made to the Chat SDK?**
NO
3. **iOS Version? Device or simulator?**
iOS 12, Device
4. **Steps taken to reproduce the problem:**
Create a conversation, send only one message, delete this message
5. **Expected result:**
Message will be deteled
6. **Actual result:**
App crash
7. **Comments:**
CCMessageWrapper class func 
`-(NSMutableDictionary *) serialize ;`

**Comment by bensmiley** [comment]
@iBinh I can't replicate this on the latest version of the Chat SDK. Can you provide the full stack trace?

**Comment by iBinh** [comment]
![Group](https://user-images.githubusercontent.com/13776018/54740947-67aa6d00-4bef-11e9-9f85-71310984e41c.png)

**Comment by bensmiley** [comment]
Hi @iBinh can you tell me which version of the Chat SDK you're using? Also, can you replicate this issue yourself?
