### ISSUE TITLE
re: no ChatSDK podspec chat-sdk-ios-use_frameworks_beta_2

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#34]
Is there supposed to be a podspec file in the ChatSDK directory per the instructions?

**Comment by simonsmiley64** [comment]
Hi @jimijon,

There are podspec files in the ChatSDK file in the project:

![screen shot 2017-04-20 at 09 39 54](https://cloud.githubusercontent.com/assets/8721425/25206785/5f9cb7f4-25ad-11e7-9c9b-9ea868a4b627.png)

You need to ensure these are linked to from your project podspec. You can navigate from your podfile to the podspec by using ../ to go up a folder and then the name to enter a folder. 

For example in this image the pod file is in the Xcode folder meaning we use the following

```
    pod "ChatSDKCore", :path => "../ChatSDK/ChatSDKCore"
```
- We go up a folder using ../
- We enter the ChatSDK folder ChatSDK/
- We enter the ChatSDKCore folder ChatSDKCore/

We have now linked our podfile with the ChatSDKCore.podspec. We need to do this for each of the modules we are using.

Let me know if you need further help on this,

Simon

**Comment by jimijon** [comment]
I figured, but just wanted to point out it is wrong in the documentation to clarify for others. Thanks for the quick response.

**Comment by simonsmiley64** [comment]
Thanks @jimijon,

Once we have fully tested this new branch we are going to merge it into the master and adjust all the documentation.
