### ISSUE TITLE
Problem with Audio Messages configuration

### ISSUE THREAD

**Issue by lum3ll** [chat-sdk/chat-sdk-ios#340]
1. Copy in Audio folder into the ChatSDKFirebase folder in the Chat SDK
2. Add the path to the Audio folder in **your projects** podfile. If you have a podfile for your project you need to add it to this and not the podfile in the Chat SDK project.
3. In the Chat SDK project it is this:   

```
pod "ChatSDKFirebase/AudioMessages", :path => "../ChatSDKFirebase"
```

You can read a tutorial about configuring this path in your project [here](https://github.com/chat-sdk/chat-sdk-ios/wiki/Chat-SDK-iOS:-How-do-I-link-my-podfile%3F)

4. Call `pod install`
5. Add the audio code in **your project's** app delegate:

```
#import <ChatSDKFirebase/AudioMessages.h>

[[[BAudioMessageModule alloc] init] activate];
```

I have just done this on a downloaded version of the Chat SDK and it compiles without an error, the audio messages are also working as expected. 

<img width="250" alt="screen shot 2017-05-29 at 16 47 47" src="https://cloud.githubusercontent.com/assets/8721425/26555766/913c6106-448e-11e7-98ae-c4df17fb845f.png">

I would expect therefore that there is a step which you are not doing correctly, it might be that you are adding the code to the Chat SDK podspec instead of your own or that you are not linking the path from your podfile to the Audio folder correctly.

If you can add a screenshot of your folder structure showing the podfile and the ChatSDK as well as what you are adding in your podfile I can help see if this is the problem.

Simon

_Originally posted by @simonsmiley64 in https://github.com/chat-sdk/chat-sdk-ios/issues/59#issuecomment-304690738_

All done... but my problem is adding the import and activation code in appDelegate.m in Xcode project folder.

Any idea? I'm crushing my mind.

**Comment by bensmiley** [comment]
Hi @lum3ll I think the instructions you're reading are for an old version of the module. If you go to your [Chat SDK account](https://chatsdk.co/your-account/) you should be able to download the latest version module. It will come with installation instructions. With the latest version of the module and the Chat SDK all you need to do is add the module using Cocoapods and it will be installed and activated automatically.

**Comment by lum3ll** [comment]
I think the problem is in Chat SDK Account. I've found Audio Messages Module 4.10.1 in my downloads, but 4.7 in Purchase Downloads (the one I've downloaded). Maybe links need to be the same.

**Comment by bensmiley** [comment]
@lum3ll this has now been resolved. The old downloads have been removed from the website.
