### ISSUE TITLE
app hangs for long time after authenticate completes

### ISSUE THREAD

**Issue by friendscorpgroup** [chat-sdk/chat-sdk-ios#342]
1. **Is the bug present in the demo Chat SDK project?**
Yes

2. **What modifications have you made to the Chat SDK?**
Nothing

3. **iOS Version? Device or simulator?**
10.4 , 11.0 , 12

4. **Steps taken to reproduce the problem:**
call authenticate if user have large data in chat ( 15 Threads with 50+ messages , which isn't much)

5. **Expected result:**
app should work smoothly

6. **Actual result:**
app hangs after we authentication completes , it takes approx 2 mins to sync and in that time app hangs.

7. **Comments:**

**Comment by lbadias** [comment]
Any updates on this? @friendscorpgroup can you find any workaround?
