### ISSUE TITLE
The Aims Of Three BackgroundMode When Using Push Notification (issue of  iOS)

### ISSUE THREAD

**Issue by VersonWang** [chat-sdk/chat-sdk-ios#346]
1.  iOS
2. version : 4.9.5 
3. Notification
4. BackgroundMode

question:
we must be setting  Location updates, Background fetch, Remote notifications when we use Push Notification ????
why and what are the aims of the three BackgroundMode Settings  ??

<img width="839" alt="WechatIMG83" src="https://user-images.githubusercontent.com/29175135/55303735-7b20c800-547a-11e9-8eb2-9b0979b9ce18.png">

**Comment by bensmiley** [comment]
Only the remote notification permission is needed for push notifications to work. The others are required for the instant reply from lock screen (background fetch) and nearby users module (location updates).

**Comment by VersonWang** [comment]
thank you very much
