### ISSUE TITLE
Custom Sign In View Controller

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#347]
I used to use:

```
let signInController = UIStoryboard(name: sbname, bundle: nil) .instantiateViewController(withIdentifier: "SignInViewController") as! SignInViewController
            BNetworkManager.shared().a.auth().setChallenge(signInController);
```

but setChallenge no longer exists. What is the new way to register my view controller?

**Comment by bensmiley** [comment]
You can use this now:

```
[BChatSDK.ui setLoginViewController:...];
```

Also, bear in mind that the initial view controller should be the splash screen view controller. 

```
UIViewController * rootViewController = BChatSDK.ui.splashScreenNavigationController;
[self.window setRootViewController:rootViewController];
```

**Comment by jimijon** [comment]
Where is the docs on this new splashScreenNavigationController?

I always did this:

            let mainViewController = INDX01TabBarController.init(nibName: nil, bundle: nil)
            self.window?.rootViewController = mainViewController

Anyway I am no longer getting my redirect to may  initial view controller when logged out like I used to.


Thoughts?
