### ISSUE TITLE
Override BSplashScreenViewController

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#349]
I  get a quick "splash screen" when the app auto logins. I changed the logo via config, but since it is white and my interface is black it is still annoying.  Is there a way to override the splash screen or else add a background color config to it?

**Comment by bensmiley** [comment]
Yes, you can do that with the following:

1. Subclass the `BSplashScreenViewController`
2. Modify it as you need. Make the background black etc...
3. After the Chat SDK initialization, call the following line: `BChatSDK.ui()?.setSplashScreenViewController(YourSplashScreenSubclass...)`

**Comment by jimijon** [comment]
BChatSDK.ui()?.setSplashScreenViewController(INDX01SplashScreen)


Cannot convert value of type '(INDX01SplashScreen).Type' to expected argument type '(UIViewController & PSplashScreenViewController)?'
Bit arithmetic in an argument. What does that do?

thanks

**Comment by bensmiley** [comment]
I think you will need to implement the `PSplashScreenViewController` protocol in your `INDX01SplashScreen`.

**Comment by jimijon** [comment]
I tried that.. gives me a redundant error.

For now I just change your xib to be black… easy enough to remember to fix as it will flash white reminding me.
