### ISSUE TITLE
Large Titles not in More or from More.

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#350]
I had to use config to set the Large Titles otherwise it would crash the second time through.
 I had originally set it globally:

            UINavigationBar.appearance().prefersLargeTitles = true

Now with the config setting it, it doesn't crash, but now More, and any screen from More do not have large Titles.

**Comment by bensmiley** [comment]
Hi @jimijon when you say `More` screens what do you mean exactly? We purposely didn't enable large titles on every screen because on some it didn't work well with the UI.

**Comment by jimijon** [comment]
Here are the difference:




These only happen  from the morenavigationcontroller.
Now if I use my global version it will crash the app the second time I load the More controller.
Evidently, there are two nested navigationcontrollers at that point so my global one sets both to use large titles. It would need the parent one to have it set as false to not crash.

**Comment by bensmiley** [comment]
Ah ok I understand what you mean now. I'll need to do some testing where I add extra tabs and see the more screen.

**Comment by jimijon** [comment]
Don’t forget to test completely leaving more and then re-enter. It will crash.

**Comment by jimijon** [comment]
Hmmm,,, a SwiftUI rewrite of all UIElements would be huge.
