### ISSUE TITLE
Room list empty

### ISSUE THREAD

**Issue by dcoparis** [chat-sdk/chat-sdk-ios#353]
1. **Is the bug present in the demo Chat SDK project?**

2. **What modifications have you made to the Chat SDK?**

3. **iOS Version? Device or simulator?**

4. **Steps taken to reproduce the problem:**

5. **Expected result:**

6. **Actual result:**

7. **Comments:**

**Comment by dcoparis** [comment]
Hello,
No Room populated in the public room list after having created one and initiated a chat. When I clic on "Back", the room list is empty
Present in the ChatSDK Demo and swift customized version with Firebase (Realtime database)
IOS 12, device AND simulation
Connected to Firebase in the customized version, with the room well created and chat too
Except Room list, apps semis to run correctly

Thank you
Dominique

**Comment by dcoparis** [comment]
Hello,
No Room populated in the public room list after having created one and initiated a chat. When I clic on "Back", the room list is empty
Present in the ChatSDK Demo and swift customized version with Firebase (Realtime database)
IOS 12, device AND simulation
Connected to Firebase in the customized version, with the room well created and chat too
Except Room list, apps semis to run correctly

Thank you
Dominique

**Comment by bensmiley** [comment]
Hi @dcoparis I've found the issue and this will be fixed in the next release.
