### ISSUE TITLE
pod updated everything...  can't build

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#355]
'Firebase/Firebase.h' file not found

in //  FirebaseAdapter.h

stuck again.

**Comment by bensmiley** [comment]
Hi @jimijon is that the only error? Also, the modules aren't updated to the latest version yet - that will be done by tomorrow so I would advise holding off on updating until then.

**Comment by jimijon** [comment]
so far… I will wait till tomorrow. I can still work without building for awhile.

Thanks

**Comment by jimijon** [comment]
really could use this fixed for my weekend.. thanks.
