### ISSUE TITLE
How to use/extend the UI; for instance Login

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#36]
What is the proper integration strategy for using your UI elements? If we modify the elements won't they be overridden from subsequent updates?

So, in the first use case, what do I do to modify the login? I am running Swift3.    thanks

**Comment by bensmiley** [comment]
If you want to modify the framework you can do that by cloning the project to your Github and then making a new branch. Whenever we make a change to the framework, you can merge it with your branch so you preserve your changes while benefiting from the extra features and bug fixes we're adding. 

In the future, we're going to continue trying to make the framework more modular. We will move the login view, chat view and text input bar into separate pods and repositories. But that's still several weeks away.

**Comment by jimijon** [comment]
Clone or Fork the project ?

**Comment by bensmiley** [comment]
Fork the project and then make a new branch.
