### ISSUE TITLE
Updating from 4.10.x to 4.11.x

### ISSUE THREAD

**Issue by bensmiley** [chat-sdk/chat-sdk-ios#360]

**Comment by Mubeena007** [comment]
After updating to version 4.11.1, i am not getting the push notification. Also, i am getting the below error when installing the updated app over the appstore version.

**Error setting up database: Persistent store migration failed, missing mapping model** 

Please help me out solving these issue.

**Comment by failynsedik** [comment]
I tried the latest app store version and it's showing "bUnknownXMPPErrorOccurred" upon registration.

**Comment by bensmiley** [comment]
@failynsedik the app store version uses XMPP and I'll check this out...
