### ISSUE TITLE
CCThreadWrapper crash in method usersOn when trying to observe event FIRDataEventTypeValue

### ISSUE THREAD

**Issue by antoniochiappetta** [chat-sdk/chat-sdk-ios#361]
1. No, the bug is not present in the demo project.

2. Commented lines from 280 to 293 in ChatSDKFirebase/Adapter/CCThreadWrapper.m

3. iPhone 6 running iOS 12.1

4. After creating a thread for the logged user (either in iOS app or in the Firebase console), as soon as I'm logged in the method usersOn of CCThreadWrapper gets called by the SDK, and when trying to observe the event FIRDataEventTypeValue it gets the list of users for the thread in the object snapshot.value like { "null": { status: "owner"}, "null": {status: "member"}, so the app crashes when invoking allKeys on snapshot.value.

5. The dictionary should be like this { ownerId: { status: "owner"}, memberId: {status: "member"} and not contain null values, to avoid crashing

6. The app crashes because of null values

7. Commenting the lines as stated above I won't be able to observe the event but at least the app executes properly.

**Comment by bensmiley** [comment]
@antoniochiappetta I can see what you're saying. But why are null values being inserted?

**Comment by antoniochiappetta** [comment]
Hi Ben and thank you for your answer. This problem happened to me during the setup of a new project, so I don't see any way in which my development could have created null data. The only thing I can tell you is that I am not creating users on Firebase in the usual way but just using your login system with custom token to create a user whose ID matches the one I receive from our external back-end, that handles the rest of our application.

My doubt is, could these null values be caused by the fact that I basically create a user just with an ID and no every other type of metadata (like name, email or whatever)?

**Comment by bensmiley** [comment]
Hi @antoniochiappetta I'm sure that this issue is caused by the fact that you are creating some parts of the user data manually. I expect that the internal `entityID` property is null. That means that when you make a new thread, this null value is written. If you are using a custom token, I would recommend using :

```
        AccountDetails details = AccountDetails.token("your token");
        ChatSDK.auth().authenticate(details).subscribe(() -> {

        }, throwable -> {
            
        });
```

This will ensure that all the necessary setup steps have been completed for Chat SDK setup.
