### ISSUE TITLE
How to get objective c chat sdk 

### ISSUE THREAD

**Issue by ramohanreddy** [chat-sdk/chat-sdk-ios#364]
Hi @bensmiley 
I am using Xcode 10.1 and swift 4.2 .
I unable to run sample demo chat sdk app.
can u pls send me the flow of implementation documentation.

Thanks&Regards
Ramohan Reddy

**Comment by bensmiley** [comment]
Hi @ramohanreddy can you try running the demo swift project? 

[https://github.com/chat-sdk/chat-sdk-ios/tree/master/XcodeSwift](https://github.com/chat-sdk/chat-sdk-ios/tree/master/XcodeSwift)

If you are having issues, can you explain what problem you're having?

**Comment by jack4oahin** [comment]
I have the same problem, I need Objective_C project, but there is only Swift project
