### ISSUE TITLE
Signin View doesn't dismiss upon a successful login

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#365]
latest everything as of today.

Even when I take out my signing controller and just use the out of box chat login, it still doesn't dismiss after success. Subsequent starts of the app go straight into the app correctly. If you logout and then login again. Same problem. The login screen doesn't dismiss.

**Comment by bensmiley** [comment]
I just tested this in the latest version and I didn't have any issues. How it works currently is that the base view controller should be the splash screen view controller. Then the splash screen controller decides whether to display the login screen or the main app screen. 

I had a quick look at your app and I couldn't see the problem immediately. I would recommend debugging the splash screen view controller. Specifically the `runViewDidLoad` method. Then you should get more of an idea of why it's not working.

**Comment by jimijon** [comment]
I’ll check today. Did you figure out what happened to my stickies?

**Comment by jimijon** [comment]
been going through my code. I have a signinViewController and a splashController. The problem seems to be that the signinViewController places the FirebaseUI over it. Then when the FirebaseUI authenticates, it goes away but no event gets fired back to the signinViewController. No viewWillAppear etc. 

How do you integrate FirebaseUI? I tried using the docs but 
    #import "BFirebaseUIModule.h"

gave an error as it couldn't be found and indeed it does not exist in my pod files.

Thanks

**Comment by jimijon** [comment]
In my case I had to close out my signinViewController with 👍 
        navigationController?.popViewController(animated: true)

Then in my custom splashScreenController I ran:

 override func viewWillAppear(_ animated: Bool) {
        super .viewWillAppear(animated)
        super .runViewDidLoad()
    }
