### ISSUE TITLE
How to register username with password in swift  

### ISSUE THREAD

**Issue by ramohanreddy** [chat-sdk/chat-sdk-ios#366]
Hi @angelolloqui , @ealeksandrov 
I am using Xcode 10.2.0, successfully  install chat sdk pods into my project.
How to register  user name with password.

Thanks&Regards
Ramohan reddy

**Comment by bensmiley** [comment]
Hi @ramohanreddy,
Are you talking about how to register a user using the login screen? Or are you looking for the registration API?
Thanks,
Ben

**Comment by ramohanreddy** [comment]
Hi @bensmiley ,
I am not chat sdk login page.
i need register with email and password when click registration button  on my app.

Thanks& Regards 
Ramohan reddy

**Comment by bensmiley** [comment]
Like this:

```
    BAccountDetails * login = [BAccountDetails username:@"" password:@""];
    [BChatSDK.auth authenticate:login].thenOnMain(^id(id success) {
        
    }, Nil);

    BAccountDetails * signUp = [BAccountDetails signUp:@"" password:@""];
    [BChatSDK.auth authenticate:signUp].thenOnMain(^id(id success) {
        
    }, Nil);
```

**Comment by ramohanreddy** [comment]
Hi @bensmiley ,
can pls send me swift code.

Thanks&Regards
Ramohan Reddy

**Comment by JackyGajjar** [comment]
Hu @ramohanreddy

**Comment by JackyGajjar** [comment]
Hi @ramohanreddy 
here is swift code.

this one for signup
`
let accountDetails = BAccountDetails.signUp("admin@grr.la", password: "123456)
let promise = BChatSDK.auth()?.authenticate(accountDetails!)?.thenOnMain
        _ = promise!({(result: Any?) -> Any? in
            print("------> Result \(String(describing: result))")
            return result
        }, {(error: Error?) -> Any? in
            print("------> Error \(String(describing: error))")
            return error
        })`

if you want login than use.
`let accountDetails = BAccountDetails.username("admin@grr.la", password: "123456)`

**Comment by ramohanreddy** [comment]
Hi @JackyGajjar ,
Thanks for sharing code,But i am unable to do  signup and login .
PFA Image,
'
![Screenshot 2019-06-14 at 11 06 03 AM](https://user-images.githubusercontent.com/18551145/59485721-7de56380-8e94-11e9-973d-d606098c003f.png)
'

Thanks&Regards
Ramohan Reddy

**Comment by bensmiley** [comment]
```
        let accountDetails = BAccountDetails.signUp("1@d.co", password: "123456")
        let promise = BChatSDK.auth()?.authenticate(accountDetails!)?.thenOnMain
        _ = promise!({result in
            return result
        }, {error in
            return error
        })
```
This works for me. Just make sure you use it after `BChatSDK.initialize` has been called.
