### ISSUE TITLE
Error while uploading iOS App to AppStore

### ISSUE THREAD

**Issue by Pankaj03** [chat-sdk/chat-sdk-ios#367]
Hi  @angelolloqui @ealeksandrov,

Hope you guys doing well!

I am facing a critical issue while uploading app to apple store.

1. **Is the bug present in the demo Chat SDK project?**
yes
2. **What modifications have you made to the Chat SDK?**
some UI enhancements
3. **iOS Version? Device or simulator?**
11.0, while uploading app to apple store.
4. **Steps taken to reproduce the problem:**
Generating Archive create a extra ChaUI executable.
5. **Expected result:**
Successful upload
6. **Actual result:**
Error: We are facing a critical issue in iOS sdk while uploading app to apple store i.e.,
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'myapp.app/Frameworks/ChatSDK.framework/ChatUI.bundle/ChatUI' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

7. **Comments:**
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'myapp.app/Frameworks/ChatSDK.framework/ChatUI.bundle/ChatUI' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

Please help me on this.

Thanks!

**Comment by bensmiley** [comment]
I think is caused by a problem with your Xcode project structure. How are you integrating the Chat SDK with your project?

**Comment by Pankaj03** [comment]
Hi @bensmiley We are integrating using pods:

  pod 'ChatSDK'
  pod 'ChatSDKFirebase/Adapter'
  pod 'ChatSDKFirebase/FileStorage'
  pod 'ChatSDKFirebase/Push'

The problem is, whenever we are building the project, there is an extra bundle of "ChatUI" or the executable file of ChatUI has been generated automatically.
We are getting the issue only at the time of uploading the app to the app store.

Kindly suggest the way to get out of it.

Thanks!

**Comment by Pankaj03** [comment]
Hello @simonsmiley64 

Hope you doing great!

Can you please help me on this issue, as I'm getting in the only iOS release.

Thanks!
