### ISSUE TITLE
How to access directly Chat User Interface screen in my App?

### ISSUE THREAD

**Issue by APGautam** [chat-sdk/chat-sdk-ios#368]
First of all I would like to say thanks for this Chat SDK, it's very helpful.

I went through from the sample app 'ChatSDKSwift' code, there you are accessing your SDK's Splash screen from your sample App using 'navigationControllerWithRootViewController'. Here is the method:

> BChatSDK.ui().splashScreenNavigationController()

Problem: I am developing a Chat App in Swift, where I displaying my own Splash and Login screen. 

Now the problem is after Login, I have to display your SDK's Chat User Interface. Can you please help me to navigate directly to Chat window after successfully Login. 

Thank you!

**Comment by bensmiley** [comment]
In this case, you would just show the main view controller:

```
BChatSDK.ui.mainViewController
```

But bear in mind that you should call `BChatSDK.auth authenticate` before that.

**Comment by jimijon** [comment]
This thread might help you:
#365
