### ISSUE TITLE
Clear local Data crashes

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#369]
Trying out the detailedProfile. Tap Clear Local Data... boom.

=====
INDX01[15197:41337352] *** Terminating app due to uncaught exception 'InvalidPathValidation', reason: '(child:) Must be a non-empty string and not contain '.' '#' '$' '[' or ']''
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001125afb6e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00000001123c8f57 objc_exception_throw + 48
	2   INDX01                              0x0000000109fdf4ec +[FValidation validateFrom:validRootPathString:] + 0
	3   INDX01                              0x0000000109f9d817 -[FIRDatabaseReference child:] + 148

**Comment by bensmiley** [comment]
I've fixed this now. It will be available with the next Cocoapods release which will be this week.
