### ISSUE TITLE
custom ChatViewController

### ISSUE THREAD

**Issue by TaherZaki** [chat-sdk/chat-sdk-ios#370]
i try to custom ChatViewController as i read in documentation it like that:-

BChatSDK.ui()?.setChatViewController(<#T##provider: ((PThread?) -> BChatViewController?)!##((PThread?) -> BChatViewController?)!##(PThread?) -> BChatViewController?#>)

I don't understand what is PThread and how i do it so i just need example to change UI

**Comment by jimijon** [comment]
just do this:              
     BChatSDK.ui()?.setChatViewController(yourController)
make sure yourController subclasses BChatViewController

**Comment by TaherZaki** [comment]
it show this error :- 
Cannot convert value of type '(ChatViewController).Type' to expected argument type '((PThread?) -> BChatViewController?)?'

**Comment by jimijon** [comment]
evidently you need to pass it a thread and then you get the controller, here is what I do for profileController, I override the adapter with this:

    override func profileViewController(with user: PUser?) -> UIViewController? {


        let controller = UIStoryboard(name: "MyProfile", bundle: Bundle.main).instantiateViewController(withIdentifier: "INDX01ProfileTableViewController") as? INDX01ProfileTableViewController
        controller?.user = user
        return controller
    }

That was in my 

   class INDX01ChatSDKInterfaceAdaptor: BDefaultInterfaceAdapter {

I the appDelegate I set that to be the default interfaceAdapter

**Comment by TaherZaki** [comment]
i fixed with edit on framework it self 
thanks
