### ISSUE TITLE
edit profile image 

### ISSUE THREAD

**Issue by TaherZaki** [chat-sdk/chat-sdk-ios#373]
when  i try to change profile image changes happened locally only  nothing happened in firebase user meta data so i want to know  what i missing ?

**Comment by TaherZaki** [comment]
Any help?!

**Comment by jimijon** [comment]
does the imageUrl in the user's profile meta data change?

**Comment by TaherZaki** [comment]
i couldn't find profile image tag name on Firebase

**Comment by jimijon** [comment]
You don’t see something like this:

**Comment by TaherZaki** [comment]
> does the imageUrl in the user's profile meta data change?
![Screen Shot 2019-07-03 at 3 54 59 PM](https://user-images.githubusercontent.com/1589735/60597602-79351080-9dab-11e9-9c2d-1432a23e79d6.png)

I couldn't find profile image tag name on Firebase

**Comment by TaherZaki** [comment]
here code i found but nothing happen

- (void)cropViewController:(TOCropViewController *)cropViewController didCropToImage:(UIImage *)image withRect:(CGRect)cropRect angle:(NSInteger)angle {

    // Make sure to update the profile picture once the image is set
    [profilePictureButton setImage:image forState:UIControlStateNormal];
    
    // Now reduce the image to 200x200 for the profile picture
    image = [image resizedImage:bProfilePictureSize interpolationQuality:kCGInterpolationHigh];

    // Set the user image
    [profilePictureButton setImage:image forState:UIControlStateNormal];
    
    // Update the user
    id<PUser> user = BChatSDK.currentUser;
    [user setImage:UIImagePNGRepresentation(image)];
    
    // Set the image now
    [BChatSDK.upload uploadImage:image].thenOnMain(^id(NSDictionary * urls) {
    
        // Set the meta data
        [user updateMeta:@{bUserImageURLKey: urls[bImagePath]}];
    
        // Update the user
        [BChatSDK.core pushUser];
    
        return urls;
    }, Nil);
    
    [cropViewController dismissViewControllerAnimated:YES completion:nil];
}

**Comment by jimijon** [comment]
in BProfilesPictureViewController there are these calls:

    
- (void)addPictureURL:(NSString *)url {
    _pictures = [BProfilePicturesHelper addPicture:url toPictures:_pictures];
    [self updateUI];
    [self savePictures];
}

- (void)removePictureURL:(NSString *)url {
    _pictures = [BProfilePicturesHelper removePicture:url fromPictures:_pictures];
    [self updateUI];
    [self savePictures];
}

- (void)setDefaultPictureURL:(NSString *)url {
    _pictures = [BProfilePicturesHelper setDefaultPicture:url inPictures:_pictures];
    [self updateUI];
    [BChatSDK.currentUser setImageURL:url];
    [self savePictures];
}
    - (void)savePictures {

maybe put a break point around those calls?

**Comment by mahesh-ivy** [comment]
@TaherZaki  can you please help me with enabling this feature to edit profile. For me the edit option is not even showing.
