### ISSUE TITLE
The private thread was created to only owner user

### ISSUE THREAD

**Issue by karayel** [chat-sdk/chat-sdk-ios#375]
1. **Is the bug present in the demo Chat SDK project?**

2. **What modifications have you made to the Chat SDK?**

No Modification and latest version

3. **iOS Version? Device or simulator?**

Iphone 6 (IOS Version 12.3.1) Device + Iphone 6 Simulator

4. **Steps taken to reproduce the problem:**

Custom Private Thread View Controller:

```
class ThreadViewController: BPrivateThreadsViewController {
    
    override func viewDidLoad() {
        super.threads = []
        super.viewDidLoad()
        
        super.tableView.separatorStyle = .none
    }
}
```

Private Group Creation:

```
BChatSDK.core()?.createThread(withUsers: ["otherUserAuthenticationId"], name: "Thread1", type: bThreadTypePrivateGroup, forceCreate: false, threadCreated: { (error, thread) in
                self.pushChatViewController(with: thread)
        })
```

5. **Expected result:**

Create group with given name and link group to other users.

6. **Actual result:**

Owner can create group and have group related information on both client and firebase but the group is not linked to other user and other user can not see anything about group.

7. **Comments:**

I saw #372 and check database rule twice and it is not still working.

**Comment by bensmiley** [comment]
It looks like you are passing in user IDs rather than `id<PUser>` objects.
