### ISSUE TITLE
Issue after updating to 4.11.1

### ISSUE THREAD

**Issue by Mubeena007** [chat-sdk/chat-sdk-ios#378]
After updating to version 4.11.1, i am not getting the push notification. Also, i am getting the below error when installing the updated app over the appstore version(which was using 4.10.x).

**Error setting up database: Persistent store migration failed, missing mapping model**

Please help me out solving these issue.

**Comment by jimijon** [comment]
Go find the chatsdk coredata model and make sure to select the latest version in it. Somehow a pod update doesn’t do that.

**Comment by Mubeena007** [comment]
I have the latest one selected.

![Screen Shot 2019-07-09 at 3 12 15 PM](https://user-images.githubusercontent.com/52694640/60883717-f523d280-a25b-11e9-9b00-f82bb804b95c.png)

**Comment by bensmiley** [comment]
Which version were you upgrading from? Do you have any problem if you install the old version and then update it by compiling using Xcode? Did you make any changes to the data model?

**Comment by Mubeena007** [comment]
I was using version 4.10.x. And recently i did a pod update. 

Now, when i am testing the upgrade for releasing to the store, i am getting the crash for the first run. Second time it runs the application without crash, but in the log i am getting this error.

**Error setting up database: Persistent store migration failed, missing mapping model**

Also, the push notification is not working at all.

**Comment by Mubeena007** [comment]
Related to the data model, i didn't do anything manually. Just updated the pod.

**Comment by bensmiley** [comment]
@Mubeena007 in terms of push notifications, can you confirm that you've gone through the [documentation steps](https://github.com/chat-sdk/chat-sdk-ios#push-notifications). It would be worth reviewing them because they do change periodically. 

In terms of the update to the code, I would need to see a version of your project pre-update and then be able to update it myself to test it. Would that be possible?

**Comment by Mubeena007** [comment]
@bensmiley I gone through the push notification steps and confirmed all was set. Still i am not getting the push notification.

Regarding the crash, from the log i am getting the below message. I checked the data model. My live app(in appstore) is using v15 and after update to 4.11.1, i have v19 of the datamodel as the current one.


**reason=Can't find or automatically infer mapping model for migration, NSUnderlyingError=0x280fc3ba0 {Error Domain=NSCocoaErrorDomain Code=134190 "(null)" UserInfo={entity=CDUser, property=threadsCreated, reason=Can not map from a to-many to a to-one relationship}}} with userInfo dictionary {  NSUnderlyingError = "Error Domain=NSCocoaErrorDomain Code=134190 \"(null)\" UserInfo={entity=CDUser, property=threadsCreated, reason=Can not map from a to-many to a to-one relationship}"**


**Old version**
![Screen Shot 2019-07-09 at 5 14 41 PM](https://user-images.githubusercontent.com/52694640/60891925-47222380-a26f-11e9-8e89-4a6b7283a9b7.png) . 
<img width="588" alt="Screen Shot 2019-07-09 at 5 33 06 PM" src="https://user-images.githubusercontent.com/52694640/60892145-b0099b80-a26f-11e9-856c-d7ecc0d52b56.png">


**New version**
![Screen Shot 2019-07-09 at 3 12 15 PM](https://user-images.githubusercontent.com/52694640/60891939-4a1d1400-a26f-11e9-9c94-63186ecf9d2a.png)
<img width="596" alt="Screen Shot 2019-07-09 at 5 33 17 PM" src="https://user-images.githubusercontent.com/52694640/60892225-d4657800-a26f-11e9-9953-edd213f83de8.png">
