### ISSUE TITLE
after launch chat sdk. then how to open my application.(like exit.)

### ISSUE THREAD

**Issue by Sachin5exceptions** [chat-sdk/chat-sdk-ios#379]
1. **Is the bug present in the demo Chat SDK project?**

2. **What modifications have you made to the Chat SDK?**

3. **iOS Version? Device or simulator?**

4. **Steps taken to reproduce the problem:**

5. **Expected result:**

6. **Actual result:**

7. **Comments:**

**Comment by AnotherWayIn** [comment]
i'd like to know this also. So far i've tried editing the BPublicThreadsViewController.m ChatSDK code (yes i know bad practice) like so:

- (void)viewDidLoad {
    
    [super viewDidLoad];
    
    _slideToDeleteDisabled = !BChatSDK.config.allowPublicThreadDeletion;
    
    // Add new group button
    if(BChatSDK.shared.configuration.allowUsersToCreatePublicChats) {
        
        self.navigationItem.rightBarButtonItem =  [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemAdd
                                                                                                target:self
                                                                                                action:@selector(createThread)];
    }
    // added 
    **self.navigationItem.leftBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:@"Close" style:UIBarButtonItemStylePlain target:self action:@selector(backToApp)];**
    
    
}

// added 
**- (void)backToApp {
    NSLog(@"close tapped");
    [self dismissViewControllerAnimated:YES completion:nil]; // not working

}**

**Comment by AnotherWayIn** [comment]
It would be great to be able to have a BConfiguration we could set to have these screens dismiss
thanks

**Comment by Sachin5exceptions** [comment]
Please watch this video -
https://drive.google.com/file/d/1PUCbcifaDAmibpQqz96ggII61RgVtnw_/view

My swift class login button. after a chat launch, I want to reopen login button screen. how to achieve this task. I am totally confused. Please reply soon!

**Comment by Sachin5exceptions** [comment]
> i'd like to know this also. So far i've tried editing the BPublicThreadsViewController.m ChatSDK code (yes i know bad practice) like so to add a close button but the view does not dismiss (sorry about the formatting):
> 
> * (void)viewDidLoad {
>   [super viewDidLoad];
>   _slideToDeleteDisabled = !BChatSDK.config.allowPublicThreadDeletion;
>   // Add new group button
>   if(BChatSDK.shared.configuration.allowUsersToCreatePublicChats) {
>   ```
>     self.navigationItem.rightBarButtonItem =  [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemAdd
>                                                                                             target:self
>                                                                                             action:@selector(createThread)];
>   ```
>   
>   
>   }
>   **// added by me
>   self.navigationItem.leftBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:@"Close" style:UIBarButtonItemStylePlain target:self action:@selector(backToApp)];**
> 
> }
> 
> **// added by me
> 
> * (void)backToApp {
>   NSLog(@"close tapped");
>   [self dismissViewControllerAnimated:YES completion:nil];
> 
> }**

Your code is not working.

**Comment by AnotherWayIn** [comment]
yes i know. I need help with it. i've also tried the following in my appdelegate and then subclassing

        BChatSDK.shared()?.interfaceAdapter = MyDefaultInterfaceAdapter()
        BChatSDK.ui()?.setLoginViewController(MyLoginVC())
        BChatSDK.ui()?.setPublicThreadsViewController(MyPublicThreadsVC())

**Comment by bensmiley** [comment]
@AnotherWayIn this goes a bit beyond what we offer for free support because you're asking for help with your custom development. How you dismiss the Chat SDK depends on how you presented it in the first place. You would need to have some idea about the view controller stack. 

The default Chat SDK stack has the splash screen at the bottom and then either the `BLoginViewController` or the `BMainViewController` above it. 

```
BSplashScreenViewController / BMainViewController
```

In your method, you could use the `setViewControllers`[[1](https://developer.apple.com/documentation/uikit/uinavigationcontroller/1621861-setviewcontrollers)] method and then provide the stack you need for your app.

**Comment by AnotherWayIn** [comment]
Thanks Ben
