### ISSUE TITLE
How to navigate to my app screen by chat SDK.

### ISSUE THREAD

**Issue by truvideo-5exceptions-rajeev** [chat-sdk/chat-sdk-ios#380]
1. **Is the bug present in the demo Chat SDK project?**

2. **What modifications have you made to the Chat SDK?**

3. **iOS Version? Device or simulator?**

4. **Steps taken to reproduce the problem:**

5. **Expected result:**

6. **Actual result:**

7. **Comments:**

**Comment by bensmiley** [comment]
@Sachin5exceptions can you explain what you're trying to do?

Thanks,

Ben

**Comment by Sachin5exceptions** [comment]
Please watch this video - 
https://drive.google.com/file/d/1PUCbcifaDAmibpQqz96ggII61RgVtnw_/view

My swift class login button. after a chat launch, I want to reopen login button screen. how to achieve this task. I am totally confused. Please reply soon!

**Comment by Sachin5exceptions** [comment]
> @Sachin5exceptions can you explain what you're trying to do?
> 
> Thanks,
> 
> Ben

Please watch this video -
https://drive.google.com/file/d/1PUCbcifaDAmibpQqz96ggII61RgVtnw_/view

My swift class login button. after a chat launch, I want to reopen login button screen. how to achieve this task. I am totally confused. Please reply soon!

**Comment by bensmiley** [comment]
@Sachin5exceptions I'm afraid I still don't understand what you're trying to do. Your video shows the app loading up. Then you click the tabs and click edit multiple times. Can you explain what functionality you are looking for?

**Comment by Sachin5exceptions** [comment]
I Want to "edit" button to "Close" button. then Close button press I want to redirect to login button screen(swift language).

**Comment by Sachin5exceptions** [comment]
> @Sachin5exceptions I'm afraid I still don't understand what you're trying to do. Your video shows the app loading up. Then you click the tabs and click edit multiple times. Can you explain what functionality you are looking for?

I Want to "edit" button to "Close" button. then Close button press I want to redirect to login button screen(swift language).

**Comment by bensmiley** [comment]
You can do that by following [this guide](https://github.com/chat-sdk/docs#using-the-interface-manager). You can override the `BPrivateThreadsViewController` and add a new left bar button item. Then when it's clicked you can update the controller stack to show the view you need.
