### ISSUE TITLE
SticketMessage 4.11.0 not working

### ISSUE THREAD

**Issue by HOMINHTUNG** [chat-sdk/chat-sdk-ios#381]
1. **Is the bug present in the demo Chat SDK project?**

2. **What modifications have you made to the Chat SDK?**

- I'm using ChatSDK and ChatSDKModules local 

3. **iOS Version? Device or simulator?**

- iOS 12

4. **Steps taken to reproduce the problem:**

-  i using BStickerMessageModule.init().activate().
-  Sticket ChatOption still show in BChatViewController and when i click option Sticket -> app crash 

5. **Expected result:**

- Show SticketView and i can send SticketMessage

6. **Actual result:**

- BChatOption: RXPromise execute loop unlimited ->  crash app

7. **Comments:**

- i pay Licensing Module ReadReciept and SticketMessage, ReadReciept  work well but SticketMessage not good :((, i using sticket module with platform android and this work well.
- SticketMessage 4.11.0 and i try ChatSDK 4.11.0/4.11.1 this not woking. And i try module with example and this not woking
- i see Features Sticket module:
   – Sticker message support (yes)
   – 4 default sticker pack (yes)
   – Easily add new packs by modifying a config file (yes)
   – This modules includes the Keyboard Overlay module for free! (no)
- i hope you can help me! thanks you!

<img width="514" alt="Screen Shot 2019-07-15 at 6 32 22 PM" src="https://user-images.githubusercontent.com/26228223/61213322-ea22e380-a72e-11e9-90c5-5beceefa76ba.png">

<img width="1279" alt="Screen Shot 2019-07-15 at 6 00 23 PM" src="https://user-images.githubusercontent.com/26228223/61212330-286ad380-a72c-11e9-91a6-71e66c0deb87.png">

**Comment by bensmiley** [comment]
Hi @HOMINHTUNG can you send me a message on our [Slack channel](slack.sdk.chat) and I will support you directly.

**Comment by HOMINHTUNG** [comment]
Sorry Ben! but Slack channel not found :((, can you invite to me: hominhtung.it@gmail.com

Thanks!

**Comment by HOMINHTUNG** [comment]
Hi Ben,

I send you verify email, please check your email!


*Thanks!Best Regards!*

Ho Minh Tung

**Comment by 3r1k83** [comment]
I have the same problem, I think it's because KeyboardOverlayOptions library is missing. Can you add me in the slack channel as well? erik.peruzzi@gmail.com

**Comment by bensmiley** [comment]
@3r1k83 I've sent you an email.
