### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by C-D-110** [chat-sdk/chat-sdk-ios#383]
Hello, 

I am trying to login to chat sdk with this code

```
        let email = "xxx@xx.com"
        let password = "123333"
        let account = BAccountDetails.username(email, password: password)
        let promise = BChatSDK.auth()?.authenticate(account!)?.thenOnMain
        _ = promise!({result in
            return result
        }, {error in
            return error
        })
```

I am always getting error 
`Error Domain=RXPromise Code=-1000 "" UserInfo={NSLocalizedFailureReason=}`
no reason is mentioned as well. User is already registered and getting error of already registered as well. Some body help me please..?

**Comment by C-D-110** [comment]
@bensmiley can i get on this please?

**Comment by bensmiley** [comment]
@C-D-110 this is probably to do with your Firebase configuration. Have you enabled email / password authentication from in the Firebase console?

**Comment by C-D-110** [comment]
Yes it is enabled there

**Comment by C-D-110** [comment]
@bensmiley here is configuration, can you please point if i am missing some thing

    func chatSDKConfiguration(application : UIApplication, launchOptions : [UIApplicationLaunchOptionsKey: Any]?)  {
        let config = BConfiguration.init()
        config.rootPath = "v6"
        config.allowUsersToCreatePublicChats = false
        config.googleMapsApiKey = "Axxxxx"
        config.clearDatabaseWhenDataVersionChanges = false
        config.clearDataWhenRootPathChanges = false
        config.loginUsernamePlaceholder = "Email"
        config.firebaseGoogleServicesPlistName = "GoogleService-Info.plist"
        config.firebaseShouldConfigureAutomatically = false

         // Facebook Setup
        config.facebookAppId = "1xxxxxxx"

        // Twitter Setup
        config.twitterApiKey = "xxxxx"
        config.twitterSecret = "xxxxxxx"
        
        // Google Setup
        config.googleClientKey = "xxxxxxxx"
        
        BChatSDK.initialize(config, app: application, options: launchOptions)
    }

**Comment by C-D-110** [comment]
@bensmiley i am confused? i can signup and login with new user from mobile app but not able to login with that users which logged in are from website. Is there any extra work around i have to do?
