### ISSUE TITLE
didReceiveRemoteNotification method not working in my swift appdelgate.

### ISSUE THREAD

**Issue by truvideo-5exceptions-rajeev** [chat-sdk/chat-sdk-ios#384]
1. **Is the bug present in the demo Chat SDK project?**

2. **What modifications have you made to the Chat SDK?**
 - > I want to get notification from swift appdegate class. right now I receive notification "bcharsdk.m" class.

3. **iOS Version? Device or simulator?**

4. **Steps taken to reproduce the problem:**

5. **Expected result:**

6. **Actual result:**

7. **Comments:**
"didReceiveRemoteNotification" method call form "bcharsdk.m" class. I want to get notifications to swift Applegate class. how to achieve this. Please reply asap.

I have already done chat SDK info.plist copy in my google service list. but I can't get a notification in my swift app delegate.

**Comment by Sachin5exceptions** [comment]
I have already done chat SDK info.plist copy in my google service list. but I can't get a notification in my swift app delegate.

**Comment by Sachin5exceptions** [comment]
Please reply soon!

**Comment by bensmiley** [comment]
This is probably a problem with your projects push configuration. Can you verify that you've completed all the steps to enable push notifications? 

Also, please don't link or re-open unrelated issues. It doesn't help us when providing support.
