### ISSUE TITLE
Chat Thread Name Issue

### ISSUE THREAD

**Issue by NagaSyam** [chat-sdk/chat-sdk-ios#386]
@bensmiley  Please check this
1. **Is the bug present in the demo Chat SDK project?**
No

2. **What modifications have you made to the Chat SDK?**
None

3. **iOS Version? Device or simulator?**
11.0, iOS Simulator

4. **Steps taken to reproduce the problem:**
This is the method I am using to create a thread and open Chat screen.

```      
  let otherUserWrap : CCUserWrapper = CCUserWrapper.user(withEntityID: userDetails?.uid ?? "")
        otherUserWrap.metaOn()
        otherUserWrap.onlineOn()
        
        let otherUserModel = otherUserWrap.model()
        otherUserModel?.setImageURL(userDetails?.profilePhotoUrl ?? "")
        otherUserModel?.setName(userDetails?.name ?? "")
        
        _ = BChatSDK.core().createThread(withUsers: [BChatSDK.currentUser()! ,otherUserModel!], threadCreated: {(error: Error?, thread:PThread?) in
            let cvc = BChatSDK.ui().chatViewController(with: thread)
            self.hideNavigationBar(hide: false)
            self.navigationController?.pushViewController(cvc!, animated: true)
        })
```

5. **Expected result:**
Thread name must be of other users name

6. **Actual result:**
It is displaying as "Thread
![Screenshot 2019-07-26 at 1 14 10 PM](https://user-images.githubusercontent.com/23054189/61938114-f3714300-afad-11e9-8f56-7e1819177fe8.png)
"

7. **Comments:**
Please help me to fix this.

Thanks in advance
Naga

**Comment by Sachin5exceptions** [comment]
Please manage by the backend server.

**Comment by bensmiley** [comment]
Hi, @NagaSyam where are you getting the other user's ID from? Are you sure that the user exists already in the Firebase database? If you want to observe a user I would recommend using this:

```
[BChatSDK.core observeUser: @"userID"];
```

Rather than turning meta and online on manually. 

If the other user exists in Firebase, your code should be correct.

**Comment by NagaSyam** [comment]
@bensmiley  Thanks for the reply. It is working as expected now.

**Comment by Sachin5exceptions** [comment]
Sir, please reply Reopened #384



| 
| 
| 
|  |  |

 |

 |
| 
|  | 
didReceiveRemoteNotification method not working in my swift appdelgate. ...

Is the bug present in the demo Chat SDK project? What modifications have you made to the Chat SDK? I want to get...
 |

 |

 |





    On Wednesday, July 31, 2019, 11:42:26 AM GMT+5:30, NagaSyam <notifications@github.com> wrote:  
 
 
Reopened #386.
