### ISSUE TITLE
Main thread block after app launch

### ISSUE THREAD

**Issue by NagaSyam** [chat-sdk/chat-sdk-ios#387]
@bensmiley please check this

1. **Is the bug present in the demo Chat SDK project?**
No

2. **What modifications have you made to the Chat SDK?**
None

3. **iOS Version? Device or simulator?**
iOS 11.0, using Simulator

4. **Steps taken to reproduce the problem:**
Launch the app and wait for 2 seconds

5. **Expected result:**
No blocks for main thread

6. **Actual result:**
After launching the app and waiting for 2-3 seconds I can see there is a block for main thread for 2-3 seconds in the app while using ChatSDK.

My code in DidFinishLaunchWithOptions in AppDelegate - 

       let config = BConfiguration.init();
        config.rootPath = "test"
        config.googleLoginEnabled = false
        config.facebookLoginEnabled = false
        config.forgotPasswordEnabled = false
        config.termsAndConditionsEnabled = false
        config.twitterLoginEnabled = false
        config.anonymousLoginEnabled = false
        
        config.profilePicturesEnabled = true
        config.locationMessagesEnabled = false
        config.imageMessagesEnabled = false
        config.userChatInfoEnabled = false
        
        config.clearDataWhenRootPathChanges = true
        
        config.clientPushEnabled = true
        config.showUserAvatarsOn1to1Threads = true
        config.profilePicturesEnabled = true
        
        BChatSDK.initialize(config, app: application, options: launchOptions)
        
        BChatSDK.core()?.goOnline()

If I skip initialising chatSDK app runs smoothly without any blocks, of course this will not help me to meet the purpose of the app.  

7. **Comments:**
Please help me to fix this.

Thanks in advance
Naga

**Comment by parulgarg004** [comment]
@bensmiley please check and help
