### ISSUE TITLE
Chat cells collapsing 

### ISSUE THREAD

**Issue by C-D-110** [chat-sdk/chat-sdk-ios#388]
1. **Is the bug present in the demo Chat SDK project?**
yes
2. **What modifications have you made to the Chat SDK?**
creating thread

3. **iOS Version? Device or simulator?**
simulator - iphone x, 12.4

4. **Steps taken to reproduce the problem:**
create thread

5. **Expected result:**
cells proper listiing

6. **Actual result:**
Please see [screenshot](https://prnt.sc/oopkgo)

7. **Comments:**

**Comment by jimijon** [comment]
I am having the same issue.

**Comment by failynsedik** [comment]
@C-D-110 @jimijon Did you find any solutions for this?

**Comment by failynsedik** [comment]
Hi. So I found that this happens, at least for me, when I change from one root path to another while on the same chat.

**Comment by bensmiley** [comment]
@failynsedik if you change the root path you will need to reinstall the app. Or you can try setting:

```
config.clearDataWhenRootPathChanges = true
```

**Comment by failynsedik** [comment]
> @failynsedik if you change the root path you will need to reinstall the app. Or you can try setting:
> 
> ```
> config.clearDataWhenRootPathChanges = true
> ```

Thanks for this @bensmiley. We just did a reinstallation when we encountered it.
