### ISSUE TITLE
Public Chat - Bugs, Warnings and Documentation please

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#390]
Latest everything of Firebase and Chat as of today.

I am trying to create a public chat. Here is my code. Is this correct:

```
let eID = "\(item.symbol!)-Public"

        if let thread: PThread = BChatSDK.db().fetchOrCreateEntity(withID: eID, withType: bThreadEntity) as? PThread {
               let vc = BInterfaceManager.shared().a().chatViewController(with: thread)
               vc?.title = eID
               if let vc = vc {
                   navigationController?.pushViewController(vc, animated: true)
               }
           }else{
               BChatSDK.publicThread().createPublicThread(withName: eID).thenOnMain({ thread in
                   let vc: UIViewController? = BChatSDK.ui().chatViewController(with: thread as? PThread)
                          if let aVc = vc {
                              self.navigationController?.pushViewController(aVc, animated: true)
                          }
                          return nil
                      }, { error in
                          // Handle error
                        print("ChatSDK Error WLD")
                          return error
                      })
           }
```
Warning: "Result of call to function returning 'RXPromise?' is unused"
Bug*: When I type in a second line of chat the chats overwrite each other as in the other issue:

* I don't see this bug with the private chats.

Since I am getting a warning, what should be my proper syntax in Swift?

Finally: We need a chapter dedicated to group and private chat usage, differences, etc.

**Comment by jimijon** [comment]
Here are two days of chats in a public chat:

Problem one:  "tap here for contact info" what is that for?
Problem two: Spacing both different days and same day.


<img width="441" alt="Screen Shot 2019-09-04 at 12 36 03 PM" src="https://user-images.githubusercontent.com/971445/64274080-a4a1bc00-cf10-11e9-9cfa-ecdf217f8ce1.png">

**Comment by bensmiley** [comment]
@jimijon I've not been able to replicate this issue. Can you replicate it with the Github version of the messenger? Are there certain situations where it works? Or is it always like this?

**Comment by jimijon** [comment]
As I mentioned. The chat is fine private. I am now trying to again implement a public chat, hence my asking for documentation as I see this confusion in many of the issues here. And this is only happening in my public chat attempt. I also did not see a chat from my tester, nor he see mine. I tried it with and without override in my adaptor:

     override func publicThreadsViewController() -> INDX01ConversationsViewController? {
        if !(_publicThreadsViewController != nil) {
            _publicThreadsViewController = INDX01ConversationsViewController()
        }
        return _publicThreadsViewController
    }
