### ISSUE TITLE
[Crash] NSDictionary unrecognized selector sent to instance.

### ISSUE THREAD

**Issue by dund-1132** [chat-sdk/chat-sdk-ios#391]
I found a problem in the source code.

Detail:

In header file: 
https://github.com/chat-sdk/chat-sdk-ios/blob/master/ChatSDKCore/Classes/Categories/NSDictionary%2BMeta.h#L14
`-(NSDictionary *) setDictMetaValue: (id) value forKey: (NSString *) key`

In implement file:
https://github.com/chat-sdk/chat-sdk-ios/blob/master/ChatSDKCore/Classes/Categories/NSDictionary%2BMeta.m#L20
`-(NSDictionary *) setMetaDictValue: (id) value forKey: (NSString *) key`

It seems to be different.

**Comment by oTranXuanDiep** [comment]
U should try instead of others frameworks 🤣  🤣 🤣 🤣 🤣 🤣 🤣 🤣

**Comment by bensmiley** [comment]
Fixed.
