### ISSUE TITLE
Bubbles messages are cut and profile picture don't appear

### ISSUE THREAD

**Issue by brunomartinez16** [chat-sdk/chat-sdk-ios#395]
**What modifications have you made to the Chat SDK?**
 only change the BConfiguration: 
    config.messageColorMe = "#646982"
    config.messageColorReply = "#4CBFAA"
    config.messageTextColorReply = "FFFFFF"
    config.messageTextColorMe = "FFFFFF"
    config.userChatInfoEnabled = false
    config.defaultBlankAvatar = UIImage(named: "examplePhoto")
    config.showLocalNotifications = true
    config.showUserAvatarsOn1to1Threads = true
**iOS Version? Device or simulator?**
 Device. Iphone X
**Steps taken to reproduce the problem:**
 The first time it launch the app the bubbles of the message and profile picture for each user look fine. But when user close the app, and open again, the bubbles are cut and the picture aren't loaded. 
**Expected result:**
![unnamed (1)](https://user-images.githubusercontent.com/18013564/66056351-5aaaf680-e50d-11e9-86f1-e22b39f18552.jpg)

**Actual result:**
![unnamed](https://user-images.githubusercontent.com/18013564/66056373-61396e00-e50d-11e9-8fad-e0d6a666a01b.jpg)

**Comments:**
Also it's important to know that after the user add a new message the profile picture of the user does appear, but the others bubbles of the messages remains cut.
PD: Please ignore the volume icon, it's related to my abilities to take a snapshot

**Comment by brunomartinez16** [comment]
When user delete the app, and install it again. The message bubbles and images look perfects, but when user close the app and run it again, the bubbles are cut and the image don't appear. Maybe it have something to do with cache? I take a look at code and I think that the the bmessageposition it always MIDDLE, so this seems to be the main reason, but I'm not familiar with this code so please help me with this!!

**Comment by failynsedik** [comment]
Having the same issue with the profile picture.

**Comment by failynsedik** [comment]
So, I found that (in **BMessageCell.m**):

The `position` is set with the parsed `bMessagePos` value of `message.messagePosition`, which turns out to be `nil`.

Looking at the enum:
`bMessagePosFirst & bMessagePosLast` == `0x1 & 0x2` == `0` == `nil`

That is why `position` becomes `bMessagePosMiddle`. Because `nil` is equal to `bMessagePosMiddle`'s value (0 or nil).

Therefore, the condition `position & BChatSDK.config.showMessageAvatarAtPosition` fails.

**Comment by failynsedik** [comment]
Since I lack time, I just added a flag to show the users' profile picture on every cell. https://github.com/failynsedik/chat-sdk-ios/commit/767bae8a85bb728d92d95cba486c102611e36817

**Comment by brunomartinez16** [comment]
That could be a good solution, but i don't want to show profile picture on every cell, so i end up overriding bchatviewcontroller and created my custom cell. This is not escalable at all, so hope they will fix this soon.

**Comment by vijay2102** [comment]
Can any one tell me how I can set the gradient color on the bubble

**Comment by bensmiley** [comment]
This issue is fixed in the latest version.

**Comment by vijay2102** [comment]
But on update the chat I get error on the  BChatSDK.shared.networkAdapter.socialLogin = [[BFirebaseSocialLoginHandler alloc] init];

And their are more related to the socialLogin.

**Comment by bensmiley** [comment]
Social login has been removed in this version. I would recommend that you use Firebase UI instead.
