### ISSUE TITLE
[XMPP ChatSDK] Replying to ejabberd welcome message crashes app

### ISSUE THREAD

**Issue by simonsmiley64** [chat-sdk/chat-sdk-ios#4]
If I reply to the ejabberd welcome message in the XMPP messaging framework for iOS the app crashes.

**Comment by simonsmiley64** [comment]
We seem to be able to fix the issue by adding a check on the entityID of the message. This problem seems to be occurring due to the ejabberd message not being a message created and sent on the server, if we only return if the message has an entityID then the crash doesn't occur:

`-(NSMutableDictionary *) infoForMessage: (id<PMessage>) message {
    // Have we already seen this message?
    NSMutableDictionary * messageInfo = _messageInfo[message.entityID];
    if(!messageInfo && message.entityID) {
        messageInfo = [NSMutableDictionary new];
        _messageInfo[message.entityID] = messageInfo;
    }
    return messageInfo;
}`

**Comment by bensmiley** [comment]
Fixed in latest version.
