### ISSUE TITLE
Show foreground push banner on message receive

### ISSUE THREAD

**Issue by somanas** [chat-sdk/chat-sdk-ios#404]
Have someone faced this issue related to getting messages in the foreground and show the banner. Is there something I am missing. where to find the method to receive messages to show the banner on message received.

**Comment by glennposadas** [comment]
Have you setup your Firebase functions ?(this is necessary for push notifications - it listens to your firebase realtime db). Also I'm thinking you can create a local push manually for foreground each time you receives a message (Even outside the chat screen). Hope it helps.

**Comment by somanas** [comment]
I have set up the firebase functions correctly, receiving a push in the background and terminated case. 

Yes I want to exactly same thing, i.e creating a local push when receiving a message. Is there some method that I can override in my custom handler to listen to message received events.
