### ISSUE TITLE
Can we get SDWebImage dependency fixed?

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#41]
Still trying to get a build. Though I have been examining the code and docs a lot because of these struggles. Anyway in the ChatSDKUI.podspec I think it needs to be:

s.dependency 'SDWebImage', '~> 3.0'
  s.dependency 'SDWebImage-ProgressView', '~> 0.4'

JUST:
  s.dependency 'SDWebImage', '~> 4.0'

I didn't see SDWebImage-ProgressView being used in the code.

**Comment by bensmiley** [comment]
Fixed in de06e8e.
