### ISSUE TITLE
Search user is not working

### ISSUE THREAD

**Issue by 3r1k83** [chat-sdk/chat-sdk-ios#415]
I downloaded the last version, and installed. I did the setup in my firebase project.
The chat is working good, but I cannot find any contact. When I try to search or add a user I cannot find anything, and the method usersForIndexes in BFirebaseSearchHandler is never called during the search.
![Simulator Screen Shot - iPhone 11 - 2019-12-09 at 12 18 00](https://user-images.githubusercontent.com/1701567/70466816-49113c80-1ac4-11ea-80ee-e8560af3a9d3.png)

**Comment by bensmiley** [comment]
You need to add the users to your contact list first by clicking the contact tab, + button, searching. Also make sure you've added the rules.

**Comment by 3r1k83** [comment]
Thanks for reply. Yes I'm doing as you say, adding the users clicking on + but for some strange reason I cannot find all contacts that are present in my db. It worked good only for one contact. Maybe there is some problem in my firebase db. Everything is working good in android version.
