### ISSUE TITLE
Custom Authentication

### ISSUE THREAD

**Issue by ganico** [chat-sdk/chat-sdk-ios#416]
1. **Is the bug present in the demo Chat SDK project?**
not possible to replicate there since the authentication is customized

2. **What modifications have you made to the Chat SDK?**
none, so far yet

3. **iOS Version? Device or simulator?**
not a version nor hardware issue, im pretty sure

4. **Steps taken to reproduce the problem:**
just check the screenshot that I attached, copy that code snippet

5. **Expected result:**
it should atleast fall in error callback right?

6. **Actual result:**
no response, so I'm not sure how to handle it.

7. **Comments:**
since the type is 0 which is not included in "bAccountType" so that's why it lands at the switch default which is an empty promise I think? so my main point is how do you or should we handle it? Just in case we need to and I think we need :)

![Screen Shot 2019-12-11 at 10 25 18](https://user-images.githubusercontent.com/7714293/70586160-55e77a80-1c01-11ea-8b7b-a75d8e323388.png)

**Comment by sgiraldog** [comment]
Hi, have you solved it?

I’m having the same issue

**Comment by bensmiley** [comment]
You are setting the type to a value that doesn't exist... Technically, it should return failure... But it's a bit contrived, you would only run in to this issue by intentionally doing the wrong thing...
