### ISSUE TITLE
failed: permission_denied

### ISSUE THREAD

**Issue by karthiKarthiP** [chat-sdk/chat-sdk-ios#417]
1. **Is the bug present in the demo Chat SDK project?**

2. **What modifications have you made to the Chat SDK?**

3. **iOS Version? Device or simulator?**

4. **Steps taken to reproduce the problem:**

5. **Expected result:**

6. **Actual result:**

7. **Comments:**

**Comment by karthiKarthiP** [comment]
what is root path? where can i add root path?

**Comment by bensmiley** [comment]
You need to update the security rules
