### ISSUE TITLE
how can I update username in CDUser entity in meta attribute from firebase?

### ISSUE THREAD

**Issue by shalkovy** [chat-sdk/chat-sdk-ios#423]
one of my users, who use chat sdk, change name on firebase. how can I update data in core data and show new username in chat?

**Comment by bensmiley** [comment]
It should happen automatically.

**Comment by shalkovy** [comment]
> It should happen automatically.

new username shows only after deleting and reinstalling the app. but if I change the name in firebase, pushs show right (updated) username, in chat in app shows the old one

**Comment by bensmiley** [comment]
Fixed in latest version.
