### ISSUE TITLE
MBProgressHUD is causing trouble

### ISSUE THREAD

**Issue by hamza-faroooq** [chat-sdk/chat-sdk-ios#431]
Hello,

I have just added the pods in my project as follows

pod "ChatSDK"
pod "ChatSDKFirebase/Adapter"
pod "ChatSDKFirebase/FileStorage"
pod "ChatSDKFirebase/Push"

with them "MBProgressHUD" is also installed which is giving me three errors in "MBProgressHUD.m" file:

1. No known class method for selector 'labelColor'
2. Use of undeclared identifier 'UIActivityIndicatorViewStyleLarge'
3. Use of undeclared identifier 'UIBlurEffectStyleSystemThickMaterial'

I am currently using Xcode version 10.2 and swift version 4

Need Help

Thank You in advance.

**Comment by bensmiley** [comment]
Chat SDK can only support iOS 11 and up.
