### ISSUE TITLE
Please update AFNetworking once it removes UIWebView+AFNetworking

### ISSUE THREAD

**Issue by failynsedik** [chat-sdk/chat-sdk-ios#435]
Apple will stop accepting submissions of existing App Store apps on December 2020 if the app uses UIWebView.

> App Store Connect
> Dear Developer,
> 
> We identified one or more issues with a recent delivery for your app. Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of app updates that use UIWebView APIs starting from December 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.
> 
> After you’ve corrected the issues, you can upload a new binary to App Store Connect.
> 
> Best regards,
> The App Store Team

Thank you.

**Comment by bensmiley** [comment]
This has already been fixed in the github repository and it will be available on Cocopods when we update next.

**Comment by ganico** [comment]
> This has already been fixed in the github repository and it will be available on Cocopods when we update next.

what version release is the fixed included?
