### ISSUE TITLE
partial apply forwarder for reabstraction

### ISSUE THREAD

**Issue by SamQuest** [chat-sdk/chat-sdk-ios#437]
1. **Is the bug present in the demo Chat SDK project?**
Can be fixed by changing code in sdk

2. **What modifications have you made to the Chat SDK?**
none

3. **iOS Version? Device or simulator?**
version does not matter

4. **Steps taken to reproduce the problem:**
create a swift application
add sdk in pods
use the following code
```

let details = BAccountDetails()
details.username = "test@example.com"
details.password = "MostSecretPassword!007"
let block = BChatSDK.auth()?.authenticate(details)?.thenOnMain
_ = block!({(result: Any?) -> Any? in
            
    return result
}, {(error: Error?) -> Any? in
            
    return error
})
```

5. **Expected result:**
should get result or exception

6. **Actual result:**
crashes silently and nothing is returned

7. **Comments:**
i found something related
https://stackoverflow.com/questions/47209733/swift-closure-partial-apply-forwarder

**Comment by bensmiley** [comment]
I tested this and you can use:

```
BChatSDK.auth()?.authenticate()?.thenOnMain({ result in
        return nil
}, { error in
       return nil
})
```

I don't get a crash.

**Comment by SamQuest** [comment]
I am still struggling with this.
the problem is (as mentioned in the link), when something **crashes** in background (in ObjectiveC) the error is not propagated up to SWIFT.

in my case it may have to do with the following code

```

let config = BConfiguration.init()
config.firebaseGoogleServicesPlistName = App.googleServiceInfo
config.firebaseShouldConfigureAutomatically = true
config.rootPath = "my_chat_debug"
config.allowUsersToCreatePublicChats = false

BChatSDK.initialize(config, app: application, options: launchOptions)

```

i am having two targets and they have two different firebase-info-plist

**Comment by SamQuest** [comment]
the real reason was this missing type

`details.type = bAccountTypeUsername`

adding type to BAccountDetails made the events fire properly.
