### ISSUE TITLE
Please update AFNetworking - AppStore is rejecting uploads

### ISSUE THREAD

**Issue by SamQuest** [chat-sdk/chat-sdk-ios#443]
1. **Is the bug present in the demo Chat SDK project?**
NO
2. **What modifications have you made to the Chat SDK?**
NONE
3. **iOS Version? Device or simulator?**
NA
4. **Steps taken to reproduce the problem:**
Just add ChatSdk and submit to AppStore
5. **Expected result:**
AppStore upload should not fail
6. **Actual result:**
AppStore upload fails
`ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview). `
7. **Comments:**
Please update AFNetworking

**Comment by bensmiley** [comment]
What warning is it giving? Which version of the Chat SDK are you using?

**Comment by SamQuest** [comment]
> What warning is it giving? Which version of the Chat SDK are you using?

added error info.
now I'm updating my pods will let you know

AFNetworking recently updated please check this also https://github.com/AFNetworking/AFNetworking/issues/4468

**Comment by SamQuest** [comment]
Should've updated the pods first!

The latest release indeed works.

Thanks.
