### ISSUE TITLE
Overlapping user name & time text in last chat message in group chat

### ISSUE THREAD

**Issue by vipul8989** [chat-sdk/chat-sdk-ios#447]
I have integrate chat SDK 4.11.11 in my app using swift 5 & Xcode 11.3.1. when I get multiple messages from any group member at that time I’m facing text overlapping issue.
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-06-03 at 16 46 25](https://user-images.githubusercontent.com/34209058/83631676-865e0f00-a5bb-11ea-870e-95a8f213428e.png)

**Comment by bensmiley** [comment]
It looks like you've customized the ChatViewController. Do you see this with the customized view?

**Comment by vipul8989** [comment]
Right, got it. thank you.
