### ISSUE TITLE
Emoticons Doesn't Display Properly

### ISSUE THREAD

**Issue by ganico** [chat-sdk/chat-sdk-ios#448]
1. **Is the bug present in the demo Chat SDK project?**
yes
2. **What modifications have you made to the Chat SDK?**
no
3. **iOS Version? Device or simulator?**
device
4. **Steps taken to reproduce the problem:**
send 5 or more emoticons
5. **Expected result:**
emoticons are displayed completely
6. **Actual result:**
the last emoticon is missing
7. **Comments:**
any suggestion how to expand the message display, I tried updating some codes & also xib but no luck on that. Hopefully you have idea about this, thanks.

**Comment by ganico** [comment]
@bensmiley any idea about this?

**Comment by bensmiley** [comment]
![IMG_77291ED13E48-1](https://user-images.githubusercontent.com/5514010/85721843-04609200-b6f2-11ea-8767-34ebb0c4275a.jpeg)

For me it works just fine.

**Comment by ganico** [comment]
Here’s sample images, it’s actually weird 😅

![image](https://user-images.githubusercontent.com/7714293/85743065-54f9de80-b736-11ea-8834-f47e9e31554a.png)
![image](https://user-images.githubusercontent.com/7714293/85743111-5d521980-b736-11ea-8014-a78a8d4b8f61.png)
![image](https://user-images.githubusercontent.com/7714293/85743128-60e5a080-b736-11ea-8504-e608f5ad878a.png)
![image](https://user-images.githubusercontent.com/7714293/85743146-63e09100-b736-11ea-8ac0-55776fc71541.png)

**Comment by bensmiley** [comment]
I'm closing because I can't replicate this issue.
