### ISSUE TITLE
Symbol not found: _OBJC_CLASS_$_Reachability

### ISSUE THREAD

**Issue by markgravity** [chat-sdk/chat-sdk-ios#449]
1. **Is the bug present in the demo Chat SDK project?**
No
2. **What modifications have you made to the Chat SDK?**
No
3. **iOS Version? Device or simulator?**
13.5 - Simulator
4. **Steps taken to reproduce the problem:**
- Update pod following
```
  pod "ChatSDK"
  pod "ChatSDKFirebase/Adapter"
  pod "ChatSDKFirebase/FileStorage"
  pod "ChatSDKFirebase/Push"
  pod "ChatSDKFirebase/SocialLogin
```
- Build
- App run and got crash
5. **Expected result:**
Run normally
6. **Actual result:**
Crash with log:
```
dyld: dyld cache load error: shared cache file open() failed
dyld: Symbol not found: _OBJC_CLASS_$_Reachability
  Referenced from: xxx.app/Frameworks/ChatSDK.framework/ChatSDK
  Expected in: xxx.app/Frameworks/Reachability.framework/Reachability
 in xxx.app/Frameworks/ChatSDK.framework/ChatSDK
```
7. **Comments:**

**Comment by bensmiley** [comment]
@markgravity Can you make sure you have `use_frameworks!` in your Podfile. I would also recommend that you remove the line:

```
pod "ChatSDKFirebase/SocialLogin"
```

We've removed the social login functionality in favour of using FirebaseUI.

**Comment by markgravity** [comment]
@bensmiley hi, here i my pod file
```
platform :ios, '13.0'

target 'xxx' do
  use_frameworks!
  inhibit_all_warnings!
  
  ...
  pod "ChatSDKFirebase/Adapter"
  pod "ChatSDKFirebase/FileStorage"
  pod "ChatSDKFirebase/Push"
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
        end
    end
  end
end 
```

I also removed `pod "ChatSDKFirebase/SocialLogin`, but still got the same error. I also tried with Example project but got build error cause it's out of update with dependencies framework.

**Comment by bensmiley** [comment]
@markgravity I've updated the pod example project. You can see it here:

https://github.com/chat-sdk/chat-sdk-ios/tree/master/XcodePodExample

This is the podfile:

```
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'ChatSDKSwift' do

  pod "ChatSDK"
  pod "ChatSDKFirebase/Adapter"
  pod "ChatSDKFirebase/FileStorage"
  pod "ChatSDKFirebase/Push"
  
end
```

I tested it just now and it worked. I don't know, do you need to have `use_frameworks!` outside of the target loop? If you still get issues, I would recommend going through these steps:

https://hackmd.io/Os5rak3iTZCQ6UcogjWT6g#Missing-Header-Files---SomeHeaderFileh-could-not-be-found

**Comment by markgravity** [comment]
Found the problem. It's conflicted with one of my frameworks.
Thank you for your support

**Comment by petrykDima** [comment]
@markgravity I have the same issue =( 
Which framework was broken ?
