### ISSUE TITLE
How to set the background colors?

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#45]
So my app instantiates everything using BAppTabBarController with my own views in there and it is working fine. Now, how do I change the tab bar color, etc? Thanks.

**Comment by CalvinTp** [comment]
You can change the color of the tab bar through the following method:

Goto the file:
/ChatSDK/ChatSDKUI/Classes/Components/View Controllers/BAppTabBarController.m

Inside viewDidLoad, change the Tab Bar color into blue for example: 
[[UITabBar appearance] setBarTintColor:[UIColor blueColor]];

Thanks,
Calvin

**Comment by jimijon** [comment]
Realized i just needed to do it globally in the app delegate. I will as long as possible without changing the underlying sdk code. Need to get a handle on the handlers.

**Comment by jimijon** [comment]
closed.
