### ISSUE TITLE
Unread messages in public rooms appears again after app start

### ISSUE THREAD

**Issue by tcordoba85** [chat-sdk/chat-sdk-ios#451]
1. **Is the bug present in the demo Chat SDK project?**
Not sure, I cannot run the demo because of xCode version.

2. **What modifications have you made to the Chat SDK?**
None

3. **iOS Version? Device or simulator?**
iOS 13.5
Simulator iPhone 11

4. **Steps taken to reproduce the problem:**
Open chats: public rooms, if you have new messages the badge appears on the right side, if you open the room and go back the badge it's gone. If you restart the app the badge appears again.

5. **Expected result:**
After new start the app if the room was viewed should remove the badge of new messages.

**Comment by bensmiley** [comment]
@tcordoba85 when you restart the app, are you killing it with Xcode or dismissing it through the iOS UI? If it's the former, the app won't save any information so the badge will be reset. To stop this, press the home button / minimise the app before killing it with Xcode and see if the issue persists.

**Comment by tcordoba85** [comment]
Hi @bensmiley, thanks for the fast answer. 
Yeah, that was it. Sorry for the dummy issue-creation. 
You can close this. 

Thanks again

**Comment by bensmiley** [comment]
No problem, I'm glad it's ok!
