### ISSUE TITLE
how to call Login methods to Existing project?

### ISSUE THREAD

**Issue by bnagarjuna** [chat-sdk/chat-sdk-ios#46]
how to call Login methods to Existing project for custom login.

**Comment by simonsmiley64** [comment]
Hi @bnagarjuna,

Currently the Chat SDK has a UITabBar as its main view. We then check the authentication of the user and raise the LoginView if they are not authenticated. 

If you want to link the  Chat SDK with an existing project I would recommend custom authentication. If your app already have a login flow then you can link users in and authenticate them with their custom profile. This would link naturally into your login flow.

If you could provide me with more information on how your app is currently set up and where you are trying to link in the login methods I can give you more detailed advice.

Simon

**Comment by bnagarjuna** [comment]
Hi Simon,

I want to register in backgroud without chat SDK UI. How to call register and login methods to my project viewcontroller. Thanks in advance.

**Comment by simonsmiley64** [comment]
Hi @bnagarjuna,

Just to confirm, do you have a current login flow you want to link the login with? 

Simon

**Comment by bnagarjuna** [comment]
Hi simon,

Yes i want another login flow. how to link with that.

**Comment by simonsmiley64** [comment]
Hi @bnagarjuna,

For custom login with the Chat SDK you will need to set up a custom server. You can then pass this server your login details and it will then return a custom token for Firebase login. When you logout in your app you need to ensure that you log the user out. 

I would recommend you checkout this [link](https://firebase.google.com/docs/auth/ios/custom-auth). It is some of the Firebase documentation talking about how to link your custom token with the Firebase flow. 

If you need assistance setting up your custom authentication server or linking this in with your app we can offer some priority service which we would need to put together a quote for. 

If you want further information on this you can get in touch with us at team@chatsdk.co and we'll be happy to help.

Simon

**Comment by bensmiley** [comment]
Also, I'd recommend looking at the documentation [here](https://github.com/chat-sdk/chat-sdk-ios#integrating-the-chat-sdk-with-an-existing-login-system). It covers exactly what you're trying to do.
