### ISSUE TITLE
Duplicate member '_isAuthenticatedThisSession'

### ISSUE THREAD

**Issue by AntonijoDev** [chat-sdk/chat-sdk-ios#466]
1. **Is the bug present in the demo Chat SDK project?**
NO

2. **What modifications have you made to the Chat SDK?**
NONE

3. **iOS Version? Device or simulator?**
Simulator iPhone 12 PRO, iOS 14 

4. **Steps taken to reproduce the problem:**
pod update / pod install (no matter witch)
Build project

5. **Expected result:**
successful build

6. **Actual result:**
Duplicate member '_isAuthenticatedThisSession'

7. **Comments:**
When I inspect master branch on remote the error is not there, I mean there is no duplicate member defined in BFirebaseAuthenticationHandler

Podfile: 

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

target 'ChatSDK test project' do
  # Pods for ChatSDK test project
  pod "ChatSDK"
  pod "ChatSDKFirebase/Adapter"
  pod "ChatSDKFirebase/FileStorage"
  pod "ChatSDKFirebase/Push"

end

**Comment by bensmiley** [comment]
I've updated the sample project and test it, it's compiling fine:

https://github.com/chat-sdk/chat-sdk-ios/tree/master/XcodePodExample

Make sure you are using version 4.15.8 and that you have set the correct iOS Deployment target. If you still find a problem you can reopen the issue.
