### ISSUE TITLE
Location message not showing on ANDROID

### ISSUE THREAD

**Issue by RamsesArriaga** [chat-sdk/chat-sdk-ios#467]
1. **Is the bug present in the demo Chat SDK project?**
Not available on demo (Location)

2. **What modifications have you made to the Chat SDK?**
UI Modifications only

3. **iOS Version? Device or simulator?**
Device on iOS14

4. **Steps taken to reproduce the problem:**
Send Location to an Android device on a configured chat room

5. **Expected result:**Location thumbnail to be shown and location opening on Google Maps

6. **Actual result:**Thumbnail nos showing properly

7. **Comments:**ChatSDK Version 4.15.9

**Comment by bensmiley** [comment]
This will be fixed in iOS 5.0.1 when it's released.
