### ISSUE TITLE
Is there any doc on how to include ChatSDK into a react-native project? Seems very complicated.

### ISSUE THREAD

**Issue by xwas1** [chat-sdk/chat-sdk-ios#468]
1. **Is the bug present in the demo Chat SDK project?**

2. **What modifications have you made to the Chat SDK?**

3. **iOS Version? Device or simulator?**

4. **Steps taken to reproduce the problem:**

5. **Expected result:**

6. **Actual result:**

7. **Comments:**

**Comment by bensmiley** [comment]
@xwas1 I'm afraid this isn't supported currently.
