### ISSUE TITLE
Putting an Invite in a Chat or how to add a button in chat window?

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#47]
Is there already an invite feature I don't see? 

What is the best way to modify the chat window to have an invite button say in the nav bar?

Should I directly modify BChatViewController?

**Comment by simonsmiley64** [comment]
Hi @jimijon,

Can you give us a bit more detail into the exact functionality you are trying to achieve? What are you trying to invite people to?

We always recommend not directly changing the Chat SDK views but instead subclassing them and adding your new functionality to that, this then means that you can always merge new features from the Chat SDK project without getting any issues.

If you are just looking to add a new button in the navigation bar then just subclass the BChatViewController2 and then add your new button in the viewDidLoad code, this should overwrite the previous buttons.

Simon

**Comment by jimijon** [comment]
Thanks. I figured that. I am using Firebase invite to invite users to use the app, etc.  I didn't see an invite feature in the code.
