### ISSUE TITLE
Issues with M1?

### ISSUE THREAD

**Issue by harleyseoul** [chat-sdk/chat-sdk-ios#472]
Sorry I'm new to this, just want to make sure all the functions work with M1 Mac since I was getting these errors?

This happened when I opened .project(I probably shouldn't do this)
Showing Recent Errors Only
/Users/harleyseoul/Desktop/Developer files/chat-sdk-ios/XcodeSwift/Pods/Target Support Files/Pods-ChatSDKSwift/Pods-ChatSDKSwift.debug.xcconfig: unable to open file (in target "ChatSDKSwift" in project "ChatSDKSwift")

/Users/harleyseoul/Desktop/Developer files/chat-sdk-ios/XcodeSwift/Pods/Target Support Files/Pods-ChatSDKSwift/Pods-ChatSDKSwift.debug.xcconfig: unable to open file (in target "ChatSDKSwift" in project "ChatSDKSwift")

/Users/harleyseoul/Desktop/Developer files/chat-sdk-ios/XcodeSwift/Pods/Target Support Files/Pods-ChatSDKSwift/Pods-ChatSDKSwift.debug.xcconfig: unable to open file (in target "ChatSDKSwift" in project "ChatSDKSwift")

/Users/harleyseoul/Desktop/Developer files/chat-sdk-ios/XcodeSwift/Pods/Target Support Files/Pods-ChatSDKSwift/Pods-ChatSDKSwift.debug.xcconfig: unable to open file (in target "ChatSDKSwift" in project "ChatSDKSwift")

<img width="1440" alt="Screen Shot 2021-04-11 at 11 33 11 pm" src="https://user-images.githubusercontent.com/76761198/114310727-5a39e580-9b1e-11eb-9a30-86d1f498b1d7.png">
The attached are the errors occurred when open .workspace

**Comment by bensmiley** [comment]
Did you run pod install?

**Comment by harleyseoul** [comment]
Hi, Ben

Thanks for replying. Was there a separated process to run the pod installation? I run the pod files(as attached) but that doesn’t seem right.

**Comment by bensmiley** [comment]
The process is just standard. In the directory of the pod file, in the terminal run `pod install`. Can you send me the output of that command? Then open the xcworkspace file. Those warnings you have don't seem to be related to M1. It seems like none of the pod dependencies have been added.

**Comment by harleyseoul** [comment]
Hi, Ben

Sorry for the late reply. I tried to run the ‘Podfile’, got the attached screen.
