### ISSUE TITLE
Issue regarding thread's unread counts

### ISSUE THREAD

**Issue by chintanMaisuriya** [chat-sdk/chat-sdk-ios#475]
1. **Is the bug present in the demo Chat SDK project?**
- Yes

2. **What modifications have you made to the Chat SDK?**
- No

3. **iOS Version? Device or simulator?**
- iOS 14.4, Simulator 8

4. **Steps taken to reproduce the problem:**
- I found that when a user received a new message the unread count appears in the thread view controller. Once a user will read all the chat the count will disappear. But when the user reopens the app the counts will be still visible for the same thread.

5. **Expected result:**
- If a user already read the chats then no unread count should be visible to the user

6. **Actual result:**
- Unread count is still visible to the user if they already read the chat

**Comment by CaioMarastoni-Triibo** [comment]
I am having the same problem, did you manage to find a solution?

**Comment by chintanMaisuriya** [comment]
Not yet

**Comment by chintanMaisuriya** [comment]
> I am having the same problem, did you manage to find a solution?

Not yet. If you find, please share over here

**Comment by bensmiley** [comment]
This issue has been fixed and will be available in the next release.

**Comment by chintanMaisuriya** [comment]
Okay, Thank you
