### ISSUE TITLE
BChatSDK.hook().add crash

### ISSUE THREAD

**Issue by N0t2Day** [chat-sdk/chat-sdk-ios#476]
1. **Is the bug present in the demo Chat SDK project?**
Can't download demo project cz error 404 on link.
2. **What modifications have you made to the Chat SDK?**
Crash inside CharSDK pod
3. **iOS Version? Device or simulator?**
iOS 14.6
4. **Steps taken to reproduce the problem:**
<img width="1135" alt="Снимок экрана 2021-06-11 в 09 41 24" src="https://user-images.githubusercontent.com/23290834/121642472-3e5cac80-ca99-11eb-9b84-cc78f7c66261.png">

Just run
5. **Expected result:**
Crash on add hook

```
    public override init() {
        super.init()
        BChatSDK.hook().add(BHook.init(_: { [weak self] dict in
            if let id = dict?[bHook_StringId] as? String, let value = dict?[bHook_ObjectValue] {
                if let boolValue = value as? Bool {
                    self?.setValue(bool: boolValue, key: id)
                }
                if let stringValue = value as? String {
                    self?.setValue(string: stringValue, key: id)
                }
            }
        }, weight: -1000), withName: bHookSettingsUpdated)
    }
```

6. **Actual result:**
Success run
7. **Comments:**
Please fix

**Comment by bensmiley** [comment]
For the time being, can you use this tag: 

https://github.com/chat-sdk/chat-sdk-ios/releases/tag/5.0.1

I'll look at the issue with the main branch.

**Comment by bensmiley** [comment]
I can't reproduce this... can you download and test the default project?
