### ISSUE TITLE
iOS show private thread directly

### ISSUE THREAD

**Issue by szoszig** [chat-sdk/chat-sdk-ios#480]
Is it possible to show directly a private thread on iOS?
In my app the user is already logged in firebase.
It looks like if I do not present the splashviewcontroller, I cannot fetch the threads (the users or anything else but auth says I am authenticated), but if i present it once, it works like a charm (even after app restart).
But if I present splash it will navigate to an unnecessary screen (main).

Any idea?
Thx

**Comment by AJITHAS-842** [comment]
how you resolved this?
