### ISSUE TITLE
I can't start new Conversation. How we detect the existing user in our firebase

### ISSUE THREAD

**Issue by AJITHAS-842** [chat-sdk/chat-sdk-ios#481]
1. **Is the bug present in the demo Chat SDK project?**

2. **What modifications have you made to the Chat SDK?**

3. **iOS Version? Device or simulator?**

4. **Steps taken to reproduce the problem:**

5. **Expected result:**

6. **Actual result:**

7. **Comments:**

**Comment by bensmiley** [comment]
You can click the contacts tab, +, search by name, phone number or email.

**Comment by AJITHAS-842** [comment]
Actually i set up a new firebase account and integrate that, then there i
can't search my existing users list
