### ISSUE TITLE
[Firebase/Database][I-RDB038008] onDisconnectSetValue: or onDisconnectRemoveValue: at /test/users/NIOWTisUHGXnTtfYsSYt901R4KD2/online failed: permission_denied. Showing This message in log

### ISSUE THREAD

**Issue by AJITHAS-842** [chat-sdk/chat-sdk-ios#483]
1. **Is the bug present in the demo Chat SDK project?**

2. **What modifications have you made to the Chat SDK?**

3. **iOS Version? Device or simulator?**

4. **Steps taken to reproduce the problem:**

5. **Expected result:**

6. **Actual result:**

7. **Comments:**

**Comment by bensmiley** [comment]
When you encounter so many issues, it's probably because you have not configured the project correctly. Please try the demo version of the app and see if it works... If it does, it suggests your setup is not correct. i.e. this issue looks like your Firebase rules are not correct.
