### ISSUE TITLE
I need to customise the chat tab into our own UI design. Is it possible ? I need to list all the users in the firebase as contacts in the chat app without searching for each single user . Is that possible ? I don't need to edit the user profile.At the time of my customisation-login itself the current user needs to be registered in the firebase and start a new chat. Is that possible ?

### ISSUE THREAD

**Issue by AJITHAS-842** [chat-sdk/chat-sdk-ios#484]
1. **Is the bug present in the demo Chat SDK project?**

2. **What modifications have you made to the Chat SDK?**

3. **iOS Version? Device or simulator?**

4. **Steps taken to reproduce the problem:**

5. **Expected result:**

6. **Actual result:**

7. **Comments:**

**Comment by bensmiley** [comment]
Don't write the issue in title, use the issue template.
