### ISSUE TITLE
Is there any possible way for the changing email for the particular user in chatSDK

### ISSUE THREAD

**Issue by ajithSoft** [chat-sdk/chat-sdk-ios#486]
1. **Is the bug present in the demo Chat SDK project?**

2. **What modifications have you made to the Chat SDK?**

3. **iOS Version? Device or simulator?**

4. **Steps taken to reproduce the problem:**

5. **Expected result:**

6. **Actual result:**

7. **Comments:**

**Comment by bensmiley** [comment]
That is not supported.
