### ISSUE TITLE
The unread message counter on the privateThreadsViewController cell not really reset.Its reset just on UI. How to reproduce So once you get in to chat some chat with unread messages and go back you will see that counter reset but if you close and reopen the app the counter will be there againa.

### ISSUE THREAD

**Issue by ajithSoft** [chat-sdk/chat-sdk-ios#487]
1. **Is the bug present in the demo Chat SDK project?**

2. **What modifications have you made to the Chat SDK?**

3. **iOS Version? Device or simulator?**

4. **Steps taken to reproduce the problem:**

5. **Expected result:**

6. **Actual result:**

7. **Comments:**

**Comment by bensmiley** [comment]
Don't write the issue in the title, please fill out the issue template.
