### ISSUE TITLE
The Read Message Count is not Updated after apps kills and reopen

### ISSUE THREAD

**Issue by ajithSoft** [chat-sdk/chat-sdk-ios#488]
The unread message counter on the privateThreadsViewController cell not really reset.Its reset just on UI. How to reproduce So once you get in to chat some chat with unread messages and go back you will see that counter reset but if you close and reopen the app the counter will be there againa

**Comment by bensmiley** [comment]
If you kill the app from Xcode it will not save the data to the database. So dismiss the app using the phone UI. If you need unread counts when the app is uninstalled, then use the read receipts module.
