### ISSUE TITLE
Uploading file using the sdk missing document

### ISSUE THREAD

**Issue by ahmadrushdie** [chat-sdk/chat-sdk-ios#489]
i am trying to upload file after seclect from UIDocumentPickerViewController 
the picker return list of URL so i take the url and i am trying to convert it to  [AnyHashable : Any] in order to accept by sendMessage  any recommendation about which data should i pass in dectionary 

   BChatSDK.fileMessage()?.sendMessage(withFile:[AnyHashable : Any] , andThreadEntityID: threadEnitty).then({ result in
            
            DispatchQueue.main.async {
                self.loadChatMessages()
            }
            
        }, { error in
            if let error = error {
            }
            return nil
        })
    }

**Comment by bensmiley** [comment]
Is this a bug?

**Comment by ahmadrushdie** [comment]
for me Yes because the poor documentation of the SDK 
 BChatSDK.fileMessage()?.sendMessage ask for Dectionary and i didnt fine any documentation about which data sould i pass inside dectionary

**Comment by ahmadrushdie** [comment]
@bensmiley i update the description the issue that i am unable to figure which data should be pass to sendMessage for file

**Comment by bensmiley** [comment]
This method isn't documented because it's a semi-private API. But if you want to send your own file, you can do it like this: 

```
    NSURL * localURL = file[bFilePath];
    NSData * data = file[bFileData];
    NSString * fileName = file[bFileName];
    NSString * mimeType = file[bFileMimeType];
```
Here are the keys you need to set. 

You will also need the FileMessageModule to be enabled.

**Comment by ahmadrushdie** [comment]
i already buy the file message module but where i can find the pod for the module?

**Comment by bensmiley** [comment]
Can you email me your license confirmation or tell me the email address you used to buy it? to: team [at] sdk.chat
