### ISSUE TITLE
iOS chat SDK set message read inside thread

### ISSUE THREAD

**Issue by ahmadrushdie** [chat-sdk/chat-sdk-ios#490]
for Android we have ChatSDK.readReceipts().markRead(msg)
but for iOS we have  BChatSDK.readReceipt()?.markRead(thread)

is there any way to make spesific message read in iOS

**Comment by bensmiley** [comment]
You can do it like this: 

```
-(RXPromise *) markMessageRead: (id<PMessage>) message {
    CCMessageWrapper * wrapper = [FirebaseNetworkAdapterModule.shared.firebaseProvider messageWrapperWithModel:message];
    return [wrapper setReadStatus: bMessageReadStatusRead];
}
```

**Comment by ahmadrushdie** [comment]
@bensmiley  can you please provide me from where i can use the two methods ?

**Comment by bensmiley** [comment]
Just copy paste them into your code...

**Comment by ahmadrushdie** [comment]
@bensmiley i think we need to buy the READ RECEIPTS module in order to mark messages read by users ?

**Comment by bensmiley** [comment]
Yes, when you have that module you can use this method.
