### ISSUE TITLE
Listen to income messages in iOS 

### ISSUE THREAD

**Issue by ahmadrushdie** [chat-sdk/chat-sdk-ios#491]
i am trying to listen to incomming messages in the controller using doc 
in the documentation they mention 

```
[_notificationList add:[[NSNotificationCenter defaultCenter] addObserverForName:bNotificationMessageAdded object:Nil queue:Nil usingBlock:^(NSNotification * notification) {
    dispatch_async(dispatch_get_main_queue(), ^{
        id<PMessage> messageModel = notification.userInfo[bNotificationMessageAddedKeyMessage];
    });
**}]];
```

any complete example how to use in swift ?

**Comment by bensmiley** [comment]
This is an old method.. where did you find it? 

The current docs are here: 

https://chat-sdk.gitbook.io/chat-sdk/guides/api-cheatsheet#messaging-server-notifications

**Comment by ahmadrushdie** [comment]
@bensmiley how to achive like this on IOS 

  ChatSDK.events().sourceOnMain()
                .filter(NetworkEvent.filterType(EventType.MessageAdded))

                .filter(NetworkEvent.filterThreadEntityID(thread[0].entityID))
                .subscribe {
                    val message: Message = it.message
                    messagesAdapter.addItem(message)
                    Handler().postDelayed(Runnable {
                        binding.rcMessages.smoothScrollToPosition(messagesAdapter.messages.size + 1)
                    }, 100)
                }

Listen to income messages for spesific thread?

**Comment by bensmiley** [comment]
@ahmadrushdie it's in the same document... Look at hooks, ios. 

```
public static String MessageReceived = "MessageReceived";
```
