### ISSUE TITLE
Chat SDK for ios not adding users to firebase after login with gmail

### ISSUE THREAD

**Issue by ahmadrushdie** [chat-sdk/chat-sdk-ios#492]
i already have google login integrated in my app and i add the sdk and configure it but when i loggin using gmail there is no user added to firebase 

import ChatSDK

import ChatSDKFirebase
import FirebaseAuthUI
import FirebaseEmailAuthUI
import FirebasePhoneAuthUI
import FirebaseOAuthUI
import FirebaseGoogleAuthUI
import FirebaseFacebookAuthUI

 let config = BConfiguration.init();
                config.rootPath = "test_1"
                config.allowUsersToCreatePublicChats = false
               
                var modules = [
                    FirebaseNetworkAdapterModule.shared(),
                    FirebasePushModule.shared(),
                    FirebaseUploadModule.shared(),
                    FileMessageModule.init()
                    
                                        
                 
                    
                    // Optional...
        //            AddContactWithQRCodeModule.init(),
                ]
                
                let useFirebaseUI = true
                if useFirebaseUI {
                    let module = FirebaseUIModule.init()
                    let authUI = FUIAuth.defaultAuthUI()
                    module.setProviders([FUIEmailAuth(), FUIPhoneAuth.init(authUI: authUI!), FUIGoogleAuth(), FUIFacebookAuth()])
                    modules.append(module)
                }
        BChatSDK.initialize(config, app: application, options: launchOptions, modules: modules, networkAdapter: nil, interfaceAdapter: nil)
        
        
   
        BChatSDK.activateLicense(withEmail:"email that we subscribe using it")

**Comment by bensmiley** [comment]
Does it work with other login methods? Can you reproduce this on the demo project?

**Comment by ahmadrushdie** [comment]
not working on any one in ios 
but in Android its working fine so is there any missing ios configuration that force sending auth to firebase?
