### ISSUE TITLE
New way of changing bubble and text colors

### ISSUE THREAD

**Issue by itumeleng-mabote** [chat-sdk/chat-sdk-ios#493]
Hi
I see BConfiguration no longer has 
config.messageColorMe
config.messageColorReply
config.messageTextColorReply
config.messageTextColorMe

How should we now change these?

Thanks in advance

**Comment by bensmiley** [comment]
If you are using ChatKit: 

```
ChatKit.config().outgoingBubbleColor = ""
```
etc...
