### ISSUE TITLE
unread message counter not reset in new Device login

### ISSUE THREAD

**Issue by AJITHAS-842** [chat-sdk/chat-sdk-ios#495]
When a message is read and kills the app and reopens, the read message count is not updated.
Also when a user login and reads all the unread messages, the same user tries to log in from another device, and still, there is no change in the unread message count. the count that shows the same as that at the time of before user login and read messages in the previous device. Nothing is happening in the count.

**Comment by bensmiley** [comment]
If you kill the app data isn't persisted to the local database. Dismiss the app on the device before killing with Xcode. 

To get the correct read count on multiple devices, you need to enable the read receipts module.

**Comment by AJITHAS-842** [comment]
How we can we enable this read receipts module ? for that enabling is there any thing we need to import new module, rather that this chat sdk

**Comment by bensmiley** [comment]
There is info here:

https://chat-sdk.gitbook.io/ios/add-pro-module-frameworks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AJITHAS-842** [comment]
Is there payment available for bronze tier

**Comment by bensmiley** [comment]
Could you clarify what you mean?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AJITHAS-842** [comment]
Is there any pricing available for using this pro-modules-frameworks like the read receipts module?

**Comment by bensmiley** [comment]
The bronze tier covers it.

**Comment by AJITHAS-842** [comment]
How much price for bronze tier ?
