### ISSUE TITLE
ChatSDK Leave thread throwing error -  1. Is the bug present in the demo Chat SDK project? - Yes 2. What modifications have you made to the Chat SDK? -  Leave thread function  call 3. iOS Version? Device or simulator? - Simulator iPhone 13 pro max 4. Steps taken to reproduce the problem: call leave thread BChatSDK.thread().leave(thread) - current user to leave the thread in a group 5. Expected result: leave the group 6. Actual result: Error Domain=RXPromise Code=-1000 "" UserInfo={NSLocalizedFailureReason=} 7. Comments:

### ISSUE THREAD

**Issue by vineethsreekumar** [chat-sdk/chat-sdk-ios#496]
1. **Is the bug present in the demo Chat SDK project?**

2. **What modifications have you made to the Chat SDK?**

3. **iOS Version? Device or simulator?**

4. **Steps taken to reproduce the problem:**

5. **Expected result:**

6. **Actual result:**

7. **Comments:**

**Comment by bensmiley** [comment]
@vineethsreekumar please update the issue following the issue template. Don't put the issue in title.

**Comment by vineethsreekumar** [comment]
which template

**Comment by bensmiley** [comment]
Is the bug present in the demo Chat SDK project?

What modifications have you made to the Chat SDK?

iOS Version? Device or simulator?

Steps taken to reproduce the problem:

Expected result:

Actual result:

Comments:

**Comment by vineethsreekumar** [comment]
updated

**Comment by bensmiley** [comment]
You put the whole message in the issue title... 🤦
