### ISSUE TITLE
Converted admin can't change role

### ISSUE THREAD

**Issue by vineethsreekumar** [chat-sdk/chat-sdk-ios#499]
1. **Is the bug present in the demo Chat SDK project - yes

2. **What modifications have you made to the Chat SDK - Used chatSDK development code for changing role in group. Only owner can change role for other users in a group. If an admin changes the role it gives permission denied in both iOS and Android

3. **iOS Version? Device or simulator - iPhone 13 pro Max , Android 11 device

4. **Steps taken to reproduce the problem:** - Create a group thread. Add users. Change role of one user to admin. Login with that admin user and try to change role of another user

5. **Expected result:** Admins should be able to change roles of other members

6. **Actual result:** Permission denied

7. **Comments:** We are using chatSDK dev version in  @simonsmiley64 @bensmiley 
@ealeksandrov

**Comment by bensmiley** [comment]
@vineethsreekumar please don't tag every contributor to this project. Just report issue you will get a follow up.

**Comment by bensmiley** [comment]
I've tested this with the following steps:

1. Create a group
2. Promote user 2 to admin
3. As user 2, change role of user 3

This worked fine with the current Firebase version of the project. If you want me to investigate further, I will need to know the version you are using, the backend and maybe see a video. 

Bear in mind that I can only provide support for the latest version of the project.
