### ISSUE TITLE
My new Group Public Chat... where did my messages go?

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#51]
OK -

It seems I have everything sync'd and sort of working. Amazing! Anyway, my group chat again. When I went into it from a detail page, it dutifully created a new CHAT in Firebase! I typed myself a message. Next I went out. Then I went back in expecting so see my message, but it was empty again. Hmmm, so I checked Firebase and no new Thread was created so that part seemed to work.

So the question is... how is this supposed to work. Shouldn't a user see the the last X messages or such of the public thread?

Thanks for all the help so far.

**Comment by simonsmiley64** [comment]
Hi @jimijon,

Can you confirm whether the message was sent in Firebase? You can find the thread and then look at the last message which was sent.  

This will identify whether the problem is coming from your Firebase configuration (we're creating it on the phone and it's not getting to the database) or the connection to the phone (the message is being uploaded but then no downloaded again). 

Once we know which of these is causing the issue we can help troubleshoot why this problem is occurring on your system.

<img width="363" alt="screen shot 2017-05-10 at 09 52 09" src="https://cloud.githubusercontent.com/assets/8721425/25890688/6039558c-3566-11e7-8fb9-75b7a1f4b865.png">

A public thread should work no differently from a private one where the user can see all previous messages. 

Simon

**Comment by jimijon** [comment]
Well for one thing mine doesn't have the public-threads in the database. However it does have threads and messages:

<img width="441" alt="screen shot 2017-05-10 at 6 07 34 am" src="https://cloud.githubusercontent.com/assets/971445/25895814/2608874e-3547-11e7-866b-3f238ce77905.png">

**Comment by simonsmiley64** [comment]
And can you find the thread you are creating?

The database is realtime so the thread should show up yellow when a message is typed. Can you confirm if your messages are getting through?

**Comment by jimijon** [comment]
Here is the behavior.

1) Start a new chat by being the very first person ever to enter the room.
2) Make a posting. Stay in Chat.
Result: New thread, new users, new message in Firebase.

3) Leave Chat 
Result: Users disappears from firebase in that chat room.

4) Enter Chat
Result: Nothing shows up on screen. However, another message was added to the thread.

5) Repeat the process with a new "public chat"

Same Behavior BUT:: This new chat, when I go back into it, will display new messages on the screen.

Weird.

**Comment by simonsmiley64** [comment]
Hi @jimijon,

I would recommend you do the following:

Download a new version of the Chat SDK. The base version is fully configured to our test accounts. Load it up and test this exact functionality without making any modifications to the code. It should work as expected.

This will let us know whether the issue is one with the Chat SDK or one which has been added during your coding. This will then help us troubleshoot the right area (if it is a problem with the Chat SDK we can then fix it and push the fix).

Simon

**Comment by jimijon** [comment]
Pulled the latest version. Went to run Xcode Swift. No iOS Target or Scheme appears. can't run it.
Did you fix the Firebase issues I pointed out about the problem with ChatFirebaseAdaptor and Firebase? Because I have to edit that by hand on every upgrade. Anyway,,, this seems to be the only show stopper problem I am experiencing so far.

**Comment by jimijon** [comment]
Ok, made an iOS target and it worked. Hmm. Then I changed the hidden flag to false and they appeared. I guess I don't understand what the use of the "hidden" flag is.

**Comment by simonsmiley64** [comment]
Can you confirm which hidden flag you are referring to?

**Comment by jimijon** [comment]
let block = BNetworkManager.shared().a.publicThread().createPublicThread(withName: tile.symbol!, entityID: eID, **isHidden: false**).thenOnMain

**Comment by simonsmiley64** [comment]
Hi @jimijon,

The hidden flag is some new code we added as there are certain situations where you might want to create a public thread, have it unavailable for users to see and enter, but still behave like a public room (user added and removed from the list when they arrive and leave). 

In general it should be used for maintaining public rooms on a server and so the majority of cases the BOOL should be set to NO.

Hopefully this functionality should be working as expected now?

Sorry for the confusion and thanks for your continued patience and clearness while solving this issue :1st_place_medal: 

Simon

**Comment by bensmiley** [comment]
Just to help people in the future, this issue stems from this feature request #44. When the hidden flag is set to yes, the room will be a secret public chat. It will behave like a public chat in that when a user enters, they are added to the user list and when they leave, they are removed from the user list. But it will not be displayed in the public rooms tab of the chat.

**Comment by cesariel** [comment]
@bensmiley @simonsmiley64 How can I enter an already created PublicThread? With the entityID. Maybe a function like `enterPublicThread(entityID: id)` exists and I don't know? Thanks!

**Comment by simonsmiley64** [comment]
Hi @cesariel,

If you create a new ticket for this issue then I can look into it. This way it will help other users if they have the same problem and will also allow us not to be confused with any replies on this issue.

Simon

**Comment by bensmiley** [comment]
If you have the entity ID, you can get the thread using that:

```
id<PThread> thread = [[BStorageManager sharedManager].a fetchEntityWithID:entityID withType:bThreadEntity];
UIViewController * vc = [[BInterfaceManager sharedManager].a chatViewControllerWithThread:thread];
[self.navigationController pushViewController:vc animated:YES];
```

Assuming it already exists, you can open it as normal using the chat view controller.

**Comment by cesariel** [comment]
@bensmiley !! Perfect !! That’s exactly what I want it.

**Comment by cesariel** [comment]
@bensmiley I have another question. When I ‘pushViewController’ to my ‘ChatViewController : BAppTabBarController’ I can have a Go Back button’ but when I ‘present ViewController’ I have all the (+) Bar Items but I don’t have a Go Back Item Bar. How can I present the view controller, with a back button (Bar Item) and still have all the functionality of creating new Conversations and Creating new Public Chats? Thanks in advanded!

**Comment by bensmiley** [comment]
This is because modal views don't have a back button by default. You should add a custom `UITabBarButtonItem` with the name "cancel" and dismiss the view controller when it's pressed.

**Comment by cesariel** [comment]
@bensmiley I'm creating this, but it doesn't show up:

```
let newBackButton = UIBarButtonItem(title: "Regresar", style: UIBarButtonItemStyle.plain, target: self, action: #selector(ChatSDKViewController.back(sender:)))
        self.navigationItem.leftBarButtonItem = newBackButton
```

**Comment by bensmiley** [comment]
It looks right to me so if you're presenting the view correctly it should work. Make sure you add it in `viewDidLoad`. To help further, I'd need to look at your project directly. I'd be happy to do that if you purchase an hour of [priority support](https://chatsdk.co/support/).

**Comment by cesariel** [comment]
Thanks @bensmiley !! I appreciate very much your support and the work that your are doing !!

**Comment by Vivekmalani** [comment]
i will create private threads using NM.core().createThread(withUsers: user, threadCreated: { (error, thread) in })

But after that it will not appear in the list.

i will use syntax for getting list of threads is NM.core().threads(with: bThreadType(bThreadFilterPrivateThread.rawValue))

can someone help me why is getting this type of trouble.
