### ISSUE TITLE
Core Data mess - Does it do anything on background?

### ISSUE THREAD

**Issue by pangia** [chat-sdk/chat-sdk-ios#519]
BCoreDataStorageAdapter.m has most of its code commented out, and also calls methods that do essentially nothing. it also appears the persistentStoreCoordinator is attached to the main moc, causing excessive lag when dealing with many threads/contacts etc....

Has this core data implementation been tested / performance tested at all?

**Comment by bensmiley** [comment]
This is an open source project. I don’t get paid anything to maintain it. Rather than posting sarcastic messages complaining about why code you are using for free doesn’t conform to your expectations, why don’t you try contributing something or helping out?

**Comment by pangia** [comment]
I did pay. And I tried too many times in the Discord to get responses. But you are correct.. my comment above was unnecessary and provided no value. I apologize.

**Comment by pangia** [comment]
Closing. added no value.
