### ISSUE TITLE
Add Privacy manifest (WWDC23)

### ISSUE THREAD

**Issue by azurlake** [chat-sdk/chat-sdk-ios#521]
According to Apple, all new apps using "Privacy impacting SDK's" must be signed and include a Privacy manifest. This seems to be a requirement for new apps, according to the docs:

https://developer.apple.com/support/third-party-SDK-requirements

ChatSDK for iOS is listing the following Privacy Impacting SDKs missing the provacy manifest file:

“Frameworks/MBProgressHUD.framework/MBProgressHUD”, which includes MBProgressHUD, an SDK that was identified in the documentation as a privacy-impacting third-party SDK.

"Frameworks/RxCocoa.framework/RxCocoa”, which includes RxCocoa, an SDK that was identified in the documentation as a privacy-impacting third-party SDK.

"Frameworks/RxRelay.framework/RxRelay”, which includes RxRelay, an SDK that was identified in the documentation as a privacy-impacting third-party SDK.

"Frameworks/RxSwift.framework/RxSwift”, which includes OneSignalOutcomes, an SDK that was identified in the documentation as a privacy-impacting third-party SDK.

“Frameworks/Toast.framework/Toast”, which includes Toast, an SDK that was identified in the documentation as a privacy-impacting third-party SDK.

Could you update the above SDK dependencies and also include your own Privacy manifest?

Thank you

**Comment by juliankotrba** [comment]
@bensmiley any update about this?

**Comment by bensmiley** [comment]
It's available now: 

https://github.com/chat-sdk/chat-sdk-ios/blob/master/DemoSwift/ChatSDKSwift/PrivacyInfo.xcprivacy

**Comment by azurlake** [comment]
@bensmiley Hello Ben,

Thanks for the actions. Now we are having issues due to ChatSDK's dependencies, that also need the Privacy manifest included. Would you have some time to update all dependencies to the latest versions and publish a new release?

Thanks in advance.

Dan
