### ISSUE TITLE
Pull to refresh causes message view to scroll to bottom

### ISSUE THREAD

**Issue by bensmiley** [chat-sdk/chat-sdk-ios#53]
Open a group chat with a lot of messages. Scroll to the top. Pull to refresh. The view then scrolls down to the bottom.

**Comment by simonsmiley64** [comment]
This will be fixed with the new code stopping the user from being pulled to the bottom when a new message is received and they are not at the bottom. It is contained in [this](https://github.com/chat-sdk/chat-sdk-ios/pulls) pull request.
