### ISSUE TITLE
ChatSDKCore required BITCODE

### ISSUE THREAD

**Issue by CalvinTp** [chat-sdk/chat-sdk-ios#54]
Hi,
I just started to use the GitHub version of ChatSDK (I was previously using an older version of ChatSDK also developed by Ben and Simon). 

After running pod install and then try to compile, I face the following error:
...... ChatSDKCore/ChatSDKCore.framework/ChatSDKCore' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7. 

I am using xCode 8.1, cocoapods 1.2.1. I have tested with actual device on iOS 9 and 10 but still face the same issue.  

Anyone here facing the same issue?

Thanks,
Calvin

**Comment by CalvinTp** [comment]
Hi, 
I have managed to solve this issue and I am posting this here so anyone who faces the same issue (as me) can use the same steps as well.

Based on the error provided by Xcode, please refer to which framework are missing the BITCODE. There would be a few of them based on what I have faced. 

In Xcode, select Pods (refer to the image attached) and then for each Target (refer to the errors flagged by Xcode, for example ChatSDKCore, ChatSDKUI, etc). Goto Build Settings and then search for "Enable Bitcode". Switch No to Yes for those framework which are flagged by Xcode. 

After you have completed switching all those from No to Yes, you should have no issue compiling and running ChatSDK Demo on your device. 

![Uploading Screen Shot 2017-05-14 at 5.27.17 PM.png…]()


Thanks,
Calvin

**Comment by simonsmiley64** [comment]
It is worth noting that some projects will need bitcode enabled and some need it disabled. 

If you get any error relating to bitcode you just need to make sure the flag is correctly set in the build settings of the project.

Simon
