### ISSUE TITLE
How do i access ChatSDKFirebaseAdapter from ChatSDKUI?

### ISSUE THREAD

**Issue by RyanElliott94** [chat-sdk/chat-sdk-ios#55]
Hello, you may remember me from the Android side of things but I've finally been able to start the iOS version, however i have zero experience when it comes to ObjC and I'm struggling to get access to the firebase methods from ChatSDKUI

I need to do this because of the features i added to the android version but how?

Any help would be amazing right now!

Thanks
Ryan

**Comment by simonsmiley64** [comment]
Hi @RyanElliott94,

What Firebase methods are you trying to access?

In general if you want to access Firebase through the Chat UI you need to use the chat adapter, you can do this like so:

`[[BNetworkManager sharedManager].a`

For example you can see in the BLoginViewController.m that we then access the authenticationAdapter through it to access the Firebase functions:

```
return [[BNetworkManager sharedManager].a.auth authenticateWithDictionary:@{bLoginTypeKey: @(bAccountTypePassword),
                                                                                bLoginEmailKey: username,
                                                                                bLoginPasswordKey: password}];
```
You can access the current user with it:

`id<PUser> currentUserModel = [BNetworkManager sharedManager].a.core.currentUserModel;`

Or send messages:

```
-(RXPromise *) sendText: (NSString *) text {
    return [self handleMessageSend:[[BNetworkManager sharedManager].a.core sendMessageWithText:text
                                                                            withThreadEntityID:_thread.entityID]];
}
```

There are too many different places we use it to put them all here but hopefully this gives you an indication. If you give me more info on what you want to do I can point you in the right direction.

Simon

**Comment by RyanElliott94** [comment]
Thanks
