### ISSUE TITLE
Request to support Firebase 's newest feature "Phone Number Authentication". 

### ISSUE THREAD

**Issue by sky1234** [chat-sdk/chat-sdk-ios#56]
Firebase introduced Phone number authentication. Request to include that authentication option.

**Comment by bensmiley** [comment]
Can you post a link to the page that gives details of the page where you read about this?

**Comment by sky1234** [comment]
it is announced in today's google IO. [https://firebase.googleblog.com/2017/05/whats-new-from-firebase-at-google-io.html]
Also, it is already available in Firebase Admin console. Check Authentication -> Sign In Method. Phone number authentication is one of the options.

**Comment by CalvinTp** [comment]
wow.. interesting news!

**Comment by jimijon** [comment]
I think chat-sdk should just use FirebaseAuthUI as the authenticator. I believe it almost drops in place and will always be "progressing." Seemed easy for me to implement as my authenticator / login

**Comment by simonsmiley64** [comment]
Hi @jimijon,

We will be building this new functionality into the Chat SDK based on the current 2 factor authentication UI currently available. 

The reason we choose to build our own interfaces instead of the Firebase one is because developers often want complete control over the interface during authentication. Although Firebase has a drag and drop authentication it does not give developers control over how, when, where it works. 

Simon

**Comment by jimijon** [comment]
Seemed pretty flexible for me. Though, really, once logged in, one doesn't authenticate too often in real use.

**Comment by sky1234** [comment]
How to change the auth to use Firebase's drop in auth ..? Is there a guide/article to that?

**Comment by sky1234** [comment]
Will be very helpful if a short summary of steps is available.

**Comment by bensmiley** [comment]
We've now added easy support for the Firebase UI framework. See the guide [here](https://github.com/chat-sdk/chat-sdk-ios#firebase-ui).

**Comment by Advick** [comment]
How to retrieve only my contact list on firebase chat? can you explain or any other documentation?

**Comment by simonsmiley64** [comment]
Hi @Advick,

This comment doesn't appear to be on topic with this ticket. Do you think you could create a new ticket with more information on what you are trying to achieve and we'll see how we can help you out,

Simon

**Comment by bensmiley** [comment]
Available using Firebase UI module.
