### ISSUE TITLE
Having trouble trying to list contacts node

### ISSUE THREAD

**Issue by RyanElliott94** [chat-sdk/chat-sdk-ios#57]
Hello, back again!

So i know this isn't technically an issue as it's something i have added to the SDK but unfortunately i can't open any questions on StackOverflow!

Before i explain the problem you will need to know what I've changed. When you add a contact it normally only saves in the local database not on the server but i didn't like that so now when you add a contact, it actually adds it only to the server which means the contact will always be there! I did this on the Android version too.

So i have successfully done that however i can't figure out how to show the contacts from the node in the contacts list!

This is what i have so far... 

Trying to get the data:

     -(RXPromise *) getContacts {
    
    RXPromise * promise = [RXPromise new];
    
        // Make the query
    FIRDatabaseReference * query = [[FIRDatabaseReference usersRef] child:bContactsPath];
    // Execute the query
    [query observeSingleEventOfType:FIRDataEventTypeValue withBlock:^(FIRDataSnapshot * snapshot) {
        
        if(snapshot.value != [NSNull null]) {
            
            // Get the keys of the dictionary
            NSDictionary * dict = snapshot.value;
            
            // Only add users that match the original query
            NSArray * keys = dict.allKeys;
            NSString * resultValue;
            
            NSMutableArray * validUIDs = [NSMutableArray new];
            
            // Loop over the dictionary keys
            for (NSString * key in keys) {
                        [validUIDs addObject:key];
            }
            
            if(validUIDs.count) {
                
                NSMutableArray * userPromises = [NSMutableArray new];
                
                // Loop over the IDs and get the users
                for(NSString * entityID in validUIDs) {
                    
                    CCUserWrapper * user = [CCUserWrapper userWithEntityID:entityID];
                    [userPromises addObject:[user once].thenOnMain(^id(id<PUserWrapper> u) {
                        
                        // Call add user again to udpate the list with the
                        // correct image - only add users who have names
                    return Nil;
                    }, Nil)];
                }
                
                [RXPromise all: userPromises].then(^id(id success) {
                    [promise resolveWithResult:success];
                    return Nil;
                }, Nil);
            }
            else {
                [promise resolveWithResult:Nil];
            }
        }
        else {
            [promise resolveWithResult:Nil];
        }
    }];
    
    return promise;
    }

Trying show the data on the list:

    RXPromise * getContact = [[BNetworkManager sharedManager].a.core.currentUserModel getContacts];

    [_contacts removeAllObjects];
    [_contacts addObject:getContact];

    [self sortContacts];
    
    [tableView reloadData];

Like i said in my previous question, I'm still very new to Objective-C, about 3 days new in fact!

So yeah as always, i need the help of the professionals haha

Thanks

Ryan

**Comment by simonsmiley64** [comment]
Hi @RyanElliott94,

Depending on how you want this functionality to work you have two possible options. 

1. Check and update when you load the contacts view - this is what you are currently doing

With this technique you are looking at Firebase each time you load the view, you then update the array to show more contacts. This method is good as the contacts will not change regularly meaning there is not much point in having continuous observers - see point 2.

The code you have looks like it is on the right track, you now need to troubleshoot it to ensure that it is linking up correctly:

I have added some points below to think about and troubleshoot:

-(RXPromise *) getContacts {

RXPromise * promise = [RXPromise new];

    // Make the query
FIRDatabaseReference * query = [[FIRDatabaseReference usersRef] child:bContactsPath];
// Execute the query
[query observeSingleEventOfType:FIRDataEventTypeValue withBlock:^(FIRDataSnapshot * snapshot) {
    
// What is this returning? Are you correctly returning your contacts? If not then you need to change your reference, if so then great.

    if(snapshot.value != [NSNull null]) {
        
        // Get the keys of the dictionary
        NSDictionary * dict = snapshot.value;
        
        // Only add users that match the original query
        NSArray * keys = dict.allKeys;
        NSString * resultValue; 
        
// Do you ever use this result value? Currently it doesn't seem as if you do.

        NSMutableArray * validUIDs = [NSMutableArray new];
        
        // Loop over the dictionary keys
        for (NSString * key in keys) {
                    [validUIDs addObject:key];
        }
        
// Add a break point do you have any objects in your array here?
        if(validUIDs.count) {
            
            NSMutableArray * userPromises = [NSMutableArray new];
            
            // Loop over the IDs and get the users
            for(NSString * entityID in validUIDs) {
                
                CCUserWrapper * user = [CCUserWrapper userWithEntityID:entityID];
                [userPromises addObject:[user once].thenOnMain(^id(id<PUserWrapper> u) {
                    
// Add a break point - does this get called?

                    // Call add user again to udpate the list with the
                    // correct image - only add users who have names
                return Nil;
                }, Nil)];
            }
            
            [RXPromise all: userPromises].then(^id(id success) {
                [promise resolveWithResult:success];

// Add a break point, does this get called?

                return Nil;
            }, Nil);
        }
        else {
            [promise resolveWithResult:Nil];
        }
    }
    else {
        [promise resolveWithResult:Nil];
    }
}];

return promise;
}
 

All in all this code seems like it should work, the problem will probably be with a single step. The problem might also be somewhere different, for example maybe the [user once] isn't returning correctly. 

You can see each point I say to add a break point, you need to do this and go through your code step by step. In case you didn't know I have added some info below about this:

You can add break points to code by clicking the side:

<img width="398" alt="screen shot 2017-05-19 at 09 44 18" src="https://cloud.githubusercontent.com/assets/8721425/26240131/def0bc9a-3c77-11e7-99a5-519f66d3ae98.png">

The code will then stop when it reaches this point. 

You can turn this on and off with the break point button:

<img width="230" alt="screen shot 2017-05-19 at 09 44 11" src="https://cloud.githubusercontent.com/assets/8721425/26240153/edf36062-3c77-11e7-9e7e-be998f9b37b1.png">

You can also see a button which looks like an arrow going over a block. This will move you forward one line of code. Clicking the play button will move you forward to the next break point. 

You can then use the terminal in Xcode to find more information about your objects. Just type 

    po objectName

and it will show you what the current object is:

<img width="196" alt="screen shot 2017-05-19 at 09 44 33" src="https://cloud.githubusercontent.com/assets/8721425/26240205/1b09f426-3c78-11e7-8fed-112c699423bc.png">

As you can see we can easily find out the bool value and the snapshot value in the image above. 

Hopefully this helps you solve the issue and find out where your code is going wrong,

Simon

**Comment by RyanElliott94** [comment]
Hello,
Thanks for the detailed reply! It looks like the getContacts is getting the right keys and i think its correct but i have a feeling the way i use getContacts from BContactsViewController is causing this crash:

     -[RXPromise user]: unrecognized selector sent to instance 0x60000024fe40
     2017-05-19 15:17:05.962 Voice[20430:153367] *** Terminating app due to uncaught exception 
     'NSInvalidArgumentException', reason: '-[RXPromise user]: unrecognized selector sent to 
     instance 0x60000024fe40'
     *** First throw call stack:
    (
	0   CoreFoundation                      0x000000010bfabb0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010899c141 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010c01b134 -[NSObject(NSObject) 
     doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010bf32840 ___forwarding___ + 1024
	4   CoreFoundation                      0x000000010bf323b8 _CF_forwarding_prep_0 + 120
	5   ChatSDKUI                           0x0000000107fe5a98 -[BContactsViewController 
    tableView:cellForRowAtIndexPath:] + 216
	6   UIKit                               0x00000001093ef762 -[UITableView 
    _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 750
	7   UIKit                               0x00000001093ef9a8 -[UITableView 
    _createPreparedCellForGlobalRow:willDisplay:] + 74
	8   UIKit                               0x00000001093c42e9 -[UITableView 
    _updateVisibleCellsNow:isRecursive:] + 2845
	9   UIKit                               0x00000001093f897c -[UITableView 
    _performWithCachedTraitCollection:] + 111
	10  UIKit                               0x00000001093dfb2a -[UITableView layoutSubviews] + 233
	11  UIKit                               0x000000010934620b -[UIView(CALayerDelegate) 
     layoutSublayersOfLayer:] + 1268
	12  QuartzCore                          0x000000010f8e1904 -[CALayer layoutSublayers] + 146
	13  QuartzCore                          0x000000010f8d5526 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 370
	14  QuartzCore                          0x000000010f8d53a0 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
	15  QuartzCore                          0x000000010f864e92 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 294
	16  QuartzCore                          0x000000010f891130 _ZN2CA11Transaction6commitEv + 468
	17  QuartzCore                          0x000000010f891b37 _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 115
	18  CoreFoundation                      0x000000010bf51717 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	19  CoreFoundation                      0x000000010bf51687 __CFRunLoopDoObservers + 391
	20  CoreFoundation                      0x000000010bf36720 __CFRunLoopRun + 1200
	21  CoreFoundation                      0x000000010bf36016 CFRunLoopRunSpecific + 406
	22  GraphicsServices                    0x000000010f10ba24 GSEventRunModal + 62
	23  UIKit                               0x00000001092830d4 UIApplicationMain + 159
	24  Voice                               0x0000000107ada477 main + 55
	25  libdyld.dylib                       0x000000010d00b65d start + 1
	26  ???                                 0x0000000000000001 0x0 + 1
    )
     libc++abi.dylib: terminating with uncaught exception of type NSException
     (lldb) 

How I'm trying to use getContacts from the ViewController:

    -(void) reloadData {
    
    RXPromise * getContact = [[BNetworkManager sharedManager].a.core getContacts];

    dispatch_async(dispatch_get_main_queue(), ^{
        [_contacts addObject:getContact];
    });

    [self sortContacts];
    
    [tableView reloadData];
    }

I've tried looking at how users are searched for then added to the list and i have also looked to see how the loadMoreMessages works but it hasn't helped.

I should mention that the getContacts code is actually the code from userForIndex but with unnecessary stuff removed

Ryan

**Comment by simonsmiley64** [comment]
Hi @RyanElliott94,

Yes now that you have posted that code I can see why you would be getting errors. It would be worth you reading up on the [RXPromise library](https://github.com/couchdeveloper/RXPromise). 

I will give you a quick explanation:

A Promise is an object which represents an asynchronous task. A promise will then return an object or an error. We can then link them together and if any of them error they will return in the same error block. 

This is relevant as in your case you are adding multiple promises into an array called userPromises, you then call [RXpromise all: userPromises], this will run all the promises and return if they all return ok. This means your code needs to look more like this:

[[BNetworkManager sharedManager].a.core getContacts].thenOnMain(^(NSArray * userModels) {
    // This is the block which will return all your users

}, error^ {
    // This is the block which will return if there is an error
}

Remember as you are adding all the promises and calling 'all' it will return an array of users meaning you don't need to deal with them on at a time. You might need to do a bit of filtering in the completion area but it should be easy. 

A good code example to look at would be:

`-(RXPromise *) usersForIndex: (NSString *) index withValue: (NSString *) value limit: (int) limit userAdded: (void(^)(id<PUser> user)) userAdded`

You can see it has a similar flow and then calls the RXPromise all: at the end. In fact that bit of the flow is almost identical. 

It would also be worth you looking at other promises in the code, a good way to find them is to search for: thenOnMain as that is the completion block of a promise:

```
    [[BNetworkManager sharedManager].a.auth authenticateWithCachedToken].thenOnMain(^id(id<PUser> user) {
        if (!user) {
            [self showLoginScreen];
        }
        [self updateBadge];
        
        return Nil;
    },^id(NSError * error) {
        [self showLoginScreen];
        return Nil;
    });
```
You can see above that the promise itself is called like a normal function, it is only in creating the promise function that we need to create the promise variable (RXPromise *promise).

Hopefully that is enough information to get you going. Let me know if you get really stuck as we could always provide some priority support to get it all working and to explain how it all fits together,

Simon

**Comment by RyanElliott94** [comment]
Hello,

As before, thank you for the detailed reply! I should nearly be there now.

So far i can get the list of entity IDs from the contacts node but despite the NSArray being added to the BContactsViewController, they don't actually show up.

I feel like you should know how the contact is added in the first place as that may help you, help me.

    -(RXPromise *) addContactToFirebase: (id<PUser>) userToAdd{
    RXPromise * promise = [RXPromise new];
   
    FIRDatabaseReference * userRef = [[[FIRDatabaseReference userRef:_model.entityID] child:bContactsPath] child:userToAdd.entityID];
    
    [userRef setValue:@{bNameString:userToAdd.name} withCompletionBlock:^(NSError * error, FIRDatabaseReference * ref) {
        if (!error) {
            [promise resolveWithResult:self];
        }
        else {
            [promise rejectWithReason:error];
        }
    }];
    
    return promise;
    }
  
Now this is what i have so far with the getContacts method

    -(RXPromise *) getContacts {
    
    RXPromise * promise = [RXPromise new];
    
    FIRDatabaseReference * query = [[FIRDatabaseReference userRef:_model.entityID] child:bContactsPath];
    
    [query observeSingleEventOfType:FIRDataEventTypeValue withBlock:^(FIRDataSnapshot * snapshot) {
        
        if(snapshot.value != [NSNull null]) {
            
            // Get the keys of the dictionary
            NSDictionary * dict = snapshot.value;
            
            // Only add users that match the original query
            NSArray * keys = dict.allKeys;
            
            NSMutableArray * validUIDs = [NSMutableArray new];
            
            // Loop over the dictionary keys
            for (NSString * key in keys) {
            
                CCUserWrapper * user = [CCUserWrapper userWithEntityID:key];
                [validUIDs addObject:[user once].thenOnMain(^id(id<PUserWrapper> u) {
                    
                    return key;
                }, Nil)];
            }
            [RXPromise all: validUIDs].then(^id(id success) {
                [promise resolveWithResult:success];
                
                return Nil;
            }, Nil);
            
        }
    
    }];
    
    return promise;
    }

Then to load the contacts 

    -(void) reloadData {
    
    [[BNetworkManager sharedManager].a.core getContacts].thenOnMain(^id(NSArray * userModels) 
     {
        
       [_contacts addObject:userModels];
        
       return userModels;
     },^id(NSError * error) {
     return Nil;
    
      });
    
       [tableView reloadData];
      };

I should also note that on the android version, I also get the list of entity IDs from the contacts node and it works perfectly fine and that's why I'm trying the same on iOS but i have a feeling things are setup a little differently on here! But yeah, still need a little help.

Thanks
Ryan

**Comment by simonsmiley64** [comment]
Hi @RyanElliott94,

The line where you say:
```
     [_contacts addObject:userModels];
```
Doesn't look ideal. I would probably do the following:

```
     [_contacts removeAllObjects]; // empty the array to ensure we only have the returned contacts
     _contacts = userModels;
```
This is because you don't want to add the array into the array you want to add the items in the array to the array. 

Things to check:
- Add break points in, is the array in the getContacts returning as you want? If it is then we know the function is working and we are just not allocating the array properly

If the userModels isn't returning the user models then you need to check your function. If it is then you need to make sure you are using the objects correct. For example:

Check if you are adding the CCUserWrapper or the PUser object. It might be in the cell you need to call user.model to get the PUser object to work with. 

Let me know if this helps,

Simon

**Comment by RyanElliott94** [comment]
Hello,
I've tried everything that i could think of to get this to work but It's just not happening!

From my attempts so far, userModels has returned the CCUserWrapper without any bEntity values or _model values. I also tried returning the entityIDs but that also won't work!

I'm literally out of ideas now so if you have any idea on how to make the code above work then please tell me because I'm stuck on this now and there's still a lot more to do

Thanks
Ryan

**Comment by RyanElliott94** [comment]
Thought I'd update this quickly! So basically I've managed to do it, all be it slightly different to the way i was originally going to do it but done none the less.

I'll explain how just in case anyone wants to know!

As what i was trying before didn't work i figured another way would be to use the contacts from Firebase as backup for if someone was to uninstall the app but then install and use it again as the contacts normally would be contacts gone completely!

Here is the code I'm currently using.
 Reload data has been changed to this:
   
    -(void) reloadData {
    [self checkFirebaseForContacts];
    }

The method for  `[self checkFirebaseForContacts];`:

        -(void) checkFirebaseForContacts {
    [[BNetworkManager sharedManager].a.core getContacts].thenOnMain(^id(NSArray * userModels)
    {
        
    for(id<PUser> user in userModels){
        
    [[BNetworkManager sharedManager].a.contact addContact:user withType:bUserConnectionTypeContact];

    NSArray<PUserConnection> * allContacts = [[BNetworkManager sharedManager].a.core.currentUserModel connectionsWithType:bUserConnectionTypeContact];

    [_contacts removeAllObjects];
    [_contacts addObjectsFromArray:allContacts];
    [self sortContacts];
    [tableView reloadData];
        }
    return userModels;
    },^id(NSError * error) {
     return Nil;
                                                                        
     });
    }

Then the getContacts method:

      -(RXPromise *) getContacts {
    
    RXPromise * promise = [RXPromise new];
    
    FIRDatabaseReference * query = [[FIRDatabaseReference userRef:_model.entityID] child:bContactsPath];
    
    [query observeSingleEventOfType:FIRDataEventTypeValue withBlock:^(FIRDataSnapshot * snapshot) {
        
        if(snapshot.value != [NSNull null]) {
            
            // Get the keys of the dictionary
            NSDictionary * dict = snapshot.value;
            
            // Only add users that match the original query
            NSArray * keys = dict.allKeys;
            
            NSMutableArray * validUIDs = [NSMutableArray new];
            
            // Loop over the dictionary keys
            for (NSString * key in keys) {
                
                CCUserWrapper * user = [CCUserWrapper userWithEntityID:key];
                
                [validUIDs addObject:[user once].thenOnMain(^id(id<PUser> u) {
                    
                    return u;
                }, Nil)];
            }
            [RXPromise all: validUIDs].then(^id(id success) {
                [promise resolveWithResult:success];
                
                return Nil;
            }, Nil);
            
        }
        
    }];
    return promise;
    }

Whether this code could be better, i don't know but it works for me so for now i shall stick to it!

Massive thanks to you @simonsmiley64! I'm still very new to Objective-C but your help has helped me understand things a little more

Ryan
