### ISSUE TITLE
Keep getting the error - " No podspec found for `ChatSDK"

### ISSUE THREAD

**Issue by Absentia** [chat-sdk/chat-sdk-ios#58]
I'm new to the whole coacoapod installation process so I'm trying to figure it out as I go.  I'm following the integration tutorial video that can be found here - https://youtu.be/oeQhIN9utvE

In that video it shows the user dragging a "ChatSDK.podspec" file into their project, but when I download the SDK I can't find that file anywhere.  When I follow the rest of the instructions and run "pod install" I keep getting the following error "No podspec found for `ChatSDK` in....".  Should I assume that this tutorial video is outdated or am I missing something?

I noticed somebody else commented under the video with the same issue so at least I know I'm not the only one dealing with this.

**Comment by RyanElliott94** [comment]
Make sure that you copy the right files to right part of your project and when you do 'pod init' make sure the podfile goes into the main project folder, also you may find it easier to copy and paste the code from the podfile that is in the xcode folder as the one from the video doesn't work!

**Comment by simonsmiley64** [comment]
Hi @Absentia,

We have written a specific tutorial on linking the podfile to the podspec [here](https://github.com/chat-sdk/chat-sdk-ios/wiki/Chat-SDK-iOS:-How-do-I-link-my-podfile%3F)

The video above is slightly outdated but all the concepts are correct, it is just the folder structure is slightly different.

<img width="824" alt="screen shot 2017-05-19 at 09 52 03" src="https://cloud.githubusercontent.com/assets/8721425/26240472/0e919270-3c79-11e7-83b7-f4b90134ad7c.png">

You can see in the picture above of a project containing the Chat SDK. It is in its own ChatSDK folder. This means the podfile has to link to the podspec files in it, the path will probably be like this (assuming the podfile is in the project folder):

```
../ChatSDK/ChatSDK/ChatSDKCore
../ChatSDK/ChatSDK/ChatSDKUI
../ChatSDK/ChatSDK/ChatSDKCoreData
../ChatSDK/ChatSDK/ChatSDKFirebaseAdapter
```

If you are still struggling then send me a picture of your project structure and I will help you figure it out for your specific scenario,

Simon

**Comment by Absentia** [comment]
@simonsmiley64 

That did it - thank you!  Got it installed after following your tutorial, I greatly appreciate the help
