### ISSUE TITLE
[XMPP ChatSDK] Can't re-login with a different account in the same session

### ISSUE THREAD

**Issue by simonsmiley64** [chat-sdk/chat-sdk-ios#6]
How to reproduce:

1. Login with a new or existing user
2. Logout with user
3. Enter new details and register or login
4. The login then fails

We can fix this by re-building the project, this will re-load the login page and the user can now successfully login. The issue seems to be coming from doing this in the same session.

**Comment by bensmiley** [comment]
Fixed in latest version.
