### ISSUE TITLE
Can't install Module Contacts

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#60]
Ok -

Because of my custom installation. I am using FirebaseAuthUI for my authentication. This required me to install the Firebase pods. However, because of that I had conflicts with: ChatSDKFirebaseAdapter.

I then just copied that code and adjusted the imports and everything seemed to work. But now with the modules, it looks like I will have to hack the podspecs in the module contacts.

I think you should remove the firebase dependency and have people install firebase with its pods. Then install chatSDK.

**Comment by jimijon** [comment]
Arrgh. So it will be really a lot of work to make the modules work. We really need to be able to pod up an installation with FirebaseAuthUI. I don't think chat should include any firebase pods. Kind of important to get this resolved.

**Comment by bensmiley** [comment]
The problem is that the Firebase pods don't work with development pods and frameworks. This is why we included them manually. Currently if we include the Firebase modules in the podspec there is a header error. 

<img width="719" alt="screen shot 2017-05-22 at 00 04 33" src="https://cloud.githubusercontent.com/assets/5514010/26287778/47b0a874-3e82-11e7-9920-1ea93f62aaa9.png">

**Comment by jimijon** [comment]
Well they somehow do it for FirebaseUI. And now they upgraded all the firebase to 4.0. 

https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebaseUI.podspec
https://github.com/firebase/FirebaseUI-iOS/blob/master/build.swift

Any hints in there? 

And you should be working seamlessly with Firebase UI for the Auth portion. IMHO

**Comment by bensmiley** [comment]
This is the reply from Firebase support: 
  
>This is indeed a known issue. We have a bug regarding this and our engineers are already on it. However, this may take awhile and might not be available anytime soon. Kindly keep an eye out on our release notes for any updates. In the mean time, you may check the concept presented [here](https://github.com/1amageek/Salada/issues/32) by one of our engineer if it would help to your case.

>I'm sorry for any inconvenience this might have caused you.

They suggested a workaround but it looks complex.

**Comment by bensmiley** [comment]
I was looking at this this morning and I've found a work around. The point is that Firebase should be imported once. So there are two options:

1. Drag the Firebase Network Adapter classes directly into your project and import Firebase in your main podfile
2. Fork the repository you want to use and remove the dependency to Firebase from the podspec. Then add a dependency to the ChatSDKFirebaseAdapter. That way it will have access to the Firebase pods that are included via the vendored frameworks. You should then import this as a development pod in your podfile.

**Comment by jimijon** [comment]
1) Do you mean copy the entire ChatSDKFirebaseAdapter directory directly? That is how I got this all to work last month. 

Or, do you mean drag over just BFirebaseNetworkAdapter.m and h inside ChatSDKFirebaseAdapter?

2) So, I think I was close, just need to try adding the dependency to ChatSDKFirebaseAdapter.

**Comment by jimijon** [comment]
OK,,, it wasn't so bad as I had already copied over ChatSDKFirebaseAdapter directory and fixed its imports. Looks like I only had to comment out: //#import <ChatSDKFirebase/ChatFirebaseAdapter.h>
for the modules to work.

**Comment by jimijon** [comment]
Sooooo... since this is fairly easy to implement. Why don't you make this the default install instructions and change the headers in ChatFirebaseAdapter? Or have both! One special install procedure for Firebase.
