### ISSUE TITLE
Change ChatView Title color to yellow

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#62]
OK -

I have tried all the obvious reasons to set the title on the ChatView to anything but black. What is the secret I am missing?

**Comment by jimijon** [comment]
Finally found the problem. The Chat window inherits "ElmChatViewController" which doesn't set a nav title but instead sets a titleView (setNavigationBar).  Is there a way to override this Controller? Right now I am using my "fork" to make changes but this seems like something that should be more customizable.

**Comment by bensmiley** [comment]
In some situations it's best to make the modification directly to the core framework. I'd recommend exposing the `_titelLabel` as a property and then submitting a pull request so we can add it to the core framework.

**Comment by ilyanengen** [comment]
You can edit method initWithThread in your subclass of BChatViewController like this:

- (id)initWithThread: (id<PThread>) thread
{
    _thread = thread;
    
    // Reset the working list (so we don't load any more messages than necessary)
    [_thread resetMessages];
    self = [super initWithDelegate:self];
    if (self) {
        _messageCache = [NSMutableArray new];
        
    //change text color to red
        _titleLabel.textColor = [UIColor redColor];
    }
    return self;
}

**Comment by jimijon** [comment]
@ilyanengen  I went back and changed my approach to yours and it seems more proper. Worked like a charm. Thank you.
