### ISSUE TITLE
Where are my stickies?

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#63]
Did I miss a step?

I don't see anything different in my chat. I did see the contact book import for contacts!

**Comment by simonsmiley64** [comment]
Hi @jimijon,

To get Stickers working you need to add two modules into your project:

+ KeyboardOverlayOptions
+ StickerMessages

You should be able to download both these modules from the website and they should both contain a readMe telling you what to add. 

You can see full instructions [here](https://github.com/simonsmiley64/chat-sdk-ios/blob/master/Docs/Modules/StickerMessages.md)

Then when you click the + button the keyboard overlay will show:

<img width="262" alt="screen shot 2017-05-23 at 10 21 22" src="https://cloud.githubusercontent.com/assets/8721425/26347510/b7d5a832-3fa1-11e7-9151-9aa136c59184.png">

and you can then click to send stickers:

<img width="253" alt="screen shot 2017-05-23 at 10 21 57" src="https://cloud.githubusercontent.com/assets/8721425/26347514/bb2a49de-3fa1-11e7-9b69-788916fbd55f.png">

I have just updated the README to include a few extra lines to be added to the podfile so this might be the problem you were finding. 

Let me know if you are still having trouble,

Simon

**Comment by jimijon** [comment]
Whoops... I had the "hardware keyboard toggled on", when I turned it off they appeared
