### ISSUE TITLE
Getting Clang issues in integrate previous package

### ISSUE THREAD

**Issue by Karthickkck** [chat-sdk/chat-sdk-ios#68]
Hi Team,
Am try to integrate chatsdk to my previous app means am getting below type of error. after pod installation.
### Am open xcworkspace only. not open in xcodeproj
: Linker command failed with exit code 1 (use -v to see invocation)
Please find the screen shot
![screen shot 2017-05-31 at 12 21 15 am](https://cloud.githubusercontent.com/assets/19325688/26599703/27b25420-4597-11e7-835f-1d5076c65dd2.png)

**Comment by bensmiley** [comment]
Could you show a screenshot of the detailed error message?

**Comment by jimijon** [comment]
Hmmm, I am getting this:

Undefined symbols for architecture x86_64:
  "_TWTRIdentifierForAdvertising", referenced from:
      +[TWTRCardConfiguration deviceID] in TwitterKit(TWTRCardConfiguration.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jimijon** [comment]
Mine was solved by changing the reference in the pod from FirebaseUI to FirebaseDatabase.
