### ISSUE TITLE
ENABLE_BITCODE Error?

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#69]
ChatSDKCore/ChatSDKCore.framework/ChatSDKCore' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

**Comment by CalvinTp** [comment]
Hi,
I have posted the steps to resolve this. You can refer to them at #54 to solve this.

To permanently solve this, individual framework can enable bit code for these framework that reported error. 

Thanks,
Calvin

**Comment by bensmiley** [comment]
Fixed in https://github.com/chat-sdk/chat-sdk-ios/commit/9361514db9da4c99ef143bf47baa48973efb387e

**Comment by jimijon** [comment]
Please fix :  ChatSDKModules.podspec  also.
