### ISSUE TITLE
Please no "control reaches end of non-void function" functions.

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#70]
Because I integrate FirebaseAuthUI, I have to manually import in MyChatFirebaseAdapter and change the headers etc., However, I keep having to fix these little pests:

```
// TODO: Implement this
-(RXPromise *) leaveThread: (id<PThread>) thread {
}

-(RXPromise *) joinThread: (id<PThread>) thread {  
}
```

Could you just put in a:
    `return nil;`

**Comment by bensmiley** [comment]
If you are inheriting from the `BAbstractCoreHandler` these shouldn't present a problem because they are already implemented. 

```
-(RXPromise *) leaveThread: (id<PThread>) thread {
    assert(NO);
}

-(RXPromise *) joinThread: (id<PThread>) thread {
    assert(NO);
}
```

**Comment by jimijon** [comment]
@bensmiley  this is in: 
BFirebaseCoreHandler

Which is implementing the Abstract methods as:

// TODO: Implement this
-(RXPromise *) leaveThread: (id<PThread>) thread {
}

-(RXPromise *) joinThread: (id<PThread>) thread {
}
