### ISSUE TITLE
How to Refresh Token for Custom Tokens

### ISSUE THREAD

**Issue by danielmogilny** [chat-sdk/chat-sdk-ios#71]
How do I refresh a token after it's expired within Chat SDK (Custom tokens expire after an hour for Firebase tokens). If this feature doesn't exist I can easily code it in, but I'd really appreciate if you could point me to the correct file in Chat SDK to modify.

**Comment by bensmiley** [comment]
Custom tokens must be used within 1 hour of being generated but once used to authenticate a user, the user will stay logged in until they log out.
