### ISSUE TITLE
Request for guidance on customizing the user interface

### ISSUE THREAD

**Issue by Geov40** [chat-sdk/chat-sdk-ios#74]
Hi, Need guidance on customizing the user interface of the chat. Are there any documentation available on this topic. Thanks for the help in advance.

**Comment by bensmiley** [comment]
I'd recommend reading this [document](https://github.com/chat-sdk/chat-sdk-ios/wiki/Exploring-the-Chat-SDK-Architecture#customizing-the-user-interface). If you need any more guidance, let me know and I'll add it to the document.

**Comment by bensmiley** [comment]
Full instructions now available [here](https://github.com/chat-sdk/docs#customizing-the-user-interface).
