### ISSUE TITLE
Help with TwitterKit

### ISSUE THREAD

**Issue by blackhattristar** [chat-sdk/chat-sdk-ios#77]
How would I go about retrieving the users email and passing it to the database when they login using Twitter? Right now it only passes the username and I have my Twitter application setup correctly as well as tried many codes. Any help would be greatly appreciated.

**Comment by bensmiley** [comment]
There is no way to access the user's twitter username or password. The app logs into Firebase using OAuth so neither the developer or Firebase have access to these details.

**Comment by blackhattristar** [comment]
I'm not looking to retrieve the username and password. I would like to get the users email. How would I got about passing the users Email to the database?

**Comment by bensmiley** [comment]
If the user logs in via Twitter I don't think there's a way to get their email.
