### ISSUE TITLE
Can't find <ChatSDKCore/ChatCore.h>

### ISSUE THREAD

**Issue by RyanElliott94** [chat-sdk/chat-sdk-ios#80]
Right i was hoping not to open an issue about this but every time i run pod install i always get that error plus this <ChatSDKUI/ChatUI.h> not found. Now normally i fix it every time but i can't for the life of me remember how i do it!

So if someone can then please let me know how!

Thanks

**Comment by RyanElliott94** [comment]
Sorry, never mind, sorted its self out somehow!

**Comment by cesariel** [comment]
@RyanElliott94 How do you solve the issue?
