### ISSUE TITLE
Photo groups

### ISSUE THREAD

**Issue by ciaoamigo** [chat-sdk/chat-sdk-ios#83]
How do I add a photo to my group profile? It's possible?

**Comment by bensmiley** [comment]
Currently this isn't possible. The group just uses a photo based on the profile pictures of the members. I'll add this as a feature request.

**Comment by Meet1313** [comment]
I have just solved this 

- (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary *)info
{
    UIImage *chosenImage = info[UIImagePickerControllerEditedImage];
    
    self.groupImgview.image = chosenImage; //  add imageview 
    
    [picker dismissViewControllerAnimated:YES completion:NULL];
    
    //image-url
    
    id<PThread> thread = _thread;
    
    // Set the image now
    [NM.upload uploadImage:chosenImage thumbnail:nil].thenOnMain(^id(NSDictionary * urls) {
        
        
        NSLog(@"%@", [urls valueForKey:@"image"]);
        
        [NM.core addgroupImage :[urls valueForKey:@"image"] toThread: thread];
       
        return urls;
    }, Nil);
    
    
}

-(RXPromise *) addgroupImage : (NSString *)groupImgUrl toThread: (id<PThread>) threadModel
{
    CCThreadWrapper * thread = [CCThreadWrapper threadWithModel:threadModel];
    
    FIRDatabaseReference * threadDetailsRef = [[FIRDatabaseReference threadRef:[threadModel entityID]] child:bDetailsPath];
    RXPromise * promise = [RXPromise new];
    // Add the user entities to the thread too
    
    NSLog(@" thread data :%@",thread);
    
    FIRDatabaseReference * ref = Nil;
    ref = [FIRDatabaseReference threadRef:[threadModel entityID]];
    
    NSTimeInterval since1970 = [[threadModel creationDate] timeIntervalSince1970]; // January 1st 1970
    
    double result = since1970 * 1000;
    NSDictionary *dic = @{bDetailsPath: @{b_CreationDate: [NSNumber numberWithDouble:result] ,
                                          b_Name: [threadModel name],
                                          b_Type:  [[threadModel type]integerValue] & bThreadTypePrivate ? @(bThreadTypePrivateV3) : @(bThreadTypePublicV3),
                                          b_TypeV4: [threadModel type],
                                          b_LastMessageAdded: [BFirebaseCoreHandler dateToTimestamp:[threadModel lastMessageAdded]],
                                          b_CreatorEntityID: [threadModel creatorEntityID],
                                          bThreadURLKey: groupImgUrl,
                                          }};
    
    [ref updateChildValues:dic withCompletionBlock:^(NSError * error, FIRDatabaseReference * ref) {
        if (!error) {
            [promise resolveWithResult:threadModel];
        }
        else {
            [promise rejectWithReason:error];
        }
    }];

    return promise;
}

**Comment by bensmiley** [comment]
Supported in latest version.
