### ISSUE TITLE
Unable to select location to send

### ISSUE THREAD

**Issue by RogerRabbit91** [chat-sdk/chat-sdk-ios#84]
First off I really appreciate this code. It saved me a lot of time. On the android version I am able to select a location and send it. Then the recipient gets GPS directions to the marker. On the iOS version my location is automatically sent and provides the recipient with no directions. How can I fix this issue. Thanks.

**Comment by bensmiley** [comment]
Currently in the iOS version, it just sends the current location. I'll set this issue as a feature request to be able to choose the location before sending.

**Comment by muhammadsr** [comment]
I would like this feature as well
