### ISSUE TITLE
ChatSDK presence management (online, offline) enhancement

### ISSUE THREAD

**Issue by CalvinTp** [chat-sdk/chat-sdk-ios#87]
Hi Ben, Simon,

For ChatSDK user online, offline, away (presence management), I would suggest to use the method provided by Firebase, and the example is shown as below:
https://stackoverflow.com/questions/22290917/firebase-presencemanaging-ios

The mechanism is simple and also pretty robust. It will able to detect the user when it gets disconnected abruptly (meaning without ability to move the status to "false". 

More material on Firebase presence system:
https://firebase.googleblog.com/2013/06/how-to-build-presence-system.html

Thanks,
Calvin

**Comment by bensmiley** [comment]
I believe we already do this:

`CCUserWrapper.m`
```
-(void) goOnline {
    // When the push is complete mark the user as online
    FIRDatabaseReference * userOnlineRef = [FIRDatabaseReference userOnlineRef:self.entityID];
    [userOnlineRef setValue:@YES];
    [userOnlineRef onDisconnectSetValue:@NO];
}

-(void) goOffline {
    FIRDatabaseReference * userOnlineRef = [FIRDatabaseReference userOnlineRef:self.entityID];
    [userOnlineRef setValue:@NO];
}
```

**Comment by CalvinTp** [comment]
Hi Ben,
Yea, you are right, really sorry for the late reply.

I have also read and checked it previously, your codes handle the varies condition of the app going to background etc as well, therefore the codes are good. 

Thanks,
Calvin
