### ISSUE TITLE
Firebase UI worked! Now Firebase/Database etc. doesn't  :-(

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#89]
The 'Pods-SharedPods-TwoBitTrader' target has frameworks with conflicting names: firebaseanalytics.framework, firebasecore.framework, firebasedatabase.framework, and firebaseinstanceid.framework.

Trying to import Firebase/Database and Invite.

**Comment by bensmiley** [comment]
You won't be able to add any Firebase pods to the Podfile see this [note](https://github.com/chat-sdk/chat-sdk-ios/wiki/Issues-with-Firebase-Pods). I'd recommend following the option 2 if you need to use other Firebase pods.

**Comment by jimijon** [comment]
ARrrrg. That was what I was doing.

You should have a ChatSDKFirebaseAdapter with the Imports changed for direct inclusion.
