### ISSUE TITLE
ThreadViewController not showing messageTextView when app is relaunched

### ISSUE THREAD

**Issue by CalvinTp** [chat-sdk/chat-sdk-ios#90]
Hi,
I have just tested the latest code you released and found the issue below:

- Close ChatSDK app by pressing the home button.
- Double click at the home button and remove the ChatSDK from the list.
- Relaunch ChatSDK app 
- All the threads in the ThreadViewController will show an empty text in the messageTextView in the ThreadViewCell. 

Seems like each time ChatSDK is relaunch this issue will happen. It will recover after some time when the user clicks on the other tabs (e.g Public Chat, Contacts) and then return to the ThreadViewController. 

I didn't debug to root cause this but wanted to log this issue so that you can take a look.

Thanks,
Calvin

**Comment by CalvinTp** [comment]
Hi,
I have found this issue and also propose a fix for this.

**Issue:**
Based on the new codes the array of the thread is actually based on _messageWorkingList. However the _messageWorkingList is only initialised when the "messageWorkingList" is called. But non of the method is calling it hence _messageWorkingList remains null

```
-(NSMutableArray *) messagesWorkingList {
    if(!_messagesWorkingList) {
        _messagesWorkingList = [NSMutableArray new];
        [self resetMessages];
    }
    return _messagesWorkingList;
}
```

**Fixes:**
I am using the fix below and it working for me. The thread no longer shows "null" when the app is called after it is killed. 


```
-(NSArray *) messagesOrderedByDateAsc {
    //return [self orderMessagesByDateAsc:_messagesWorkingList];
    return [self orderMessagesByDateAsc:self.messagesWorkingList];
}

-(NSArray *) messagesOrderedByDateDesc {
    //return [_messagesWorkingList sortedArrayUsingComparator:^(id<PMessage> m1, id<PMessage> m2) {
    return [self.messagesWorkingList sortedArrayUsingComparator:^(id<PMessage> m1, id<PMessage> m2) {
        return [m2.date compare:m1.date];
    }];
}
```

You can consider pushing this fix or restructuring it so that others can also solve this issue.

Thanks,
Calvin

**Comment by CalvinTp** [comment]
Hi,
To handle varies conditions of the thread messages, I have also added the following code to ensure the messages are more than 1 element before the sorting of array started. 

This will prevent the app from crashing if the thread message only has 1 element (as an example). 

```
-(NSArray *) orderMessagesByDateAsc: (NSArray *) messages {
    if (messages.count > 1) {
        return [messages sortedArrayUsingComparator:^(id<PMessage> m1, id<PMessage> m2) {
            return [m1.date compare:m2.date];
        }];
    } else {
        return messages;
    }
}

-(NSArray *) messagesOrderedByDateAsc {
    if (self.messagesWorkingList.count > 1) {
        return [self orderMessagesByDateAsc:self.messagesWorkingList];
    } else {
        return self.messagesWorkingList;
    }
}

-(NSArray *) messagesOrderedByDateDesc {
    if (self.messagesWorkingList.count > 1) {
        return [self.messagesWorkingList sortedArrayUsingComparator:^(id<PMessage> m1, id<PMessage> m2) {
            return [m2.date compare:m1.date];
        }];
    } else {
        return self.messagesWorkingList;
    }
}

-(NSArray *) orderMessagesByDateDesc: (NSArray *) messages {
    if (messages.count > 1) {
        return [messages sortedArrayUsingComparator:^(id<PMessage> m1, id<PMessage> m2) {
            return [m2.date compare:m1.date];
        }];
    } else {
        return messages;
    }
}
```

Please consider pushing the code or restructuring it for ChatSDK.

Thanks,
Calvin

**Comment by bensmiley** [comment]
This appears to have been fixed at some point.
