### ISSUE TITLE
Delete Thread propose fixes

### ISSUE THREAD

**Issue by CalvinTp** [chat-sdk/chat-sdk-ios#93]
Hi,
I think I noticed some issue with deleting thread while reading the codes and below is the proposed fix: 

**Issue:**
When the user is deleting the threads from BUsersViewController or BPrivateThreadsViewController, the observers are not being removed first. This will cause the ChatSDK to crash if there is any incoming new message received from other users while the thread is being deleted. 

For example in the BUsersViewController, when the Leave Conversation is clicked the following codes are being executed:
```
    if (indexPath.section == bLeaveConvoSection) {        
        [NM.core deleteThread:_thread];
        [NM.core leaveThread:_thread];

```

Inside the deletethread method, it will directly call the deleteThread without removing the observer. 
```
-(RXPromise *) deleteThread: (id<PThread>) thread {
    return [[CCThreadWrapper threadWithModel:thread] deleteThread]

```

Below is what I have changed on my side and it consist of 2 parts:

**Fix Part 1:**
```
-(RXPromise *) deleteThread: (id<PThread>) thread {  
    //return [[CCThreadWrapper threadWithModel:thread] deleteThread]
    
    //Remove observer from the thread to avoid race conditions
    [[CCThreadWrapper threadWithModel:thread] off];
    [[CCThreadWrapper threadWithModel:thread] messagesOff];
    
    return[[CCThreadWrapper threadWithModel:thread] deleteThread].thenOnMain(^id(id result) {
            return result;
        }, Nil);
}
```

**Fix Part 2:**
I have temporarily removed the following code in the BStateManager because it will cause the deleteThread to be executed twice. When the user is trying to delete the method, the observerEventType will be triggered and this will call the deleteThread again. 

I can foresee this is only useful if another user can delete a thread and force all the users who is still inside thread to delete their thread.
```
    /*
    [threadsRef observeEventType:FIRDataEventTypeChildRemoved withBlock:^(FIRDataSnapshot * snapshot) {
        // Returns threads one by one
        if (snapshot.value != [NSNull null]) {
            // Make the new thread
            CCThreadWrapper * thread = [CCThreadWrapper threadWithEntityID:snapshot.key];
            [thread off];
            [thread messagesOff]; // We need to turn the messages off incase we rejoin the thread
            
            [NM.core deleteThread:thread.model];
        }
    }];
    */
```

It would be great if these changes can be integrated into the ChatSDK in one of your future releases. 

Thanks,
Calvin

**Comment by bensmiley** [comment]
Fixed in 4.3.7.
