### ISSUE TITLE
Android-to-iOS Notifications aren't working?

### ISSUE THREAD

**Issue by RyanElliott94** [chat-sdk/chat-sdk-ios#94]
Hello, 
So when sending a message from an Android device to an iOS device, you don't receive a notification unless you go into the app. However if it's the other way round, it'll work fine.

I'm sure there was an issue on here a while back but i can't find it, so any help would be grand.

Thanks,
Ryan

**Comment by RyanElliott94** [comment]
Any chances of me getting help on this? 

Ryan

**Comment by jimijon** [comment]
I think that is a Firebase notification issue. And how you setup iOS to handle the notifications. Did you first just send the iOS app a notification from the Firebase Web Panel? How was the behavior?

**Comment by RyanElliott94** [comment]
I've closed the issue due to having another one open.

**Comment by developer2311** [comment]
You need to change some code in FirebasePushHandler for correctly working notifications.
It may be "copy-pasted" FireBasePushHandler implementation to your custom class and change FirebasePushHandler to your custom push handler after initialization ChatSDK.
